// Package apiauth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apiauth

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UserRole.
const (
	Admin     UserRole = "admin"
	Candidate UserRole = "candidate"
	Employer  UserRole = "employer"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Candidate:
		return true
	case Employer:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	Active  UserStatus = "active"
	Blocked UserStatus = "blocked"
	Deleted UserStatus = "deleted"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Blocked:
		return true
	case Deleted:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ExternalCallbackRequest defines model for ExternalCallbackRequest.
type ExternalCallbackRequest struct {
	Code        string  `json:"code"`
	RedirectUri *string `json:"redirectUri,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Role     UserRole            `json:"role"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	NewPassword string `json:"newPassword"`
	Token       string `json:"token"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessExpiresAt  time.Time `json:"accessExpiresAt"`
	AccessToken      string    `json:"accessToken"`
	RefreshExpiresAt time.Time `json:"refreshExpiresAt"`
	RefreshToken     string    `json:"refreshToken"`
	User             User      `json:"user"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Token string `json:"token"`
}

// User defines model for User.
type User struct {
	CreatedAt       time.Time           `json:"createdAt"`
	Email           openapi_types.Email `json:"email"`
	EmailVerifiedAt *time.Time          `json:"emailVerifiedAt,omitempty"`
	Id              openapi_types.UUID  `json:"id"`
	Role            UserRole            `json:"role"`
	Status          UserStatus          `json:"status"`
}

// UserRole defines model for UserRole.
type UserRole string

// UserStatus defines model for UserStatus.
type UserStatus string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ForgotPasswordJSONBody defines parameters for ForgotPassword.
type ForgotPasswordJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// ResendConfirmationJSONBody defines parameters for ResendConfirmation.
type ResendConfirmationJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// ConfirmEmailJSONRequestBody defines body for ConfirmEmail for application/json ContentType.
type ConfirmEmailJSONRequestBody = TokenRequest

// ExternalCallbackJSONRequestBody defines body for ExternalCallback for application/json ContentType.
type ExternalCallbackJSONRequestBody = ExternalCallbackRequest

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody ForgotPasswordJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ResendConfirmationJSONRequestBody defines body for ResendConfirmation for application/json ContentType.
type ResendConfirmationJSONRequestBody ResendConfirmationJSONBody

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ConfirmEmail Подтверждение email по токену из письма
	// (POST /auth/confirm-email)
	ConfirmEmail(c *gin.Context)
	// ExternalCallback Callback внешнего identity-провайдера (задел под Keycloak/OIDC)
	// (POST /auth/external/{provider}/callback)
	ExternalCallback(c *gin.Context, provider string)
	// ForgotPassword Запрос на сброс пароля
	// (POST /auth/forgot-password)
	ForgotPassword(c *gin.Context)
	// Login Логин по email/паролю
	// (POST /auth/login)
	Login(c *gin.Context)
	// Logout Отзыв refresh-токена
	// (POST /auth/logout)
	Logout(c *gin.Context)
	// Me Текущий пользователь
	// (GET /auth/me)
	Me(c *gin.Context)
	// Refresh Обновление access-токена
	// (POST /auth/refresh)
	Refresh(c *gin.Context)
	// Register Регистрация пользователя
	// (POST /auth/register)
	Register(c *gin.Context)
	// ResendConfirmation Повторная отправка письма с подтверждением
	// (POST /auth/resend-confirmation)
	ResendConfirmation(c *gin.Context)
	// ResetPassword Установка нового пароля по токену
	// (POST /auth/reset-password)
	ResetPassword(c *gin.Context)
	// Healthz Liveness probe
	// (GET /healthz)
	Healthz(c *gin.Context)
	// InternalGetUser Внутренний эндпоинт — получить пользователя по ID (для других сервисов)
	// (GET /internal/users/{userId})
	InternalGetUser(c *gin.Context, userId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ConfirmEmail operation middleware
func (siw *ServerInterfaceWrapper) ConfirmEmail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ConfirmEmail(c)
}

// ExternalCallback operation middleware
func (siw *ServerInterfaceWrapper) ExternalCallback(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", c.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter provider: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExternalCallback(c, provider)
}

// ForgotPassword operation middleware
func (siw *ServerInterfaceWrapper) ForgotPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ForgotPassword(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// Me operation middleware
func (siw *ServerInterfaceWrapper) Me(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Me(c)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Refresh(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// ResendConfirmation operation middleware
func (siw *ServerInterfaceWrapper) ResendConfirmation(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResendConfirmation(c)
}

// ResetPassword operation middleware
func (siw *ServerInterfaceWrapper) ResetPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResetPassword(c)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// InternalGetUser operation middleware
func (siw *ServerInterfaceWrapper) InternalGetUser(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.InternalGetUser(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.POST(options.BaseURL+"/auth/confirm-email", wrapper.ConfirmEmail)
	router.POST(options.BaseURL+"/auth/resend-confirmation", wrapper.ResendConfirmation)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.Refresh)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.POST(options.BaseURL+"/auth/forgot-password", wrapper.ForgotPassword)
	router.POST(options.BaseURL+"/auth/reset-password", wrapper.ResetPassword)
	router.GET(options.BaseURL+"/auth/me", wrapper.Me)
	router.POST(options.BaseURL+"/auth/external/:provider/callback", wrapper.ExternalCallback)
	router.GET(options.BaseURL+"/internal/users/:userId", wrapper.InternalGetUser)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FnvbhvHEX+Vw7YfbOAkSoo/uPzmOFKrWkkE/2k/GEJxuhuJGx1vL3tLxYpAQKKSNobVGi0CFGiRuG1e",
	"gGHFWLFM+hVmX6FPUszuHXmk7khaloQgn0Ryd2dn5zd/fjPaZ76oxyKCSCWsus8kJLGIEjBf3veC+/Bp",
	"AxJF33wRKYjMRy+OQ+57iouo8kkiIvot8WtQ9+jTLyVssSr7RWUoumJXk8qylEKyZrPpsgASX/KYhLAq",
	"w2+wix3s6gPs6Wf4o4MvsY1v9AH29SFruuyuiLZC7l+HKv/APvb0F3iGp/hKt5wb2Et1OcXXpKLrQN3j",
	"oaOP8AfsWlV7+rlu3SRNV4Tc5EEA0TWo+jWZR7f0Eb4ZWqyrn+q/Yo90+UioFdGIgusB0DGG+hFPsIs9",
	"7JMCjyKvoWpC8s/h2pRoY0e3sG/weol97BA8jHanAki+lVHdZ7EUMUjFrc/7IgD6C0+8ehwCq7LlD++s",
	"rv3h4Z17yx8xl6m9mH5MlOTRNj2wDknibY+dse7hhRK8YM+RsM0TBRKC8wKaLpPwaYPTYvWxvX4odGOw",
	"X2x+Ar6iC5efKJCRF971wnDT83dyIVr8lHMqSwi4BF89kpzWt4Sse4pVWUPy2RQsUmtNbPOoVBdjkJHL",
	"7C8FBo29JPlMyKBA9TFdMhGDE0V63YctCUmtVDNp1x+KHRuwk68c2V18ncX6si1R956sQbStaqy6uHTb",
	"ZXUeZd9vFxyVIoRpUfQoAXmf9k21ayqv+L0JqPV0Y+mjI/hs/eKPUbNhY7e5I5cVqWzAW/d4QfR7vg9J",
	"svwk5hKSO2oEpsBTMKd4HYqgsgfLnMjN/OYCkqf4p8saCchZoD5nr7zOY/e45yxR8IT06lITl3rDW+FZ",
	"JP5R+uSxfCfBUxC8jXHfIhjNwu9A8i0+wx2Ps5MuixphyDaaLuPBaLZt8IC9c+i6LFGeaiSznHhgd47b",
	"2aiRvdvcPhDq5oxaBsT9VF+IGnVTIbwo4GQRIzUOxR5IcqigzvNoDh+cUy0nxvMV3yUZm6Hwd0zpDCAE",
	"BUGBEDID+A3J1d4DerB1iE3wJMg7Dcor2beVzPy//f1DlhICkmRXh3jUlIotw+DRlqDzY0zjX9jF/+Kp",
	"YV8H2NZ/xFP93HXwDfbxRLdSLvtDyoVOsWs5o+vgGfbpJPZcJ40p19GH+L3luiShTR/xzMjrYA+7+qtU",
	"Bg8gUlztzZOmXBmysfJg3VkPPUWe5fzv4GuHXuw8ALnLfTLgLsjEKr04vzC/QCYXMURezFmVvTe/OL9g",
	"cr2qGaNViK9VfBFtcVmfGwRILGwkU8AZyrYasKoh5VzWlzPnsRH/vgj2Lo3rjaSS5qjvKtkA80OuaVla",
	"uHUeLaNgATYZTb61sFCmx0B4JdcOGYdr1Oue3CNfeDEZc3OxQ5QUX9GKPnKImdLP5D/H+BrbhKe3nRjP",
	"J4fdoCssFpASvsp+LMUuD0A2K35K/sqhGaeJBmPp1UGBpGv2GSfLEO6UpDwTBdkFbNzKbg6tIc3dgT0/",
	"FN5OAWvcuBpvKCO/MznGwuU6paEQRU3Id/oQ39igta1sR39JHmI9bXG6p400TaO+lj08nxgoEfUHqWHO",
	"ds2m6zGtGKUn54bpDskxz9I4cO6l6FU+Xv3g7s0JDrgl5LZQc3k6WuxzK2bjeo42XtAFLkiZC3ns+bo1",
	"i68sFaT8F6ajNI0+9p0baWx39KFB4ATbBEofX2LHVISn2MaubjlLC0sOnlA6Ny26foqnuqWfOdjXLYfK",
	"XWrCm+Np5e/DCYjprMuqxAToQurKygEzTdsVJe6RhvDnHJ906L3ph4ZjoTGY/5nxAVsnjFtVcvj+ZTK+",
	"oqEmAkzrV4PwWGt90eKM/8auPtSHRKDsEMvUUf2VqaLtd8iaKSU01S5PBh9vUH3KQfCtbuFL/Qw7GSOb",
	"G1bribW5bqjvNhSY/kNgV+jhaUd33rlfmATxBZ7imT62qf5MH2dzMN2iCqCfX4dR/4NdfKWPKN9RkBVr",
	"cjzBuCkW5d6dOuBPyL2vK4V9kxrxeVYI2jl+SWuXwTXwW/zeSsOzAaO1g4FZ4yMbfU7CMN1xVSCOzuNm",
	"QnHxGsK0OBqoxBODOME29Ye5DqHv2Kpf0mnga8MnDF9oDwDrX6i5oSO/mn5k8B+ZMa8p7IzLM9Ek50kg",
	"CubSXtSzpiv3I9p8N7/3Z80/LUy3psM0+BdQQdOa/Z+kZ1NJ3oFeEZ3NNajT3G8KjrO0DyOz5CvLBwXz",
	"6gszlxcDknbsYH+YLS9prvAdxRBlAiPVIGI/9k3Hl+8Bzs8YigGpgReq2uelrOU36fo7VrbRABqOKIez",
	"A7EzNX7SY8UBNIrEx/fGbLfGdyGCJHFiKTYhZwtrgNQaPEpHK40EZFLZpz+rQbPUOqvp/l+DMpl9lpmK",
	"lTlxojJlJmyHKddOJEv42rvmnb+Rc5rSQLmjZ8ih/jP28MSkF0pwLTPGTCvGkf6TaZjLyaz1/dUPnBtZ",
	"m32iD/SRKUJfUkWlZNWhVEbniiYdhtfK3QzFUUusCd8LnQB2mcsaMkyHw9VKJaSFmkhU9fbC7UVGMKWC",
	"9zPwzQVNd/A99b7mRvP/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
