// Package apiauth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apiauth

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UserRole.
const (
	Admin     UserRole = "admin"
	Candidate UserRole = "candidate"
	Employer  UserRole = "employer"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Candidate:
		return true
	case Employer:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	Active  UserStatus = "active"
	Blocked UserStatus = "blocked"
	Deleted UserStatus = "deleted"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Blocked:
		return true
	case Deleted:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ExternalCallbackRequest defines model for ExternalCallbackRequest.
type ExternalCallbackRequest struct {
	Code        string  `json:"code"`
	RedirectUri *string `json:"redirectUri,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Role     UserRole            `json:"role"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	NewPassword string `json:"newPassword"`
	Token       string `json:"token"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessExpiresAt  time.Time `json:"accessExpiresAt"`
	AccessToken      string    `json:"accessToken"`
	RefreshExpiresAt time.Time `json:"refreshExpiresAt"`
	RefreshToken     string    `json:"refreshToken"`
	User             User      `json:"user"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Token string `json:"token"`
}

// User defines model for User.
type User struct {
	CreatedAt       time.Time           `json:"createdAt"`
	Email           openapi_types.Email `json:"email"`
	EmailVerifiedAt *time.Time          `json:"emailVerifiedAt,omitempty"`
	Id              openapi_types.UUID  `json:"id"`
	Role            UserRole            `json:"role"`
	Status          UserStatus          `json:"status"`
}

// UserRole defines model for UserRole.
type UserRole string

// UserStatus defines model for UserStatus.
type UserStatus string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ForgotPasswordJSONBody defines parameters for ForgotPassword.
type ForgotPasswordJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// DeleteMeJSONBody defines parameters for DeleteMe.
type DeleteMeJSONBody struct {
	Password string  `json:"password"`
	Reason   *string `json:"reason,omitempty"`
}

// ResendConfirmationJSONBody defines parameters for ResendConfirmation.
type ResendConfirmationJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// ConfirmEmailJSONRequestBody defines body for ConfirmEmail for application/json ContentType.
type ConfirmEmailJSONRequestBody = TokenRequest

// ExternalCallbackJSONRequestBody defines body for ExternalCallback for application/json ContentType.
type ExternalCallbackJSONRequestBody = ExternalCallbackRequest

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody ForgotPasswordJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// DeleteMeJSONRequestBody defines body for DeleteMe for application/json ContentType.
type DeleteMeJSONRequestBody DeleteMeJSONBody

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ResendConfirmationJSONRequestBody defines body for ResendConfirmation for application/json ContentType.
type ResendConfirmationJSONRequestBody ResendConfirmationJSONBody

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ConfirmEmail Подтверждение email по токену из письма
	// (POST /auth/confirm-email)
	ConfirmEmail(c *gin.Context)
	// ExternalCallback Callback внешнего identity-провайдера (задел под Keycloak/OIDC)
	// (POST /auth/external/{provider}/callback)
	ExternalCallback(c *gin.Context, provider string)
	// ForgotPassword Запрос на сброс пароля
	// (POST /auth/forgot-password)
	ForgotPassword(c *gin.Context)
	// Login Логин по email/паролю
	// (POST /auth/login)
	Login(c *gin.Context)
	// Logout Отзыв refresh-токена
	// (POST /auth/logout)
	Logout(c *gin.Context)
	// DeleteMe Удаление аккаунта (soft delete + анонимизация по 152-ФЗ)
	// (DELETE /auth/me)
	DeleteMe(c *gin.Context)
	// Me Текущий пользователь
	// (GET /auth/me)
	Me(c *gin.Context)
	// Refresh Обновление access-токена
	// (POST /auth/refresh)
	Refresh(c *gin.Context)
	// Register Регистрация пользователя
	// (POST /auth/register)
	Register(c *gin.Context)
	// ResendConfirmation Повторная отправка письма с подтверждением
	// (POST /auth/resend-confirmation)
	ResendConfirmation(c *gin.Context)
	// ResetPassword Установка нового пароля по токену
	// (POST /auth/reset-password)
	ResetPassword(c *gin.Context)
	// Healthz Liveness probe
	// (GET /healthz)
	Healthz(c *gin.Context)
	// InternalGetUser Внутренний эндпоинт — получить пользователя по ID (для других сервисов)
	// (GET /internal/users/{userId})
	InternalGetUser(c *gin.Context, userId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ConfirmEmail operation middleware
func (siw *ServerInterfaceWrapper) ConfirmEmail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ConfirmEmail(c)
}

// ExternalCallback operation middleware
func (siw *ServerInterfaceWrapper) ExternalCallback(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", c.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter provider: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExternalCallback(c, provider)
}

// ForgotPassword operation middleware
func (siw *ServerInterfaceWrapper) ForgotPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ForgotPassword(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// DeleteMe operation middleware
func (siw *ServerInterfaceWrapper) DeleteMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteMe(c)
}

// Me operation middleware
func (siw *ServerInterfaceWrapper) Me(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Me(c)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Refresh(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// ResendConfirmation operation middleware
func (siw *ServerInterfaceWrapper) ResendConfirmation(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResendConfirmation(c)
}

// ResetPassword operation middleware
func (siw *ServerInterfaceWrapper) ResetPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResetPassword(c)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// InternalGetUser operation middleware
func (siw *ServerInterfaceWrapper) InternalGetUser(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.InternalGetUser(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.POST(options.BaseURL+"/auth/confirm-email", wrapper.ConfirmEmail)
	router.POST(options.BaseURL+"/auth/resend-confirmation", wrapper.ResendConfirmation)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.Refresh)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.POST(options.BaseURL+"/auth/forgot-password", wrapper.ForgotPassword)
	router.POST(options.BaseURL+"/auth/reset-password", wrapper.ResetPassword)
	router.DELETE(options.BaseURL+"/auth/me", wrapper.DeleteMe)
	router.GET(options.BaseURL+"/auth/me", wrapper.Me)
	router.POST(options.BaseURL+"/auth/external/:provider/callback", wrapper.ExternalCallback)
	router.GET(options.BaseURL+"/internal/users/:userId", wrapper.InternalGetUser)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FndbhvHFX6VxbQXNroSJcUFXN45stSqVhJBstsLQyhWu0NxouUOMztUrAgEJCppY9it2yJAgBaJ27oP",
	"wLBiREsm/QpnXqFPUpyZWXJJ7ZK0/lD4ij87c+bM+c7Pd87uE59XqjyikYxJcZ8IGld5FFP940MvWKef",
	"1Wgs8ZfPI0kj/dWrVkPme5LxqPBpzCP8L/bLtOLht58KWiJF8pPCQHTBPI0LS0JwQer1uksCGvuCVVEI",
	"KRL4DtrQgrY6gK56Bq8dOIEmvFUH0FOHpO6SRR6VQubfhCp/gx501ZdwBh04VQ3nFnStLh14gyq6Dq14",
	"LHTUEfwIbaNqV71Qjduo6TIXWywIaHQDqn6D5lENdQRvBxZrq6fqL9BFXT7mcpnXouBmAHS0oV7DMbSh",
	"Cz1U4FHk1WSZC/YFvTElmtBSDehpvE6gBy2Eh+BqKwDlGxnFfVIVvEqFZMbnfR5Q/KRPvEo1pKRIlj66",
	"t7L6u4f3Hix9TFwi96r4ZywFi7bxghUax972yB7jHl4oqBfsOYJus1hSQYPzAuouEfSzGsOHxcfm+IHQ",
	"zf56vvUp9SUeuPREUhF54aIXhluev5MK0eyrnFNZ0IAJ6stHguHzEhcVT5IiqQk2nYJZaq3ybRbl6qIN",
	"MnSY+SfDoFUvjj/nIshQfUSXRER/R5Ze67QkaFzO1UyY5w/5jgnY8UcOrc4+zmB91ZaoeE9WabQty6Q4",
	"v3DXJRUWJb/vZmwVPKSTouhRTMU6rptoVysv+74xlWt2Ye6lI/r52sUvI6fDxixzhw7LUlmDt+axjOj3",
	"fJ/G8dKTKhM0vieHYAo8SWckq9AsqMzGPCdyE7+5gOQJ/umSWkzFNFCfs1da55Fz3HOWyLiCPTrXxLne",
	"8E54Zol/ZK88ku8E9SQN3sW47xCM+sFvqGAlNsUZj5OdLolqYUg26y5hwXC2rbGAXDp0XRJLT9biaXZs",
	"mJWjdtZqJPfWp/eFuimj5gGxbvWlUa2iK4QXBQwtoqVWQ75HBTpUUGFpNAcXTqmWEuP5ku2ijK2Q+zu6",
	"dAY0pJIGGULQDNSvCSb3NvDCxiG2qCeouFeT5cGv5cT8v/7tQ2IJAUoyTwd4lKWsGobBohLH/SNM4x/Q",
	"hv9AR7OvA2iq30NHvXAdeAs9OFYNy2V/tFyoA23DGV0HzqCHO6HrOjamXEcdwg+G66KEJn6FMy2vBV1o",
	"q6+tDBbQSDK5N4uaMomWJ8sba85a6En0LOe/B984eGNng4pd5qMBd6mIjdLzs3Ozc2hyXqWRV2WkSD6Y",
	"nZ+d07lelrXRCsjXCj6PSkxUZvoBUuUmkjHgNGVbCUhRk3ImKkuJ85iI/5AHe1fG9YZSSX3Yd6Wo0bo7",
	"3LQszN05j5ZWMAObhCbfmZvL06MvvJBqh7TD1SoVT+yRIoGX4zHXBztISeEUn6gjB5kp/o3+8xzeQBPx",
	"9LZj7fnosJt4hMGCWsJX2K8KvssCKuoF35K/fGhGaaLGWHgVKqnAY/YJQ8sg7sQlkaejIDmAjFrZTaE1",
	"oLk7dM8PubeTwRo3r8cb8sjvVI4xd7VOqSlEVhPySh3CWxO0ppVtqa/QQ4ynzU/2tKGmadjXkounEwMm",
	"ol4/NcyYrhlaSSuG6cm5pbtDdMwzGwfOA4te4ZOV+4u3xzhgiYttLmfSdDTb55b1wrUUbbygC1yQMmfy",
	"2PN1axpfWchI+S91R6kbfeg5t2xst9ShRuAYmghKD06gpSvCU2hCWzWchbkFB44xnesWXT2FjmqoZw70",
	"VMPBcmdNeHs0rXw7mIDozjqvSoyBLsSuLB8w3bRdU+Ieagjf5/jETR9M3jQYC43A/PeED5g6od2qkML3",
	"T+Px5TU5FmB8fj0Ij7TWFy3O8E9oq0N1CB0bIaaOqq91FW1eImtaSqirXZoMPt6sbw5B8L1qwIl6Bq2E",
	"kc0MqvXY2lyh5j5ITM9b/77+/yN6ZZlwzGwEj/Ds9rweZCQ/jpmbZERNPskZ+Cq04Y2moINEB02T6BY3",
	"1pcd6GAOO1NH6g+6OnW16/dwkHoMTb2/i25ALuZIf4ZTOIWmOoKuavSFIslzbZ7OwNdmYpO49SD32WUT",
	"wU2Pyge54vk7Ov6rtN3N7DRlQuQNMS9Jxzi48zN8jph19SS8AydJ42NS1/zPF2bg3/BtBplwyTbNyE82",
	"Nq6pDNixR4Yv6yr6JXTQZFp3/JIMi1UDaZJ6cROZ51/QhlN1hLECr/M0eT4mA1mHzi8BNkv/H9WAm6rz",
	"31kjvkgipJlqwvDZVRBy+B5+MNJSYWSmZ9MWkeT9wDgM7YrrAnF4aD0VivM3EKbZ0YA1BLM1pq6um26j",
	"e46hxjmVCt6YVI+kutkHrHehCQBu+cXkLf3XliNekzk+ys9E45wnplEwYwc2njFdvh/h4sX02ve6STMw",
	"3ZkMU/89acZkJ3mZ2DWpJO1Ap9BMu19zkvtNwHGaHnvohcu15YOMlzoXpvcvB+zEgd4gW17R8O0VxpDl",
	"JRYR89VQy3SjfH4Qlw1ImXqhLH+BWmWyll/Z55esbMMBNJjjDwZsfGdi/Nht01D4Tx6M2G6V7dKIxrFT",
	"FXyLpmxhDGCtwSI7f8TXPXFhHz9WgnqudVbs+l9SqTP7NINHI3Ps2HHCi5P65iXRuMoKdem881d0Tl0a",
	"MHd0NTlUf4QuHOv00tENjm60TMXAhgqnSvlk1vj+yn3nVjKLOlYH6kgXoa+womKyamEqw31Z40DUkIrd",
	"BMVhS6xy3wudgO4Sl9REaN+gFAuFEB+UeSyLd+fuzpP6Zl/wfgK+PqDu9n9b76tv1v83AA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
