// This file is auto-generated by @hey-api/openapi-ts

export const CompanySchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        description: {
            type: ['string', 'null']
        },
        industry: {
            type: ['string', 'null']
        },
        website: {
            type: ['string', 'null'],
            format: 'uri'
        },
        size: {
            type: ['string', 'null']
        }
    },
    required: ['id', 'name']
} as const;

export const CompanyInputSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        industry: {
            type: 'string'
        },
        website: {
            type: 'string',
            format: 'uri'
        },
        size: {
            type: 'string'
        }
    },
    required: ['name']
} as const;

export const NeedSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        title: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        categoryId: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        specializationId: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        gradeId: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        stack: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        salaryMin: {
            type: 'integer'
        },
        salaryMax: {
            type: 'integer'
        },
        currency: {
            type: 'string',
            default: 'RUB'
        },
        workFormat: {
            type: ['string', 'null'],
            enum: ['remote', 'hybrid', 'office', null]
        },
        status: {
            type: 'string',
            enum: ['draft', 'active', 'closed']
        }
    },
    required: ['id', 'title', 'description', 'salaryMin', 'salaryMax', 'currency', 'status']
} as const;

export const NeedInputSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        categoryId: {
            type: 'string',
            format: 'uuid'
        },
        specializationId: {
            type: 'string',
            format: 'uuid'
        },
        gradeId: {
            type: 'string',
            format: 'uuid'
        },
        stack: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        salaryMin: {
            type: 'integer',
            minimum: 0
        },
        salaryMax: {
            type: 'integer',
            minimum: 0
        },
        workFormat: {
            type: 'string',
            enum: ['remote', 'hybrid', 'office']
        },
        status: {
            type: 'string',
            enum: ['draft', 'active', 'closed']
        }
    },
    required: ['title', 'description', 'salaryMin', 'salaryMax']
} as const;

export const VacancyInputSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        categoryId: {
            type: 'string',
            format: 'uuid'
        },
        stack: {
            type: 'array',
            items: {
                type: 'string',
                format: 'uuid'
            }
        },
        salaryMin: {
            type: 'integer',
            minimum: 0
        },
        salaryMax: {
            type: 'integer',
            minimum: 0
        },
        workFormat: {
            type: 'string',
            enum: ['remote', 'hybrid', 'office']
        }
    },
    required: ['title', 'description', 'salaryMin', 'salaryMax']
} as const;

export const VacancySchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/VacancyInput'
        },
        {
            type: 'object',
            properties: {
                id: {
                    type: 'string',
                    format: 'uuid'
                },
                companyId: {
                    type: 'string',
                    format: 'uuid'
                },
                status: {
                    type: 'string',
                    enum: ['draft', 'published', 'archived']
                },
                publishedAt: {
                    type: ['string', 'null'],
                    format: 'date-time'
                },
                createdAt: {
                    type: 'string',
                    format: 'date-time'
                }
            }
        }
    ]
} as const;

export const MatchCardSchema = {
    type: 'object',
    properties: {
        candidateUserId: {
            type: 'string',
            format: 'uuid'
        },
        displayName: {
            type: 'string'
        },
        categoryId: {
            type: 'string',
            format: 'uuid'
        },
        gradeId: {
            type: 'string',
            format: 'uuid'
        },
        score: {
            type: 'number',
            format: 'float'
        },
        reasons: {
            type: 'array',
            items: {
                type: 'string',
                example: 'grade_match'
            }
        },
        hasFSP: {
            type: 'boolean'
        }
    }
} as const;