// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { HealthzError, HealthzResponse, GetMyCompanyError, GetMyCompanyResponse, UpsertMyCompanyData, UpsertMyCompanyError, UpsertMyCompanyResponse, ListMyNeedsError, ListMyNeedsResponse, CreateNeedData, CreateNeedError, CreateNeedResponse, UpdateNeedData, UpdateNeedError, UpdateNeedResponse, DeleteNeedData, DeleteNeedError, DeleteNeedResponse, GetNeedMatchesData, GetNeedMatchesError, GetNeedMatchesResponse, ListMyVacanciesError, ListMyVacanciesResponse, CreateVacancyData, CreateVacancyError, CreateVacancyResponse, UpdateVacancyData, UpdateVacancyError, UpdateVacancyResponse, DeleteVacancyData, DeleteVacancyError, DeleteVacancyResponse, PublishVacancyData, PublishVacancyError, PublishVacancyResponse, ListPublicVacanciesData, ListPublicVacanciesError, ListPublicVacanciesResponse, GetPublicVacancyData, GetPublicVacancyError, GetPublicVacancyResponse } from './types.gen';

export const client = createClient(createConfig());

export const healthz = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthzResponse, HealthzError, ThrowOnError>({
        ...options,
        url: '/healthz'
    });
};

export const getMyCompany = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMyCompanyResponse, GetMyCompanyError, ThrowOnError>({
        ...options,
        url: '/me/company'
    });
};

export const upsertMyCompany = <ThrowOnError extends boolean = false>(options: Options<UpsertMyCompanyData, ThrowOnError>) => {
    return (options?.client ?? client).put<UpsertMyCompanyResponse, UpsertMyCompanyError, ThrowOnError>({
        ...options,
        url: '/me/company'
    });
};

export const listMyNeeds = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ListMyNeedsResponse, ListMyNeedsError, ThrowOnError>({
        ...options,
        url: '/me/needs'
    });
};

export const createNeed = <ThrowOnError extends boolean = false>(options: Options<CreateNeedData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateNeedResponse, CreateNeedError, ThrowOnError>({
        ...options,
        url: '/me/needs'
    });
};

export const updateNeed = <ThrowOnError extends boolean = false>(options: Options<UpdateNeedData, ThrowOnError>) => {
    return (options?.client ?? client).patch<UpdateNeedResponse, UpdateNeedError, ThrowOnError>({
        ...options,
        url: '/me/needs/{id}'
    });
};

export const deleteNeed = <ThrowOnError extends boolean = false>(options: Options<DeleteNeedData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteNeedResponse, DeleteNeedError, ThrowOnError>({
        ...options,
        url: '/me/needs/{id}'
    });
};

/**
 * Подборка кандидатов под потребность, с объяснением
 */
export const getNeedMatches = <ThrowOnError extends boolean = false>(options: Options<GetNeedMatchesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetNeedMatchesResponse, GetNeedMatchesError, ThrowOnError>({
        ...options,
        url: '/me/needs/{id}/matches'
    });
};

export const listMyVacancies = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ListMyVacanciesResponse, ListMyVacanciesError, ThrowOnError>({
        ...options,
        url: '/me/vacancies'
    });
};

export const createVacancy = <ThrowOnError extends boolean = false>(options: Options<CreateVacancyData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateVacancyResponse, CreateVacancyError, ThrowOnError>({
        ...options,
        url: '/me/vacancies'
    });
};

export const updateVacancy = <ThrowOnError extends boolean = false>(options: Options<UpdateVacancyData, ThrowOnError>) => {
    return (options?.client ?? client).patch<UpdateVacancyResponse, UpdateVacancyError, ThrowOnError>({
        ...options,
        url: '/me/vacancies/{id}'
    });
};

export const deleteVacancy = <ThrowOnError extends boolean = false>(options: Options<DeleteVacancyData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteVacancyResponse, DeleteVacancyError, ThrowOnError>({
        ...options,
        url: '/me/vacancies/{id}'
    });
};

export const publishVacancy = <ThrowOnError extends boolean = false>(options: Options<PublishVacancyData, ThrowOnError>) => {
    return (options?.client ?? client).post<PublishVacancyResponse, PublishVacancyError, ThrowOnError>({
        ...options,
        url: '/me/vacancies/{id}/publish'
    });
};

export const listPublicVacancies = <ThrowOnError extends boolean = false>(options?: Options<ListPublicVacanciesData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListPublicVacanciesResponse, ListPublicVacanciesError, ThrowOnError>({
        ...options,
        url: '/vacancies'
    });
};

export const getPublicVacancy = <ThrowOnError extends boolean = false>(options: Options<GetPublicVacancyData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPublicVacancyResponse, GetPublicVacancyError, ThrowOnError>({
        ...options,
        url: '/vacancies/{id}'
    });
};