// This file is auto-generated by @hey-api/openapi-ts

export type Company = {
    id: string;
    name: string;
    description?: (string) | null;
    industry?: (string) | null;
    website?: (string) | null;
    size?: (string) | null;
};

export type CompanyInput = {
    name: string;
    description?: string;
    industry?: string;
    website?: string;
    size?: string;
};

export type MatchCard = {
    candidateUserId?: string;
    displayName?: string;
    categoryId?: string;
    gradeId?: string;
    score?: number;
    reasons?: Array<(string)>;
    hasFSP?: boolean;
};

export type Need = {
    id: string;
    title: string;
    description: string;
    categoryId?: (string) | null;
    specializationId?: (string) | null;
    gradeId?: (string) | null;
    stack?: Array<(string)>;
    salaryMin: number;
    salaryMax: number;
    currency: string;
    workFormat?: ('remote' | 'hybrid' | 'office') | null;
    status: 'draft' | 'active' | 'closed';
};

export type workFormat = 'remote' | 'hybrid' | 'office';

export type status = 'draft' | 'active' | 'closed';

export type NeedInput = {
    title: string;
    description: string;
    categoryId?: string;
    specializationId?: string;
    gradeId?: string;
    stack?: Array<(string)>;
    salaryMin: number;
    salaryMax: number;
    workFormat?: 'remote' | 'hybrid' | 'office';
    status?: 'draft' | 'active' | 'closed';
};

export type Vacancy = VacancyInput & {
    id?: string;
    companyId?: string;
    status?: 'draft' | 'published' | 'archived';
    publishedAt?: (string) | null;
    createdAt?: string;
};

export type status2 = 'draft' | 'published' | 'archived';

export type VacancyInput = {
    title: string;
    description: string;
    categoryId?: string;
    stack?: Array<(string)>;
    salaryMin: number;
    salaryMax: number;
    workFormat?: 'remote' | 'hybrid' | 'office';
};

export type HealthzResponse = (unknown);

export type HealthzError = unknown;

export type GetMyCompanyResponse = (Company);

export type GetMyCompanyError = unknown;

export type UpsertMyCompanyData = {
    body: CompanyInput;
};

export type UpsertMyCompanyResponse = (Company);

export type UpsertMyCompanyError = unknown;

export type ListMyNeedsResponse = (Array<Need>);

export type ListMyNeedsError = unknown;

export type CreateNeedData = {
    body: NeedInput;
};

export type CreateNeedResponse = (Need);

export type CreateNeedError = unknown;

export type UpdateNeedData = {
    body: NeedInput;
    path: {
        id: string;
    };
};

export type UpdateNeedResponse = (Need);

export type UpdateNeedError = unknown;

export type DeleteNeedData = {
    path: {
        id: string;
    };
};

export type DeleteNeedResponse = (void);

export type DeleteNeedError = unknown;

export type GetNeedMatchesData = {
    path: {
        id: string;
    };
    query?: {
        limit?: number;
        offset?: number;
    };
};

export type GetNeedMatchesResponse = ({
    items: Array<MatchCard>;
    total: number;
});

export type GetNeedMatchesError = unknown;

export type ListMyVacanciesResponse = (Array<Vacancy>);

export type ListMyVacanciesError = unknown;

export type CreateVacancyData = {
    body: VacancyInput;
};

export type CreateVacancyResponse = (Vacancy);

export type CreateVacancyError = unknown;

export type UpdateVacancyData = {
    body: VacancyInput;
    path: {
        id: string;
    };
};

export type UpdateVacancyResponse = (Vacancy);

export type UpdateVacancyError = unknown;

export type DeleteVacancyData = {
    path: {
        id: string;
    };
};

export type DeleteVacancyResponse = (void);

export type DeleteVacancyError = unknown;

export type PublishVacancyData = {
    path: {
        id: string;
    };
};

export type PublishVacancyResponse = (Vacancy);

export type PublishVacancyError = unknown;

export type ListPublicVacanciesData = {
    query?: {
        categoryId?: string;
        gradeId?: string;
        limit?: number;
        offset?: number;
    };
};

export type ListPublicVacanciesResponse = (Array<Vacancy>);

export type ListPublicVacanciesError = unknown;

export type GetPublicVacancyData = {
    path: {
        id: string;
    };
};

export type GetPublicVacancyResponse = (Vacancy);

export type GetPublicVacancyError = unknown;