-- +goose Up
INSERT INTO technologies (code, name, category) VALUES
  ('csharp', 'C#', 'language'),
  ('cpp', 'C++', 'language'),
  ('rust', 'Rust', 'language'),
  ('php', 'PHP', 'language'),
  ('ruby', 'Ruby', 'language'),
  ('swift', 'Swift', 'language'),
  ('dart', 'Dart', 'language'),
  ('scala', 'Scala', 'language'),
  ('sql', 'SQL', 'language'),
  ('angular', 'Angular', 'frontend'),
  ('nextjs', 'Next.js', 'frontend'),
  ('svelte', 'Svelte', 'frontend'),
  ('htmlcss', 'HTML/CSS', 'frontend'),
  ('flutter', 'Flutter', 'mobile'),
  ('reactnative', 'React Native', 'mobile'),
  ('swiftui', 'SwiftUI', 'mobile'),
  ('android', 'Android', 'mobile'),
  ('spring', 'Spring', 'backend'),
  ('django', 'Django', 'backend'),
  ('fastapi', 'FastAPI', 'backend'),
  ('nodejs', 'Node.js', 'backend'),
  ('dotnet', '.NET', 'backend'),
  ('laravel', 'Laravel', 'backend'),
  ('rails', 'Ruby on Rails', 'backend'),
  ('clickhouse', 'ClickHouse', 'db'),
  ('elastic', 'Elasticsearch', 'db'),
  ('cassandra', 'Cassandra', 'db'),
  ('kafka', 'Kafka', 'data'),
  ('rabbitmq', 'RabbitMQ', 'data'),
  ('spark', 'Spark', 'data'),
  ('airflow', 'Airflow', 'data'),
  ('pandas', 'Pandas', 'data'),
  ('terraform', 'Terraform', 'infra'),
  ('ansible', 'Ansible', 'infra'),
  ('aws', 'AWS', 'infra'),
  ('gcp', 'Google Cloud', 'infra'),
  ('yandexcloud', 'Yandex Cloud', 'infra'),
  ('linux', 'Linux', 'infra'),
  ('git', 'Git', 'infra'),
  ('gitlab', 'GitLab', 'infra'),
  ('selenium', 'Selenium', 'qa'),
  ('playwright', 'Playwright', 'qa'),
  ('cypress', 'Cypress', 'qa'),
  ('junit', 'JUnit', 'qa'),
  ('pytest', 'pytest', 'qa'),
  ('graphql', 'GraphQL', 'backend'),
  ('grpc', 'gRPC', 'backend'),
  ('figma', 'Figma', 'frontend'),
  ('bitrix', '1С-Битрикс', 'backend'),
  ('onec', '1С', 'backend')
ON CONFLICT (code) DO NOTHING;
