// Package apicandidate provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apicandidate

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CategoryStateHistoryReason.
const (
	CategoryStateHistoryReasonInitialTest CategoryStateHistoryReason = "initial_test"
	CategoryStateHistoryReasonManual      CategoryStateHistoryReason = "manual"
	CategoryStateHistoryReasonRetake      CategoryStateHistoryReason = "retake"
)

// Valid indicates whether the value is a known member of the CategoryStateHistoryReason enum.
func (e CategoryStateHistoryReason) Valid() bool {
	switch e {
	case CategoryStateHistoryReasonInitialTest:
		return true
	case CategoryStateHistoryReasonManual:
		return true
	case CategoryStateHistoryReasonRetake:
		return true
	default:
		return false
	}
}

// Defines values for ResumeSource.
const (
	ResumeSourceGenerated ResumeSource = "generated"
	ResumeSourceManual    ResumeSource = "manual"
	ResumeSourcePdfUpload ResumeSource = "pdf_upload"
)

// Valid indicates whether the value is a known member of the ResumeSource enum.
func (e ResumeSource) Valid() bool {
	switch e {
	case ResumeSourceGenerated:
		return true
	case ResumeSourceManual:
		return true
	case ResumeSourcePdfUpload:
		return true
	default:
		return false
	}
}

// CandidateCard defines model for CandidateCard.
type CandidateCard struct {
	CategoryId *openapi_types.UUID `json:"categoryId,omitempty"`

	// Contacts null, если контакты не раскрыты
	Contacts    *CandidateContacts `json:"contacts,omitempty"`
	DisplayName *string            `json:"displayName,omitempty"`
	Fsp         *struct {
		AchievementsCount *int  `json:"achievementsCount,omitempty"`
		BestPlace         *int  `json:"bestPlace,omitempty"`
		HasFSP            *bool `json:"hasFSP,omitempty"`
	} `json:"fsp,omitempty"`
	GradeId          *openapi_types.UUID    `json:"gradeId,omitempty"`
	Headline         *string                `json:"headline,omitempty"`
	SpecializationId *openapi_types.UUID    `json:"specializationId,omitempty"`
	Technologies     *[]CandidateTechnology `json:"technologies,omitempty"`
	UserId           *openapi_types.UUID    `json:"userId,omitempty"`
	YearsExperience  *float32               `json:"yearsExperience,omitempty"`
}

// CandidateContacts defines model for CandidateContacts.
type CandidateContacts struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Github   *string              `json:"github,omitempty"`
	Linkedin *string              `json:"linkedin,omitempty"`
	Phone    *string              `json:"phone,omitempty"`
	Telegram *string              `json:"telegram,omitempty"`
	Website  *string              `json:"website,omitempty"`
}

// CandidateProfile defines model for CandidateProfile.
type CandidateProfile struct {
	About            *string             `json:"about,omitempty"`
	CategoryId       *openapi_types.UUID `json:"categoryId,omitempty"`
	FirstName        *string             `json:"firstName,omitempty"`
	FspMemberId      *string             `json:"fspMemberId,omitempty"`
	GradeId          *openapi_types.UUID `json:"gradeId,omitempty"`
	Headline         *string             `json:"headline,omitempty"`
	LastName         *string             `json:"lastName,omitempty"`
	Location         *string             `json:"location,omitempty"`
	SpecializationId *openapi_types.UUID `json:"specializationId,omitempty"`
	UpdatedAt        time.Time           `json:"updatedAt"`
	UserId           openapi_types.UUID  `json:"userId"`
	YearsExperience  *float32            `json:"yearsExperience,omitempty"`
}

// CandidateTechnology defines model for CandidateTechnology.
type CandidateTechnology struct {
	Level        *int               `json:"level,omitempty"`
	TechnologyId openapi_types.UUID `json:"technologyId"`
}

// CategoryState defines model for CategoryState.
type CategoryState struct {
	CategoryId *openapi_types.UUID `json:"categoryId,omitempty"`
	GradeId    *openapi_types.UUID `json:"gradeId,omitempty"`
	History    *[]struct {
		CategoryId    *openapi_types.UUID         `json:"categoryId,omitempty"`
		EffectiveFrom *time.Time                  `json:"effectiveFrom,omitempty"`
		EffectiveTo   *time.Time                  `json:"effectiveTo,omitempty"`
		GradeId       *openapi_types.UUID         `json:"gradeId,omitempty"`
		Reason        *CategoryStateHistoryReason `json:"reason,omitempty"`
	} `json:"history,omitempty"`
	SpecializationId *openapi_types.UUID `json:"specializationId,omitempty"`
}

// CategoryStateHistoryReason defines model for CategoryState.History.Reason.
type CategoryStateHistoryReason string

// Experience defines model for Experience.
type Experience struct {
	Company     string              `json:"company"`
	Description *string             `json:"description,omitempty"`
	EndedAt     *openapi_types.Date `json:"endedAt,omitempty"`
	Id          openapi_types.UUID  `json:"id"`
	Position    string              `json:"position"`
	StartedAt   openapi_types.Date  `json:"startedAt"`
}

// ExperienceInput defines model for ExperienceInput.
type ExperienceInput struct {
	Company     string              `json:"company"`
	Description *string             `json:"description,omitempty"`
	EndedAt     *openapi_types.Date `json:"endedAt,omitempty"`
	Position    string              `json:"position"`
	StartedAt   openapi_types.Date  `json:"startedAt"`
}

// FSPAchievement defines model for FSPAchievement.
type FSPAchievement struct {
	Category   *string             `json:"category,omitempty"`
	EventDate  *openapi_types.Date `json:"eventDate,omitempty"`
	EventName  *string             `json:"eventName,omitempty"`
	ExternalId *string             `json:"externalId,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Place      *int                `json:"place,omitempty"`
	Score      *float32            `json:"score,omitempty"`
	Weight     *int                `json:"weight,omitempty"`
}

// FSPState defines model for FSPState.
type FSPState struct {
	Achievements *[]FSPAchievement `json:"achievements,omitempty"`
	FspMemberId  *string           `json:"fspMemberId,omitempty"`
	LinkedAt     *time.Time        `json:"linkedAt,omitempty"`
}

// Resume defines model for Resume.
type Resume struct {
	CreatedAt *time.Time              `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID     `json:"id,omitempty"`
	IsPrimary *bool                   `json:"isPrimary,omitempty"`
	Parsed    *map[string]interface{} `json:"parsed,omitempty"`
	Source    *ResumeSource           `json:"source,omitempty"`
	Title     *string                 `json:"title,omitempty"`
}

// ResumeSource defines model for Resume.Source.
type ResumeSource string

// ResumeInput defines model for ResumeInput.
type ResumeInput struct {
	Content   string `json:"content"`
	IsPrimary *bool  `json:"isPrimary,omitempty"`
	Title     string `json:"title"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	About           *string  `json:"about,omitempty"`
	FirstName       *string  `json:"firstName,omitempty"`
	Headline        *string  `json:"headline,omitempty"`
	LastName        *string  `json:"lastName,omitempty"`
	Location        *string  `json:"location,omitempty"`
	YearsExperience *float32 `json:"yearsExperience,omitempty"`
}

// Visibility defines model for Visibility.
type Visibility struct {
	Contacts   *bool `json:"contacts,omitempty"`
	Experience *bool `json:"experience,omitempty"`
	Fsp        *bool `json:"fsp,omitempty"`
	Resume     *bool `json:"resume,omitempty"`
}

// GetCandidateForEmployerParams defines parameters for GetCandidateForEmployer.
type GetCandidateForEmployerParams struct {
	// RevealContacts Показывать ли контакты (только при accepted-приглашении/отклике)
	RevealContacts *bool `form:"revealContacts,omitempty" json:"revealContacts,omitempty"`
}

// LinkFSPJSONBody defines parameters for LinkFSP.
type LinkFSPJSONBody struct {
	FspMemberId string `json:"fspMemberId"`
}

// UploadResumePDFMultipartBody defines parameters for UploadResumePDF.
type UploadResumePDFMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// ReplaceTechnologiesJSONBody defines parameters for ReplaceTechnologies.
type ReplaceTechnologiesJSONBody = []CandidateTechnology

// ReplaceMyContactsJSONRequestBody defines body for ReplaceMyContacts for application/json ContentType.
type ReplaceMyContactsJSONRequestBody = CandidateContacts

// AddExperienceJSONRequestBody defines body for AddExperience for application/json ContentType.
type AddExperienceJSONRequestBody = ExperienceInput

// LinkFSPJSONRequestBody defines body for LinkFSP for application/json ContentType.
type LinkFSPJSONRequestBody LinkFSPJSONBody

// UpdateMyProfileJSONRequestBody defines body for UpdateMyProfile for application/json ContentType.
type UpdateMyProfileJSONRequestBody = UpdateProfileRequest

// CreateResumeJSONRequestBody defines body for CreateResume for application/json ContentType.
type CreateResumeJSONRequestBody = ResumeInput

// UploadResumePDFMultipartRequestBody defines body for UploadResumePDF for multipart/form-data ContentType.
type UploadResumePDFMultipartRequestBody UploadResumePDFMultipartBody

// ReplaceTechnologiesJSONRequestBody defines body for ReplaceTechnologies for application/json ContentType.
type ReplaceTechnologiesJSONRequestBody = ReplaceTechnologiesJSONBody

// UpdateMyVisibilityJSONRequestBody defines body for UpdateMyVisibility for application/json ContentType.
type UpdateMyVisibilityJSONRequestBody = Visibility

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /candidates/{userId})
	GetCandidateForEmployer(c *gin.Context, userId openapi_types.UUID, params GetCandidateForEmployerParams)

	// (GET /healthz)
	Healthz(c *gin.Context)

	// (GET /me/category)
	GetMyCategory(c *gin.Context)

	// (GET /me/contacts)
	GetMyContacts(c *gin.Context)

	// (PUT /me/contacts)
	ReplaceMyContacts(c *gin.Context)

	// (GET /me/experiences)
	ListExperiences(c *gin.Context)

	// (POST /me/experiences)
	AddExperience(c *gin.Context)

	// (GET /me/fsp)
	GetMyFSP(c *gin.Context)

	// (PUT /me/fsp)
	LinkFSP(c *gin.Context)

	// (GET /me/profile)
	GetMyProfile(c *gin.Context)

	// (PATCH /me/profile)
	UpdateMyProfile(c *gin.Context)

	// (GET /me/resumes)
	ListResumes(c *gin.Context)

	// (POST /me/resumes)
	CreateResume(c *gin.Context)

	// (POST /me/resumes/upload)
	UploadResumePDF(c *gin.Context)

	// (PUT /me/technologies)
	ReplaceTechnologies(c *gin.Context)

	// (GET /me/visibility)
	GetMyVisibility(c *gin.Context)

	// (PUT /me/visibility)
	UpdateMyVisibility(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetCandidateForEmployer operation middleware
func (siw *ServerInterfaceWrapper) GetCandidateForEmployer(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCandidateForEmployerParams

	// ------------- Optional query parameter "revealContacts" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "revealContacts", c.Request.URL.Query(), &params.RevealContacts, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter revealContacts: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCandidateForEmployer(c, userId, params)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// GetMyCategory operation middleware
func (siw *ServerInterfaceWrapper) GetMyCategory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyCategory(c)
}

// GetMyContacts operation middleware
func (siw *ServerInterfaceWrapper) GetMyContacts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyContacts(c)
}

// ReplaceMyContacts operation middleware
func (siw *ServerInterfaceWrapper) ReplaceMyContacts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReplaceMyContacts(c)
}

// ListExperiences operation middleware
func (siw *ServerInterfaceWrapper) ListExperiences(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListExperiences(c)
}

// AddExperience operation middleware
func (siw *ServerInterfaceWrapper) AddExperience(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddExperience(c)
}

// GetMyFSP operation middleware
func (siw *ServerInterfaceWrapper) GetMyFSP(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyFSP(c)
}

// LinkFSP operation middleware
func (siw *ServerInterfaceWrapper) LinkFSP(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LinkFSP(c)
}

// GetMyProfile operation middleware
func (siw *ServerInterfaceWrapper) GetMyProfile(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyProfile(c)
}

// UpdateMyProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdateMyProfile(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMyProfile(c)
}

// ListResumes operation middleware
func (siw *ServerInterfaceWrapper) ListResumes(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListResumes(c)
}

// CreateResume operation middleware
func (siw *ServerInterfaceWrapper) CreateResume(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateResume(c)
}

// UploadResumePDF operation middleware
func (siw *ServerInterfaceWrapper) UploadResumePDF(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UploadResumePDF(c)
}

// ReplaceTechnologies operation middleware
func (siw *ServerInterfaceWrapper) ReplaceTechnologies(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReplaceTechnologies(c)
}

// GetMyVisibility operation middleware
func (siw *ServerInterfaceWrapper) GetMyVisibility(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyVisibility(c)
}

// UpdateMyVisibility operation middleware
func (siw *ServerInterfaceWrapper) UpdateMyVisibility(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMyVisibility(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/me/profile", wrapper.GetMyProfile)
	router.PATCH(options.BaseURL+"/me/profile", wrapper.UpdateMyProfile)
	router.GET(options.BaseURL+"/me/contacts", wrapper.GetMyContacts)
	router.PUT(options.BaseURL+"/me/contacts", wrapper.ReplaceMyContacts)
	router.GET(options.BaseURL+"/me/visibility", wrapper.GetMyVisibility)
	router.PUT(options.BaseURL+"/me/visibility", wrapper.UpdateMyVisibility)
	router.GET(options.BaseURL+"/me/resumes", wrapper.ListResumes)
	router.POST(options.BaseURL+"/me/resumes", wrapper.CreateResume)
	router.POST(options.BaseURL+"/me/resumes/upload", wrapper.UploadResumePDF)
	router.GET(options.BaseURL+"/me/experiences", wrapper.ListExperiences)
	router.POST(options.BaseURL+"/me/experiences", wrapper.AddExperience)
	router.PUT(options.BaseURL+"/me/technologies", wrapper.ReplaceTechnologies)
	router.GET(options.BaseURL+"/me/category", wrapper.GetMyCategory)
	router.GET(options.BaseURL+"/me/fsp", wrapper.GetMyFSP)
	router.PUT(options.BaseURL+"/me/fsp", wrapper.LinkFSP)
	router.GET(options.BaseURL+"/candidates/:userId", wrapper.GetCandidateForEmployer)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFrdbhvHFX6VxbQXCbAW5SYFAt65tpW6TRrBdtoLQwiGu4fkxPvn2VnVjEBAogukhY0KLQIUCJC6KfoA",
	"lCzatGzRr3DmFfokxcwuyVlyuNzKknIncX7Oz5zzne8cco94cZjEEUQiJc09knpdCKn+8yaNfOZTATcp",
	"99UHCY8T4IKBXvaogE7Me3f0WjvmIRWkSbKM+cQlopcAaZJUcBZ1SN8lXhwJ6uVCfEg9zhLB4og0SZQF",
	"gevgSB7gGxw7eIoTPJMDHOKpHMinDp7hyJH7OJQHeCr35VP1KXFJHMEXbdJ8sEd+zqFNmuRnjbktjcKQ",
	"xtyKqQJ9d2+qnhJN+jt9l/gsTQLa+x0NgTRn63P122my7ALqdRnsQqgE3oyzSBhHWSSgA1ydbUEqtgPq",
	"GTc/mK27uRJKhy5Nt+5tG3e04jgAGpF+f+bQuPU1eELd2uHUh5rO7wL1AxaVFChWDflpAh6jAfuGqpep",
	"ebUArxvFQdwpfMIEhPqPWo9yf3q6R+Y2Us6p/j9LgddUoweUp7cfJ8AZRGVPR1nYMh1tc+ZylCw9NoSU",
	"BSVd8k8synSY6GatamcHLHoIPouqdyXdeN2rCQigw2lYveuP0EqZgLIvOSPuyjOVbtrmcZsFYEmJVpyJ",
	"alXqAIftXJvxVJQT1LotTT4H9eJ3/OqNaxPIdqheJgW0jqZB7NEcAy8mK22ns0Q9l39DlI6pz64JFoIt",
	"et8v62Zn2kFMBXGr0pDDo4xx8NVyIdXUeKcqAg3kWArCAHZBp2pIH7MwC0nzly4JWZT/fd21YPQMxurV",
	"swXlS6ftaucxf09QAeerpRcXwiwVMe+VwPq9Sju02+AJtgtbPA7rx9ns2P14zaFzmW5I4kDTPM0gysK8",
	"+jLBaPCVgFQQtUHQh0peSKOMBmRn6RIbGi6Wq/fJVNv95cRaeKI4TGjUs3KVEr2qghaIfCs0VDqe1fN5",
	"EqesrIGxmArKRbXoVammpU2tN8SYl+5UOvNOlGTiAjxqrJ/LkZfloXM4Z+ve9o05l10NCGvCaRcicYsK",
	"WK3zymMriTc8FsAjGqyr5nXDsgYPT72YVzJIRadYp2ul+327e1cAv9lB1GbPC69lQaLaHChnoWvZQT28",
	"ugtpFtqwisP/y0FqviZLtzkLKe/ZmiaXJJSnoG+ivq8zgQbbhmqCZzA3sTDEDIQ44x6YdaOoDy5J/PZX",
	"WRLEVOnVgQi4MtFSOFwimAhssb3ahSsRKhIQCctVC57woU2zQJBmmwYpuBbPVOhU4jV6mzuTbMOOLxOj",
	"IbgLjzJIxdq+wOysl2l9ZedqLC7TbHNxiV3XaRenuW59nd+zlLVYwETP/jjTxnHZ32ATZawX44XlBT7L",
	"qfUzARWx4GWcid49BRW5Yi2gHPiNTHTn/21NE+s3f7hP3Hzooy/Xq/NM6wqRkL66mEVtzdKKwFGQ5mwH",
	"VKgUdf67/50zI+bOPeC7zAPikl3gqX4Bcn1jc2NT2RMnENGEkSb5aOP6xqbKJCq6WtGGN70ibezl7UBf",
	"fd4BsTw0wr/jBF/hsZ4L/QWHOJIDNToayn05wIn8Fk/lEwePcISvFkZKOMHjDQe/XxwzvcOJPMRjeSgH",
	"8kAeOnrnG/lMnc5X1YBq5FDPg0SAv0G0OXzG9sinIGZu2Ir57TAJ4p72Z0I5DUEAT/XAiikTlOHEJZEO",
	"4Hn/M8+/HJ5y1K/Vkyw56TlOlE/wlXyKxziUA/nMsQ/ZPliwVu7jeGbptfx/fIFvcCj/jCM8wzGOGziR",
	"AzxVF+Ipjj4kbm7Yowx4b24Zh12gwWywYlq0Dqj6OzoDkjhK82D+xebmAhLSJAlYnumNrwuWPxdQbzJI",
	"uZ9H+YL7vjfDCYc6vvAMT3CMJ8qbOFQh/fHmx5b4/AFHanI5xNd4oh02USL6Lml0gQai+40R2uUo+nWx",
	"bje9LOaL35bSnjQf6NLcCKFhcjarnE9BfN6bNqbkUh1tNr82R/8bRypfVSLLwzyNBzjCFzhRcScPG/hC",
	"7uNI+dJR0TuWB3IwXZz6VdlsgHCFzfNQvILgmgqzB1gpC/M9SWZR/C5o5rqgvC62v4r93mXrXQal/k/u",
	"uH/ikUopPFaIbCZXCI15rV0dB5+xVNw29r2nQbVo+1zeMmW3mvhOfdWhv/nAI5wYARKnFpNu+L4h4XKi",
	"Y7GJrhUb1y9BvNVj3+EEj3BoDYqCYK0GBfXNyyWG9awFtCn+XFfXY3mIr4o64+B/8Ed87ty5pfHuRJEP",
	"OcAxvsyLrzx0PsC3OMGXOfE50t+KPVOF+4naKZ/i2w8r4OQzFj2cWny+MCmzX2vDuaqrMDcvdxS14abC",
	"icOF10/mX1esjoDpdxpXAW5TWauiYSL/hGNFx6ycQz8rFV532ZK8Gysbc/E4YO35fqpCUeVLo07Iv+EZ",
	"nsmn+DqntzMXG3GSd1vVZeNusecqSkYuq1a5+JfqdORf8S2OqqrETT2LKe69nOAwZxhXXCCm/rL450fd",
	"L54sQUPx5I1imNPcmzlu4YJ/4FCxUPmkAOntW1uOPHBUvSm4qPqBwjstRvH+Yy1qjCN8u9QofqmF5dpu",
	"39qqfIgwCwRLKBcN1f9d86mglUhc4NysWWyxiGp+vwaU1bnzofGVvJ8R3448MB/T1c25bs3zgV++foIj",
	"uY8vcazq41jNCtQW+e0MB0ZOcYP+xwiJxZ80VBHy++be8+fTxf1q4rzls4pR75bmXqsrqDEfu0TgN6TY",
	"AuUHlYdyoBAeX+Opok/HuniOFWHKaVQFM5oW0AVbLh4mF824uEcrDwTKE8AHO2qmkgLfnc6iMh4Uk75m",
	"o6GGpkE3TkXzk81PPlI/jfrfAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
