# кодогенерации на основе openAPI контракта по всем контрактам в папке api
CONTRACTS := auth dict candidate employer testing interaction search
FE_API_DIR := front/src/api
TS_CODEGEN_VERSION := 5.5.3
HEY_API_VERSION := 0.60.0
CODEGEN_TMP := $(shell mktemp -d -t fsp-codegen-XXXXXX)

HEY_API_VERSION    := 0.55.3
TS_CODEGEN_VERSION := 5.5.3

gen: gen-go gen-frontend

gen-go: ## Go: oapi-codegen по всем api/<service>/openapi.yaml
	@go get github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen
	
	@for s in $(CONTRACTS); do \
		echo ">> $$s"; \
		go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen \
			-config api/$$s/codegen.yaml api/$$s/openapi.yaml; \
	done

	@go mod tidy

gen-frontend:
	@echo ">> tmp dir: $(CODEGEN_TMP)"
	@cd $(CODEGEN_TMP) && npm init -y >/dev/null 2>&1
	@cd $(CODEGEN_TMP) && npm install --no-package-lock --no-audit --no-fund \
		typescript@$(TS_CODEGEN_VERSION) \
		@hey-api/openapi-ts@$(HEY_API_VERSION)
	@echo ">> generate"
	@mkdir -p $(FE_API_DIR)
	@for s in $(CONTRACTS); do \
		echo "   ts  $$s"; \
		( cd $(CODEGEN_TMP) && ./node_modules/.bin/openapi-ts \
			-i $(CURDIR)/api/$$s/openapi.yaml \
			-o $(CURDIR)/$(FE_API_DIR)/$$s \
			-c @hey-api/client-fetch ) || { echo "FAILED on $$s"; exit 1; }; \
	done
	@echo ">> cleanup $(CODEGEN_TMP)"
	@rm -rf $(CODEGEN_TMP)
	@$(MAKE) --no-print-directory gen-frontend-barrel

gen-frontend-barrel:
	@printf '%s\n' \
		"// AUTO-GENERATED by 'make gen-frontend'. Do not edit." \
		"" \
		> $(FE_API_DIR)/index.ts
	@for s in $(CONTRACTS); do \
		echo "export * as $$s from './$$s';" >> $(FE_API_DIR)/index.ts; \
	done

seed: ## Запуск сидинга синтетических данных
	python3 seed.py

validate: ## Запуск процедуры валидации алгоритмов (BE2-05)
	python3 validate.py