// Package apiemployer provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apiemployer

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for NeedStatus.
const (
	NeedStatusActive NeedStatus = "active"
	NeedStatusClosed NeedStatus = "closed"
	NeedStatusDraft  NeedStatus = "draft"
)

// Valid indicates whether the value is a known member of the NeedStatus enum.
func (e NeedStatus) Valid() bool {
	switch e {
	case NeedStatusActive:
		return true
	case NeedStatusClosed:
		return true
	case NeedStatusDraft:
		return true
	default:
		return false
	}
}

// Defines values for NeedWorkFormat.
const (
	NeedWorkFormatHybrid      NeedWorkFormat = "hybrid"
	NeedWorkFormatLessThannil NeedWorkFormat = "<nil>"
	NeedWorkFormatOffice      NeedWorkFormat = "office"
	NeedWorkFormatRemote      NeedWorkFormat = "remote"
)

// Valid indicates whether the value is a known member of the NeedWorkFormat enum.
func (e NeedWorkFormat) Valid() bool {
	switch e {
	case NeedWorkFormatHybrid:
		return true
	case NeedWorkFormatLessThannil:
		return true
	case NeedWorkFormatOffice:
		return true
	case NeedWorkFormatRemote:
		return true
	default:
		return false
	}
}

// Defines values for NeedInputStatus.
const (
	NeedInputStatusActive NeedInputStatus = "active"
	NeedInputStatusClosed NeedInputStatus = "closed"
	NeedInputStatusDraft  NeedInputStatus = "draft"
)

// Valid indicates whether the value is a known member of the NeedInputStatus enum.
func (e NeedInputStatus) Valid() bool {
	switch e {
	case NeedInputStatusActive:
		return true
	case NeedInputStatusClosed:
		return true
	case NeedInputStatusDraft:
		return true
	default:
		return false
	}
}

// Defines values for NeedInputWorkFormat.
const (
	NeedInputWorkFormatHybrid NeedInputWorkFormat = "hybrid"
	NeedInputWorkFormatOffice NeedInputWorkFormat = "office"
	NeedInputWorkFormatRemote NeedInputWorkFormat = "remote"
)

// Valid indicates whether the value is a known member of the NeedInputWorkFormat enum.
func (e NeedInputWorkFormat) Valid() bool {
	switch e {
	case NeedInputWorkFormatHybrid:
		return true
	case NeedInputWorkFormatOffice:
		return true
	case NeedInputWorkFormatRemote:
		return true
	default:
		return false
	}
}

// Defines values for VacancyStatus.
const (
	VacancyStatusArchived  VacancyStatus = "archived"
	VacancyStatusDraft     VacancyStatus = "draft"
	VacancyStatusPublished VacancyStatus = "published"
)

// Valid indicates whether the value is a known member of the VacancyStatus enum.
func (e VacancyStatus) Valid() bool {
	switch e {
	case VacancyStatusArchived:
		return true
	case VacancyStatusDraft:
		return true
	case VacancyStatusPublished:
		return true
	default:
		return false
	}
}

// Defines values for VacancyWorkFormat.
const (
	VacancyWorkFormatHybrid VacancyWorkFormat = "hybrid"
	VacancyWorkFormatOffice VacancyWorkFormat = "office"
	VacancyWorkFormatRemote VacancyWorkFormat = "remote"
)

// Valid indicates whether the value is a known member of the VacancyWorkFormat enum.
func (e VacancyWorkFormat) Valid() bool {
	switch e {
	case VacancyWorkFormatHybrid:
		return true
	case VacancyWorkFormatOffice:
		return true
	case VacancyWorkFormatRemote:
		return true
	default:
		return false
	}
}

// Defines values for VacancyInputWorkFormat.
const (
	VacancyInputWorkFormatHybrid VacancyInputWorkFormat = "hybrid"
	VacancyInputWorkFormatOffice VacancyInputWorkFormat = "office"
	VacancyInputWorkFormatRemote VacancyInputWorkFormat = "remote"
)

// Valid indicates whether the value is a known member of the VacancyInputWorkFormat enum.
func (e VacancyInputWorkFormat) Valid() bool {
	switch e {
	case VacancyInputWorkFormatHybrid:
		return true
	case VacancyInputWorkFormatOffice:
		return true
	case VacancyInputWorkFormatRemote:
		return true
	default:
		return false
	}
}

// Company defines model for Company.
type Company struct {
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Industry    *string            `json:"industry,omitempty"`
	Name        string             `json:"name"`
	Size        *string            `json:"size,omitempty"`
	Website     *string            `json:"website,omitempty"`
}

// CompanyInput defines model for CompanyInput.
type CompanyInput struct {
	Description *string `json:"description,omitempty"`
	Industry    *string `json:"industry,omitempty"`
	Name        string  `json:"name"`
	Size        *string `json:"size,omitempty"`
	Website     *string `json:"website,omitempty"`
}

// MatchCard defines model for MatchCard.
type MatchCard struct {
	CandidateUserId *openapi_types.UUID `json:"candidateUserId,omitempty"`
	CategoryId      *openapi_types.UUID `json:"categoryId,omitempty"`
	DisplayName     *string             `json:"displayName,omitempty"`
	GradeId         *openapi_types.UUID `json:"gradeId,omitempty"`
	HasFSP          *bool               `json:"hasFSP,omitempty"`
	Reasons         *[]string           `json:"reasons,omitempty"`
	Score           *float32            `json:"score,omitempty"`
}

// Need defines model for Need.
type Need struct {
	CategoryId       *openapi_types.UUID   `json:"categoryId,omitempty"`
	Currency         string                `json:"currency"`
	Description      string                `json:"description"`
	GradeId          *openapi_types.UUID   `json:"gradeId,omitempty"`
	Id               openapi_types.UUID    `json:"id"`
	SalaryMax        int                   `json:"salaryMax"`
	SalaryMin        int                   `json:"salaryMin"`
	SpecializationId *openapi_types.UUID   `json:"specializationId,omitempty"`
	Stack            *[]openapi_types.UUID `json:"stack,omitempty"`
	Status           NeedStatus            `json:"status"`
	Title            string                `json:"title"`
	WorkFormat       *NeedWorkFormat       `json:"workFormat,omitempty"`
}

// NeedStatus defines model for Need.Status.
type NeedStatus string

// NeedWorkFormat defines model for Need.WorkFormat.
type NeedWorkFormat string

// NeedInput defines model for NeedInput.
type NeedInput struct {
	CategoryId       *openapi_types.UUID   `json:"categoryId,omitempty"`
	Description      string                `json:"description"`
	GradeId          *openapi_types.UUID   `json:"gradeId,omitempty"`
	SalaryMax        int                   `json:"salaryMax"`
	SalaryMin        int                   `json:"salaryMin"`
	SpecializationId *openapi_types.UUID   `json:"specializationId,omitempty"`
	Stack            *[]openapi_types.UUID `json:"stack,omitempty"`
	Status           *NeedInputStatus      `json:"status,omitempty"`
	Title            string                `json:"title"`
	WorkFormat       *NeedInputWorkFormat  `json:"workFormat,omitempty"`
}

// NeedInputStatus defines model for NeedInput.Status.
type NeedInputStatus string

// NeedInputWorkFormat defines model for NeedInput.WorkFormat.
type NeedInputWorkFormat string

// Vacancy defines model for Vacancy.
type Vacancy struct {
	CategoryId  *openapi_types.UUID   `json:"categoryId,omitempty"`
	CompanyId   *openapi_types.UUID   `json:"companyId,omitempty"`
	CreatedAt   *time.Time            `json:"createdAt,omitempty"`
	Description string                `json:"description"`
	Id          *openapi_types.UUID   `json:"id,omitempty"`
	PublishedAt *time.Time            `json:"publishedAt,omitempty"`
	SalaryMax   int                   `json:"salaryMax"`
	SalaryMin   int                   `json:"salaryMin"`
	Stack       *[]openapi_types.UUID `json:"stack,omitempty"`
	Status      *VacancyStatus        `json:"status,omitempty"`
	Title       string                `json:"title"`
	WorkFormat  *VacancyWorkFormat    `json:"workFormat,omitempty"`
}

// VacancyStatus defines model for Vacancy.Status.
type VacancyStatus string

// VacancyWorkFormat defines model for Vacancy.WorkFormat.
type VacancyWorkFormat string

// VacancyInput defines model for VacancyInput.
type VacancyInput struct {
	CategoryId  *openapi_types.UUID     `json:"categoryId,omitempty"`
	Description string                  `json:"description"`
	SalaryMax   int                     `json:"salaryMax"`
	SalaryMin   int                     `json:"salaryMin"`
	Stack       *[]openapi_types.UUID   `json:"stack,omitempty"`
	Title       string                  `json:"title"`
	WorkFormat  *VacancyInputWorkFormat `json:"workFormat,omitempty"`
}

// VacancyInputWorkFormat defines model for VacancyInput.WorkFormat.
type VacancyInputWorkFormat string

// GetNeedMatchesParams defines parameters for GetNeedMatches.
type GetNeedMatchesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListPublicVacanciesParams defines parameters for ListPublicVacancies.
type ListPublicVacanciesParams struct {
	CategoryId *openapi_types.UUID `form:"categoryId,omitempty" json:"categoryId,omitempty"`
	GradeId    *openapi_types.UUID `form:"gradeId,omitempty" json:"gradeId,omitempty"`
	Limit      *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int                `form:"offset,omitempty" json:"offset,omitempty"`
}

// UpsertMyCompanyJSONRequestBody defines body for UpsertMyCompany for application/json ContentType.
type UpsertMyCompanyJSONRequestBody = CompanyInput

// CreateNeedJSONRequestBody defines body for CreateNeed for application/json ContentType.
type CreateNeedJSONRequestBody = NeedInput

// UpdateNeedJSONRequestBody defines body for UpdateNeed for application/json ContentType.
type UpdateNeedJSONRequestBody = NeedInput

// CreateVacancyJSONRequestBody defines body for CreateVacancy for application/json ContentType.
type CreateVacancyJSONRequestBody = VacancyInput

// UpdateVacancyJSONRequestBody defines body for UpdateVacancy for application/json ContentType.
type UpdateVacancyJSONRequestBody = VacancyInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /healthz)
	Healthz(c *gin.Context)

	// (GET /me/company)
	GetMyCompany(c *gin.Context)

	// (PUT /me/company)
	UpsertMyCompany(c *gin.Context)

	// (GET /me/needs)
	ListMyNeeds(c *gin.Context)

	// (POST /me/needs)
	CreateNeed(c *gin.Context)

	// (DELETE /me/needs/{id})
	DeleteNeed(c *gin.Context, id openapi_types.UUID)

	// (PATCH /me/needs/{id})
	UpdateNeed(c *gin.Context, id openapi_types.UUID)

	// (GET /me/needs/{id}/matches)
	GetNeedMatches(c *gin.Context, id openapi_types.UUID, params GetNeedMatchesParams)

	// (GET /me/vacancies)
	ListMyVacancies(c *gin.Context)

	// (POST /me/vacancies)
	CreateVacancy(c *gin.Context)

	// (DELETE /me/vacancies/{id})
	DeleteVacancy(c *gin.Context, id openapi_types.UUID)

	// (PATCH /me/vacancies/{id})
	UpdateVacancy(c *gin.Context, id openapi_types.UUID)

	// (POST /me/vacancies/{id}/publish)
	PublishVacancy(c *gin.Context, id openapi_types.UUID)

	// (GET /vacancies)
	ListPublicVacancies(c *gin.Context, params ListPublicVacanciesParams)

	// (GET /vacancies/{id})
	GetPublicVacancy(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// GetMyCompany operation middleware
func (siw *ServerInterfaceWrapper) GetMyCompany(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyCompany(c)
}

// UpsertMyCompany operation middleware
func (siw *ServerInterfaceWrapper) UpsertMyCompany(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpsertMyCompany(c)
}

// ListMyNeeds operation middleware
func (siw *ServerInterfaceWrapper) ListMyNeeds(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMyNeeds(c)
}

// CreateNeed operation middleware
func (siw *ServerInterfaceWrapper) CreateNeed(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateNeed(c)
}

// DeleteNeed operation middleware
func (siw *ServerInterfaceWrapper) DeleteNeed(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteNeed(c, id)
}

// UpdateNeed operation middleware
func (siw *ServerInterfaceWrapper) UpdateNeed(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateNeed(c, id)
}

// GetNeedMatches operation middleware
func (siw *ServerInterfaceWrapper) GetNeedMatches(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNeedMatchesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetNeedMatches(c, id, params)
}

// ListMyVacancies operation middleware
func (siw *ServerInterfaceWrapper) ListMyVacancies(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMyVacancies(c)
}

// CreateVacancy operation middleware
func (siw *ServerInterfaceWrapper) CreateVacancy(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateVacancy(c)
}

// DeleteVacancy operation middleware
func (siw *ServerInterfaceWrapper) DeleteVacancy(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteVacancy(c, id)
}

// UpdateVacancy operation middleware
func (siw *ServerInterfaceWrapper) UpdateVacancy(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateVacancy(c, id)
}

// PublishVacancy operation middleware
func (siw *ServerInterfaceWrapper) PublishVacancy(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PublishVacancy(c, id)
}

// ListPublicVacancies operation middleware
func (siw *ServerInterfaceWrapper) ListPublicVacancies(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPublicVacanciesParams

	// ------------- Optional query parameter "categoryId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "categoryId", c.Request.URL.Query(), &params.CategoryId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "gradeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "gradeId", c.Request.URL.Query(), &params.GradeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gradeId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPublicVacancies(c, params)
}

// GetPublicVacancy operation middleware
func (siw *ServerInterfaceWrapper) GetPublicVacancy(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPublicVacancy(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/me/company", wrapper.GetMyCompany)
	router.PUT(options.BaseURL+"/me/company", wrapper.UpsertMyCompany)
	router.GET(options.BaseURL+"/me/needs", wrapper.ListMyNeeds)
	router.POST(options.BaseURL+"/me/needs", wrapper.CreateNeed)
	router.DELETE(options.BaseURL+"/me/needs/:id", wrapper.DeleteNeed)
	router.PATCH(options.BaseURL+"/me/needs/:id", wrapper.UpdateNeed)
	router.GET(options.BaseURL+"/me/needs/:id/matches", wrapper.GetNeedMatches)
	router.GET(options.BaseURL+"/me/vacancies", wrapper.ListMyVacancies)
	router.POST(options.BaseURL+"/me/vacancies", wrapper.CreateVacancy)
	router.DELETE(options.BaseURL+"/me/vacancies/:id", wrapper.DeleteVacancy)
	router.PATCH(options.BaseURL+"/me/vacancies/:id", wrapper.UpdateVacancy)
	router.POST(options.BaseURL+"/me/vacancies/:id/publish", wrapper.PublishVacancy)
	router.GET(options.BaseURL+"/vacancies", wrapper.ListPublicVacancies)
	router.GET(options.BaseURL+"/vacancies/:id", wrapper.GetPublicVacancy)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FjPbtw2E3+VBb/vqHrlNIdgb0natGnrxKib9GAsCq40azGRRIWk3CjGAnF6KNAWCFD01EODoi9gBzFq",
	"JLHzCtQr9EkKUtJKsqiVDNvrJifLy+H8+c2PM0PuIIcGEQ0hFByNdhB3PAiw/rxJgwiHifqMGI2ACQJ6",
	"wQXuMBIJQkP1r0giQKNNxAUj4RayUBj7PhrPLERctT6lLMACjVAcExdZuXwhrsRCN+aCJYuVhTiAUqKy",
	"nZMnsHjr9zDhREDdGUaQ1bpnZiEGj2LCwFXL2m/twLjYg+jkAThCOZADdTuMYtETrYXRVxZ7Bl1Z6Ip1",
	"LnoixNbo1rBwvJuYuc3QHBy6xMUC7nFgt/sl28ECtihLeoq7hEc+Tu604bDFsAs9dXmY39pYr6iZUOoD",
	"DpGGAnMa6qiIgEB/wGMcRL4S1Fa+CxQSJsX5D5gxnOjkOJTVMzD1KRbl1jAOJsB0Dhp43wEwQt0Nm4n6",
	"TswYhE6SMXGKY19t+/reDSPYHVTtBPsMRYBjH7NkDT+uWCahgC1glWUStixH4BDskydYOX9aF7nAzsNa",
	"6jvdbaRcYBHrrRDGgTLjMjwVyELYEWQbkIUcn3Jw0dikjQi/5ThT9vBW7kypm0FAhdLpJROmHaTTKXEA",
	"WSqm8enqWma8nv0q4NXcVAg1j3ncQuKWenjaAnBWTrZxLCAhCRScttXFtw7R3tyruvLBUG7c1VlOwy8T",
	"l+5jB+cVDPv+3Skabe6g/zOYohH637AcX4b57DLMN2T8m1kNAubtume/YoAFuNdFTVo1vY8ECcC0pWfF",
	"i+KJT7jXQ3dLzWrJ/lwvshBmjke2jRRo9p5xCfZyzu4FncezH6335XCoaMGJGRHJhiJ/lqUJYAbseiy8",
	"8r/CZ/TFt98opVoajfLVEhNPiAjNZnounVINQYYFurWxPlj3sVBgDv55+tvg0yDyaQJssAFsWzcftA2M",
	"62Sj1RV7xUYzC9EIQhwRNEIfr6yu2MhCERae9nPoAfaF90R9b4EGVJFtXkbR5/m6goxHNORZfFdsuzFY",
	"o7tf1uBAo03d7YYBDJ3yImM08xmItaS47ZhtOTQUEOq9OIp84ujdwwc8Y3ZWedBocV0qTGh4697L3+Wx",
	"fCvfyT15JA/T55lMFBu8vRdxYCccfhQDFzeom5y3r3kNrbNWsBhml4TTH3JfHslj+VK+kQfqS0nleQ4B",
	"XN6a5a8IF2vJHS1zRufnhWVRFMpSs7YYQnohj9Nn6VN5kIWW7qbP5OFAvq4yQh7mjKDcENpN3aO0wYth",
	"QznO9aLC6rkaNoL2pzyWf8tXcs/EgeEOcWdZifBBQBOwT/TvOWARZjgAAYzryYIo/apGFVf+UTYm14O2",
	"KgF0tJfZuAHQ1Wb9kn/paCqs1pXS8UwVwMVL9v7SKWVfPKU6S4um1VC/AkC1zjTPs3wl9+Vx+lS+lnvq",
	"JCuWvpKHKsPpM2ViIN8pKf3n5OFPf7EG6e5AHsv99Kf0eborj7Q/h/JAvkVWs3mpiNZyr5ZACCtX+igG",
	"lpRafRIQgaqK5u8NV2wLBfhxNrOt2rZVTnCrzQmuzQCdTjm0WLCthUPhbHxGQtXH4Hn979UIygc006RJ",
	"BfZNbxonb+raUiFvmARnVgcPK2ze1kM+ga5meX8ut4yGWdzz+vTMX+VedqzS3X7NsVB+McWsfuNcbouc",
	"w9bRJY0E6NkpS/Te02a57AD+CxSzl0KxRV2zTrNh/jCh66nxqK5nApfKtmWh9i79Qe7LN/JQD/ov64Ns",
	"vwKt4XKqRdqE14kuWnnCOYemX7y+Lnt+OKeZ4dznhHNvdC8KmqQ/yqP0Z3kwkC8bvc/w7NGs8G1PH1UW",
	"fdBnrjYzpM8NuNV/qD+kbY6V4xzYdoFMzPz8wWw0HPrUwb5HuRhds69dVW+p/w4A",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
