// Package apiemployer provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apiemployer

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CandidateContactsMaskedFields.
const (
	Email    CandidateContactsMaskedFields = "email"
	Github   CandidateContactsMaskedFields = "github"
	Linkedin CandidateContactsMaskedFields = "linkedin"
	Phone    CandidateContactsMaskedFields = "phone"
	Telegram CandidateContactsMaskedFields = "telegram"
	Website  CandidateContactsMaskedFields = "website"
)

// Valid indicates whether the value is a known member of the CandidateContactsMaskedFields enum.
func (e CandidateContactsMaskedFields) Valid() bool {
	switch e {
	case Email:
		return true
	case Github:
		return true
	case Linkedin:
		return true
	case Phone:
		return true
	case Telegram:
		return true
	case Website:
		return true
	default:
		return false
	}
}

// Defines values for NeedStatus.
const (
	NeedStatusActive NeedStatus = "active"
	NeedStatusClosed NeedStatus = "closed"
	NeedStatusDraft  NeedStatus = "draft"
)

// Valid indicates whether the value is a known member of the NeedStatus enum.
func (e NeedStatus) Valid() bool {
	switch e {
	case NeedStatusActive:
		return true
	case NeedStatusClosed:
		return true
	case NeedStatusDraft:
		return true
	default:
		return false
	}
}

// Defines values for NeedWorkFormat.
const (
	NeedWorkFormatHybrid      NeedWorkFormat = "hybrid"
	NeedWorkFormatLessThannil NeedWorkFormat = "<nil>"
	NeedWorkFormatOffice      NeedWorkFormat = "office"
	NeedWorkFormatRemote      NeedWorkFormat = "remote"
)

// Valid indicates whether the value is a known member of the NeedWorkFormat enum.
func (e NeedWorkFormat) Valid() bool {
	switch e {
	case NeedWorkFormatHybrid:
		return true
	case NeedWorkFormatLessThannil:
		return true
	case NeedWorkFormatOffice:
		return true
	case NeedWorkFormatRemote:
		return true
	default:
		return false
	}
}

// Defines values for NeedInputStatus.
const (
	NeedInputStatusActive NeedInputStatus = "active"
	NeedInputStatusClosed NeedInputStatus = "closed"
	NeedInputStatusDraft  NeedInputStatus = "draft"
)

// Valid indicates whether the value is a known member of the NeedInputStatus enum.
func (e NeedInputStatus) Valid() bool {
	switch e {
	case NeedInputStatusActive:
		return true
	case NeedInputStatusClosed:
		return true
	case NeedInputStatusDraft:
		return true
	default:
		return false
	}
}

// Defines values for NeedInputWorkFormat.
const (
	NeedInputWorkFormatHybrid NeedInputWorkFormat = "hybrid"
	NeedInputWorkFormatOffice NeedInputWorkFormat = "office"
	NeedInputWorkFormatRemote NeedInputWorkFormat = "remote"
)

// Valid indicates whether the value is a known member of the NeedInputWorkFormat enum.
func (e NeedInputWorkFormat) Valid() bool {
	switch e {
	case NeedInputWorkFormatHybrid:
		return true
	case NeedInputWorkFormatOffice:
		return true
	case NeedInputWorkFormatRemote:
		return true
	default:
		return false
	}
}

// Defines values for VacancyStatus.
const (
	VacancyStatusArchived  VacancyStatus = "archived"
	VacancyStatusDraft     VacancyStatus = "draft"
	VacancyStatusPublished VacancyStatus = "published"
)

// Valid indicates whether the value is a known member of the VacancyStatus enum.
func (e VacancyStatus) Valid() bool {
	switch e {
	case VacancyStatusArchived:
		return true
	case VacancyStatusDraft:
		return true
	case VacancyStatusPublished:
		return true
	default:
		return false
	}
}

// Defines values for VacancyWorkFormat.
const (
	VacancyWorkFormatHybrid VacancyWorkFormat = "hybrid"
	VacancyWorkFormatOffice VacancyWorkFormat = "office"
	VacancyWorkFormatRemote VacancyWorkFormat = "remote"
)

// Valid indicates whether the value is a known member of the VacancyWorkFormat enum.
func (e VacancyWorkFormat) Valid() bool {
	switch e {
	case VacancyWorkFormatHybrid:
		return true
	case VacancyWorkFormatOffice:
		return true
	case VacancyWorkFormatRemote:
		return true
	default:
		return false
	}
}

// Defines values for VacancyInputWorkFormat.
const (
	VacancyInputWorkFormatHybrid VacancyInputWorkFormat = "hybrid"
	VacancyInputWorkFormatOffice VacancyInputWorkFormat = "office"
	VacancyInputWorkFormatRemote VacancyInputWorkFormat = "remote"
)

// Valid indicates whether the value is a known member of the VacancyInputWorkFormat enum.
func (e VacancyInputWorkFormat) Valid() bool {
	switch e {
	case VacancyInputWorkFormatHybrid:
		return true
	case VacancyInputWorkFormatOffice:
		return true
	case VacancyInputWorkFormatRemote:
		return true
	default:
		return false
	}
}

// Defines values for SearchCandidatesParamsSort.
const (
	FspWeight SearchCandidatesParamsSort = "fspWeight"
	Relevance SearchCandidatesParamsSort = "relevance"
	TestScore SearchCandidatesParamsSort = "testScore"
)

// Valid indicates whether the value is a known member of the SearchCandidatesParamsSort enum.
func (e SearchCandidatesParamsSort) Valid() bool {
	switch e {
	case FspWeight:
		return true
	case Relevance:
		return true
	case TestScore:
		return true
	default:
		return false
	}
}

// CandidateCard Карточка кандидата без контактов, пока reveal не подтверждён.
// Структура соответствует ответу candidate-сервиса.
type CandidateCard struct {
	CategoryId       *openapi_types.UUID  `json:"categoryId,omitempty"`
	Contacts         *CandidateContacts   `json:"contacts,omitempty"`
	DisplayName      *string              `json:"displayName,omitempty"`
	Fsp              *CandidateCardFsp    `json:"fsp,omitempty"`
	GradeId          *openapi_types.UUID  `json:"gradeId,omitempty"`
	Headline         *string              `json:"headline,omitempty"`
	Location         *string              `json:"location,omitempty"`
	Salary           *CandidateCardSalary `json:"salary,omitempty"`
	SoftSkills       *[]string            `json:"softSkills,omitempty"`
	SpecializationId *openapi_types.UUID  `json:"specializationId,omitempty"`
	UserId           *openapi_types.UUID  `json:"userId,omitempty"`
	YearsExperience  *float32             `json:"yearsExperience,omitempty"`
}

// CandidateCardFsp defines model for CandidateCardFsp.
type CandidateCardFsp struct {
	AchievementsCount *int  `json:"achievementsCount,omitempty"`
	BestPlace         *int  `json:"bestPlace,omitempty"`
	HasFSP            *bool `json:"hasFSP,omitempty"`
}

// CandidateCardSalary defines model for CandidateCardSalary.
type CandidateCardSalary struct {
	Currency *string `json:"currency,omitempty"`
	Masked   *bool   `json:"masked,omitempty"`
	Max      *int    `json:"max,omitempty"`
	Min      *int    `json:"min,omitempty"`
}

// CandidateContacts defines model for CandidateContacts.
type CandidateContacts struct {
	Email        *openapi_types.Email             `json:"email,omitempty"`
	Github       *string                          `json:"github,omitempty"`
	Linkedin     *string                          `json:"linkedin,omitempty"`
	Masked       *bool                            `json:"masked,omitempty"`
	MaskedFields *[]CandidateContactsMaskedFields `json:"maskedFields,omitempty"`
	Phone        *string                          `json:"phone,omitempty"`
	Telegram     *string                          `json:"telegram,omitempty"`
	Website      *string                          `json:"website,omitempty"`
}

// CandidateContactsMaskedFields defines model for CandidateContacts.MaskedFields.
type CandidateContactsMaskedFields string

// CandidateSearchHit defines model for CandidateSearchHit.
type CandidateSearchHit struct {
	CategoryId           openapi_types.UUID `json:"categoryId"`
	DisplayName          string             `json:"displayName"`
	FspAchievementsCount *int               `json:"fspAchievementsCount,omitempty"`
	FspBestPlace         *int               `json:"fspBestPlace,omitempty"`
	FspWeightSum         *int               `json:"fspWeightSum,omitempty"`
	GradeId              openapi_types.UUID `json:"gradeId"`
	Reasons              []string           `json:"reasons"`
	Score                float32            `json:"score"`
	SpecializationId     openapi_types.UUID `json:"specializationId"`
	TestScore            *float32           `json:"testScore,omitempty"`
	UserId               openapi_types.UUID `json:"userId"`
	YearsExperience      *float32           `json:"yearsExperience,omitempty"`
}

// CandidateSearchPage defines model for CandidateSearchPage.
type CandidateSearchPage struct {
	Items  []CandidateSearchHit `json:"items"`
	Limit  int                  `json:"limit"`
	Offset int                  `json:"offset"`
	Total  int                  `json:"total"`
}

// Company defines model for Company.
type Company struct {
	ContactEmail    *openapi_types.Email `json:"contactEmail,omitempty"`
	ContactPerson   *string              `json:"contactPerson,omitempty"`
	ContactPhone    *string              `json:"contactPhone,omitempty"`
	ContactTelegram *string              `json:"contactTelegram,omitempty"`
	Description     *string              `json:"description,omitempty"`
	Id              openapi_types.UUID   `json:"id"`
	Industry        *string              `json:"industry,omitempty"`
	Name            string               `json:"name"`
	Size            *string              `json:"size,omitempty"`
	Website         *string              `json:"website,omitempty"`
}

// CompanyInput defines model for CompanyInput.
type CompanyInput struct {
	ContactEmail    *openapi_types.Email `json:"contactEmail,omitempty"`
	ContactPerson   *string              `json:"contactPerson,omitempty"`
	ContactPhone    *string              `json:"contactPhone,omitempty"`
	ContactTelegram *string              `json:"contactTelegram,omitempty"`
	Description     *string              `json:"description,omitempty"`
	Industry        *string              `json:"industry,omitempty"`
	Name            string               `json:"name"`
	Size            *string              `json:"size,omitempty"`
	Website         *string              `json:"website,omitempty"`
}

// MatchCard defines model for MatchCard.
type MatchCard struct {
	CandidateUserId *openapi_types.UUID `json:"candidateUserId,omitempty"`
	CategoryId      *openapi_types.UUID `json:"categoryId,omitempty"`
	DisplayName     *string             `json:"displayName,omitempty"`
	GradeId         *openapi_types.UUID `json:"gradeId,omitempty"`
	HasFSP          *bool               `json:"hasFSP,omitempty"`
	Reasons         *[]string           `json:"reasons,omitempty"`
	Score           *float32            `json:"score,omitempty"`
}

// Need defines model for Need.
type Need struct {
	CategoryId         *openapi_types.UUID   `json:"categoryId,omitempty"`
	Currency           string                `json:"currency"`
	Description        string                `json:"description"`
	GradeId            *openapi_types.UUID   `json:"gradeId,omitempty"`
	Id                 openapi_types.UUID    `json:"id"`
	Location           *string               `json:"location,omitempty"`
	MinExperienceYears *float32              `json:"minExperienceYears,omitempty"`
	SalaryMax          int                   `json:"salaryMax"`
	SalaryMin          int                   `json:"salaryMin"`
	SpecializationId   *openapi_types.UUID   `json:"specializationId,omitempty"`
	Stack              *[]openapi_types.UUID `json:"stack,omitempty"`
	Status             NeedStatus            `json:"status"`
	Title              string                `json:"title"`
	WorkFormat         *NeedWorkFormat       `json:"workFormat,omitempty"`
}

// NeedStatus defines model for Need.Status.
type NeedStatus string

// NeedWorkFormat defines model for Need.WorkFormat.
type NeedWorkFormat string

// NeedInput defines model for NeedInput.
type NeedInput struct {
	CategoryId         *openapi_types.UUID   `json:"categoryId,omitempty"`
	Description        string                `json:"description"`
	GradeId            *openapi_types.UUID   `json:"gradeId,omitempty"`
	Location           *string               `json:"location,omitempty"`
	MinExperienceYears *float32              `json:"minExperienceYears,omitempty"`
	SalaryMax          int                   `json:"salaryMax"`
	SalaryMin          int                   `json:"salaryMin"`
	SpecializationId   *openapi_types.UUID   `json:"specializationId,omitempty"`
	Stack              *[]openapi_types.UUID `json:"stack,omitempty"`
	Status             *NeedInputStatus      `json:"status,omitempty"`
	Title              string                `json:"title"`
	WorkFormat         *NeedInputWorkFormat  `json:"workFormat,omitempty"`
}

// NeedInputStatus defines model for NeedInput.Status.
type NeedInputStatus string

// NeedInputWorkFormat defines model for NeedInput.WorkFormat.
type NeedInputWorkFormat string

// Vacancy defines model for Vacancy.
type Vacancy struct {
	CategoryId       *openapi_types.UUID   `json:"categoryId,omitempty"`
	CompanyId        *openapi_types.UUID   `json:"companyId,omitempty"`
	CreatedAt        *time.Time            `json:"createdAt,omitempty"`
	Description      string                `json:"description"`
	GradeId          *openapi_types.UUID   `json:"gradeId,omitempty"`
	Id               *openapi_types.UUID   `json:"id,omitempty"`
	Location         *string               `json:"location,omitempty"`
	PublishedAt      *time.Time            `json:"publishedAt,omitempty"`
	SalaryMax        int                   `json:"salaryMax"`
	SalaryMin        int                   `json:"salaryMin"`
	SpecializationId *openapi_types.UUID   `json:"specializationId,omitempty"`
	Stack            *[]openapi_types.UUID `json:"stack,omitempty"`
	Status           *VacancyStatus        `json:"status,omitempty"`
	Title            string                `json:"title"`
	WorkFormat       *VacancyWorkFormat    `json:"workFormat,omitempty"`
}

// VacancyStatus defines model for Vacancy.Status.
type VacancyStatus string

// VacancyWorkFormat defines model for Vacancy.WorkFormat.
type VacancyWorkFormat string

// VacancyInput defines model for VacancyInput.
type VacancyInput struct {
	CategoryId       *openapi_types.UUID     `json:"categoryId,omitempty"`
	Description      string                  `json:"description"`
	GradeId          *openapi_types.UUID     `json:"gradeId,omitempty"`
	Location         *string                 `json:"location,omitempty"`
	SalaryMax        int                     `json:"salaryMax"`
	SalaryMin        int                     `json:"salaryMin"`
	SpecializationId *openapi_types.UUID     `json:"specializationId,omitempty"`
	Stack            *[]openapi_types.UUID   `json:"stack,omitempty"`
	Title            string                  `json:"title"`
	WorkFormat       *VacancyInputWorkFormat `json:"workFormat,omitempty"`
}

// VacancyInputWorkFormat defines model for VacancyInput.WorkFormat.
type VacancyInputWorkFormat string

// SearchCandidatesParams defines parameters for SearchCandidates.
type SearchCandidatesParams struct {
	CategoryId       *openapi_types.UUID `form:"categoryId,omitempty" json:"categoryId,omitempty"`
	SpecializationId *openapi_types.UUID `form:"specializationId,omitempty" json:"specializationId,omitempty"`
	GradeId          *openapi_types.UUID `form:"gradeId,omitempty" json:"gradeId,omitempty"`

	// Stack Повторяющийся параметр — ID технологий
	Stack *[]openapi_types.UUID `form:"stack,omitempty" json:"stack,omitempty"`

	// HasFsp Только кандидаты с подтверждёнными достижениями ФСП
	HasFsp             *bool                       `form:"hasFsp,omitempty" json:"hasFsp,omitempty"`
	MinYearsExperience *float32                    `form:"minYearsExperience,omitempty" json:"minYearsExperience,omitempty"`
	Location           *string                     `form:"location,omitempty" json:"location,omitempty"`
	Sort               *SearchCandidatesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
	Limit              *int                        `form:"limit,omitempty" json:"limit,omitempty"`
	Offset             *int                        `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchCandidatesParamsSort defines parameters for SearchCandidates.
type SearchCandidatesParamsSort string

// GetNeedMatchesParams defines parameters for GetNeedMatches.
type GetNeedMatchesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListPublicVacanciesParams defines parameters for ListPublicVacancies.
type ListPublicVacanciesParams struct {
	CategoryId *openapi_types.UUID `form:"categoryId,omitempty" json:"categoryId,omitempty"`
	GradeId    *openapi_types.UUID `form:"gradeId,omitempty" json:"gradeId,omitempty"`
	Limit      *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int                `form:"offset,omitempty" json:"offset,omitempty"`
}

// UpsertMyCompanyJSONRequestBody defines body for UpsertMyCompany for application/json ContentType.
type UpsertMyCompanyJSONRequestBody = CompanyInput

// CreateNeedJSONRequestBody defines body for CreateNeed for application/json ContentType.
type CreateNeedJSONRequestBody = NeedInput

// UpdateNeedJSONRequestBody defines body for UpdateNeed for application/json ContentType.
type UpdateNeedJSONRequestBody = NeedInput

// CreateVacancyJSONRequestBody defines body for CreateVacancy for application/json ContentType.
type CreateVacancyJSONRequestBody = VacancyInput

// UpdateVacancyJSONRequestBody defines body for UpdateVacancy for application/json ContentType.
type UpdateVacancyJSONRequestBody = VacancyInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /candidates)
	SearchCandidates(c *gin.Context, params SearchCandidatesParams)

	// (GET /candidates/{userId})
	GetCandidateCard(c *gin.Context, userId openapi_types.UUID)

	// (GET /healthz)
	Healthz(c *gin.Context)

	// (GET /me/company)
	GetMyCompany(c *gin.Context)

	// (PUT /me/company)
	UpsertMyCompany(c *gin.Context)

	// (GET /me/needs)
	ListMyNeeds(c *gin.Context)

	// (POST /me/needs)
	CreateNeed(c *gin.Context)

	// (DELETE /me/needs/{id})
	DeleteNeed(c *gin.Context, id openapi_types.UUID)

	// (PATCH /me/needs/{id})
	UpdateNeed(c *gin.Context, id openapi_types.UUID)

	// (GET /me/needs/{id}/matches)
	GetNeedMatches(c *gin.Context, id openapi_types.UUID, params GetNeedMatchesParams)

	// (GET /me/vacancies)
	ListMyVacancies(c *gin.Context)

	// (POST /me/vacancies)
	CreateVacancy(c *gin.Context)

	// (DELETE /me/vacancies/{id})
	DeleteVacancy(c *gin.Context, id openapi_types.UUID)

	// (PATCH /me/vacancies/{id})
	UpdateVacancy(c *gin.Context, id openapi_types.UUID)

	// (POST /me/vacancies/{id}/publish)
	PublishVacancy(c *gin.Context, id openapi_types.UUID)

	// (GET /vacancies)
	ListPublicVacancies(c *gin.Context, params ListPublicVacanciesParams)

	// (GET /vacancies/{id})
	GetPublicVacancy(c *gin.Context, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SearchCandidates operation middleware
func (siw *ServerInterfaceWrapper) SearchCandidates(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchCandidatesParams

	// ------------- Optional query parameter "categoryId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "categoryId", c.Request.URL.Query(), &params.CategoryId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "specializationId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "specializationId", c.Request.URL.Query(), &params.SpecializationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter specializationId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "gradeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "gradeId", c.Request.URL.Query(), &params.GradeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gradeId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "stack" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "stack", c.Request.URL.Query(), &params.Stack, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter stack: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "hasFsp" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "hasFsp", c.Request.URL.Query(), &params.HasFsp, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter hasFsp: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "minYearsExperience" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "minYearsExperience", c.Request.URL.Query(), &params.MinYearsExperience, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter minYearsExperience: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "location" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "location", c.Request.URL.Query(), &params.Location, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter location: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", c.Request.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SearchCandidates(c, params)
}

// GetCandidateCard operation middleware
func (siw *ServerInterfaceWrapper) GetCandidateCard(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCandidateCard(c, userId)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// GetMyCompany operation middleware
func (siw *ServerInterfaceWrapper) GetMyCompany(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyCompany(c)
}

// UpsertMyCompany operation middleware
func (siw *ServerInterfaceWrapper) UpsertMyCompany(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpsertMyCompany(c)
}

// ListMyNeeds operation middleware
func (siw *ServerInterfaceWrapper) ListMyNeeds(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMyNeeds(c)
}

// CreateNeed operation middleware
func (siw *ServerInterfaceWrapper) CreateNeed(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateNeed(c)
}

// DeleteNeed operation middleware
func (siw *ServerInterfaceWrapper) DeleteNeed(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteNeed(c, id)
}

// UpdateNeed operation middleware
func (siw *ServerInterfaceWrapper) UpdateNeed(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateNeed(c, id)
}

// GetNeedMatches operation middleware
func (siw *ServerInterfaceWrapper) GetNeedMatches(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNeedMatchesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetNeedMatches(c, id, params)
}

// ListMyVacancies operation middleware
func (siw *ServerInterfaceWrapper) ListMyVacancies(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMyVacancies(c)
}

// CreateVacancy operation middleware
func (siw *ServerInterfaceWrapper) CreateVacancy(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateVacancy(c)
}

// DeleteVacancy operation middleware
func (siw *ServerInterfaceWrapper) DeleteVacancy(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteVacancy(c, id)
}

// UpdateVacancy operation middleware
func (siw *ServerInterfaceWrapper) UpdateVacancy(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateVacancy(c, id)
}

// PublishVacancy operation middleware
func (siw *ServerInterfaceWrapper) PublishVacancy(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PublishVacancy(c, id)
}

// ListPublicVacancies operation middleware
func (siw *ServerInterfaceWrapper) ListPublicVacancies(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPublicVacanciesParams

	// ------------- Optional query parameter "categoryId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "categoryId", c.Request.URL.Query(), &params.CategoryId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "gradeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "gradeId", c.Request.URL.Query(), &params.GradeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gradeId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPublicVacancies(c, params)
}

// GetPublicVacancy operation middleware
func (siw *ServerInterfaceWrapper) GetPublicVacancy(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPublicVacancy(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/me/company", wrapper.GetMyCompany)
	router.PUT(options.BaseURL+"/me/company", wrapper.UpsertMyCompany)
	router.GET(options.BaseURL+"/me/needs", wrapper.ListMyNeeds)
	router.POST(options.BaseURL+"/me/needs", wrapper.CreateNeed)
	router.DELETE(options.BaseURL+"/me/needs/:id", wrapper.DeleteNeed)
	router.PATCH(options.BaseURL+"/me/needs/:id", wrapper.UpdateNeed)
	router.GET(options.BaseURL+"/me/needs/:id/matches", wrapper.GetNeedMatches)
	router.GET(options.BaseURL+"/me/vacancies", wrapper.ListMyVacancies)
	router.POST(options.BaseURL+"/me/vacancies", wrapper.CreateVacancy)
	router.DELETE(options.BaseURL+"/me/vacancies/:id", wrapper.DeleteVacancy)
	router.PATCH(options.BaseURL+"/me/vacancies/:id", wrapper.UpdateVacancy)
	router.POST(options.BaseURL+"/me/vacancies/:id/publish", wrapper.PublishVacancy)
	router.GET(options.BaseURL+"/candidates", wrapper.SearchCandidates)
	router.GET(options.BaseURL+"/candidates/:userId", wrapper.GetCandidateCard)
	router.GET(options.BaseURL+"/vacancies", wrapper.ListPublicVacancies)
	router.GET(options.BaseURL+"/vacancies/:id", wrapper.GetPublicVacancy)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FptbxvHEf4rh20/siKV+EPAb7ZjJ05rR6jsGIEsFKu7objxvXlvqZoWCOgFbZo6iNCinwK0Rtr+AEoW",
	"Y1qy6L8w+xf6S4rdu+PdkUve6dW1+8WWbt9mZ555ZnZGm8QOvDDwwRcRaW6SyG6DR/WPN6nvMIcKuEm5",
	"oz44ENmchYIFPmkS/BH7ckvu4Eh+i0fYt9Q/eIKHOMRD7Msd9WkfB/hKjYzwRH3BI7UAD2oWvsWRXsZh",
	"A6hr4QkO4o+HcgcPcCC38Gc8lH/Bk4VHPv4kd+SW3FXr5a7cwr4lt3GEo2TujtxWP8ld9bOV+7xr2ek1",
	"fiW39a4HOJTb2F945JMaCXkQAhcM9JVtKmA94N07+r6tgHtUkCbpdJhDakR0QyDNFRIJzvx1UiN+x3XJ",
	"aq9G7MAX1I41+EsOLdIkv6hniq0nWq1nKk0X9GrEYVHo0u496oFaH5+SHtKrkVYUVt+Xcud2FKpl65w6",
	"cNqLtIE6LvNzgphmuYFNYxTMmxVRl/LuqURfjpeoxUFLLD9mrqt1ygR4kVE5yQfKOY3XhWAz6rJnWsDT",
	"Xr8TAZ+3JndwFyiPbj0NgTPw7YLC/I63BjzbNxMzWPsGbKGWT1msuTmBRWq3GWyAp7R1M+j4Ind/5gtY",
	"B642WoNILLm0KEE6nrcsjW4vL+X2WAsCF6hPysVbHhtywls6nINvd+fDwKPRY3BMB6uxpyVie8yfO2O+",
	"8Dm3LIoOHmVuwc7xl3ngWGei3Vkr8QzmPwaH+edRiRq7zcB1itAHv+Op7VJBw3bggxIYXFjn1CNjCXNi",
	"1MjvYS1iAshqrdx54i3nij4+be6s9NCCI3E2R71z7bgMlNvtz5kwYLACY+duXIFrr1fzu1YU3qjoeq0o",
	"fAhsvS2WO555s1KuzonIgUaBP4GNp9QL3XgetR//zqPCbpMKFo/sgOc1kVDXqYg0vz1EYrm45TQdXiLN",
	"cnjSYVy51kp6SNHmtTxgMr0brpvqJlP4ajlEl+g6TGN0bKbxD5UCYoZ6g+Fc5rEZyAxarQhmjIlAUNc0",
	"NKG8WNJ0fnrceG+jKgIvpL4pTMQsfOsMlJssXQIelWUb6dRyCktm3q/EZIWcd95EVg3PzHc6keAlMdOf",
	"xU8RewaXQL0F0yu5tQBzrHzHDzvizKbOXWiGhQ0zioadnjBtzzzvm8w41yy5wYrWyA2UGWE8dUL3M9V+",
	"VxF6+g6bjIAJXzyozqoXHDVPE75m56FloU2fcobQNhap5QZUZEvTWGdKPe4BOGdLNoyMk0uUHWjRjquW",
	"/fbBDaOyS6B6pnddRXaq9rDzmJ9F5K9VgJ4f7uOH4N18rp+PSclwPmkuDJ/rRafzoQKgypOYSSAJKjqF",
	"FNzhtKWARG3BNnRS4QYROOYcmwl3BkkE/PHtRJhsbw5eINSe7e4a1wIGrRazgdTUnVZPR+Px4UVM5RWe",
	"t00OpuM7r85wjVn0f0paOS/S5yI3N2gGrMd85imlN2qG9DePWcPMWfgtmXqWpPrDgfBqWfw7DV5N2PyK",
	"2jThWeq6X7ZIc2V+sp0siPHcq03nM3G2UzGqcqACnOuiMFuXHgXTj4/pvKPazmFnzWVRu8LeMzhwhvXH",
	"+yokcLvNNowQmI6Qq5my3zMu+LAc+31xTXVbsDucie6ycr0YI2tAOfDrHdHOfktlJl88vK8f4Wq2ShP1",
	"aKaTthAh6fV07t4KtApiXZDby0vWkkuFUqb1n62/Wbe80A26wK1l4Bs6lJIN4FHcxlhcaCw09LM5BJ+G",
	"jDTJxwuLCw3lHVS0tZz1cY6tf12PX9cT7ZAXONKNhSPdxbBwX3dDjuTudGNkhAcLFr6QWzjCI7mNQ93a",
	"0J2LV9jHt2pAblt4YEW6BlDoXCwQLSsfI43EhYKbmYxKdE49EKAi3comURAmTzrAu+nbrlkshMR8WAGC",
	"iiNNuxnrJ+fcM1edOc1WBrsc6DbVltyTP8jvcIiv5bbcU3bqyy3s4xvdKtrSYLnzqSV3cCD/gCc4wmMc",
	"4Uu1gNQIPA3dwAHSFLwDNbMWtEfn5T1PzO5qOKuFxHCvfyrx5Pd4pMA2gTD53FL4MXbT8EQ+xzc4tPBQ",
	"oUzu4BB/xgGe4FDuxQP/xp/wBTFfUb3forBwx+mGgtmeHvO/nijn5beZk4/N2nHM9AZxShEbcFFYl73M",
	"OLiwQWP5MubMvmVlzlxx10ihM8ROqmmGsz9q6K5IrIjFRqOWqWWxZqjamQ9IynTGE/JbGmJZb1XxfhQG",
	"fhSz3UeNRlragbgYTsPQZbHi698kZZvsoFPUNnW5VHP4BLZ1t1dDeij/aGotj/BA+ci1xqKBif+OAwv7",
	"qdPjEF+p+WoHdVivlufz+mZcJ+7NJvYqfe5DPJZ7lpZ5X3efR8nYQA0sWPhjvgMun1v4BvsqWMTcL3/Q",
	"Hey9rC3+yJ88Ju2Q6xudyD08Tn95icfYl3+KfVjNGeIxDi25ragtWaZkOlKf8QhP5C4eq+PMQeiRPxmF",
	"zC10RTFfPLyv6VLFOfkdDvAljmarQXfci7HrMxDFvzMwxy4VijN4j0v7WYISc3L1OHElKNcXMuG7HFIx",
	"uj82wLHA+/NwhwN8HW9zbZaTnGAfX+OhRs4odY42UFe0n+Ucomiyz5NxswaLx3z560LuR5orulBR96Bu",
	"Z/0C4zGfgbjbTZsKl2mt5AiznUb4RqUJcXSM5yTPnaK0D8II+ITATzoQiRuB071oWZPnajFFVx7Qe0d6",
	"+gfu63TpQKMuhyUP6j6AE8208m9YJO527+k55xS+UndNF3ansi3DlV4od5JbOIivFidK8V8yjRGBwwQR",
	"QWS42k1dDtAHXg4askpcJSgsXujB5riNI3ylGMiEgfomi8OsAy7EzZGiwj7V3xOFlUcBdtERwEST/9K3",
	"yaFaPwvttokBHHrF0r9zSDUuH1Kl1KJhVddtobLn+aEOklvmkDvCg+TFpP+bdH75fU2/qUa4L/8s9+S2",
	"yqvihAvfmNIadaO7iVRXAIj/x6fGef7MIuuomspqZ/ozCUPZyxhX8jjMoXlD11MZlAXLr8bzriJgpiX1",
	"KjHzr+p5o9xKPSeqBMd088shs2Jx/2pD5FhtJVHSCICKkTLT3nsaLK/6Av8LEGtcCcTmRc0izOpJD0jz",
	"qdFVl+IJ7xRtV6W1t3IX95MySVIzynRXjaC1uuw8SV95Mf6MhfNz5w8XlDNceJ5w4YHuRQoT+a0upw8s",
	"jZVi7DOUPaYZflbpI4+iD9rnCjmDLrFM6q34odg1XFlVgkfAN1LNdLibdAeb9bob2NRtB5FoftL45Brp",
	"rfb+GwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
