// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { HealthzError, HealthzResponse, SearchCandidatesData, SearchCandidatesError, SearchCandidatesResponse, ExplainCandidateData, ExplainCandidateError, ExplainCandidateResponse, CategoryRankingData, CategoryRankingError, CategoryRankingResponse } from './types.gen';

export const client = createClient(createConfig());

export const healthz = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthzResponse, HealthzError, ThrowOnError>({
        ...options,
        url: '/healthz'
    });
};

/**
 * Поиск по банку кандидатов
 */
export const searchCandidates = <ThrowOnError extends boolean = false>(options?: Options<SearchCandidatesData, ThrowOnError>) => {
    return (options?.client ?? client).get<SearchCandidatesResponse, SearchCandidatesError, ThrowOnError>({
        ...options,
        url: '/candidates'
    });
};

/**
 * Объяснение попадания кандидата в выдачу
 */
export const explainCandidate = <ThrowOnError extends boolean = false>(options: Options<ExplainCandidateData, ThrowOnError>) => {
    return (options?.client ?? client).get<ExplainCandidateResponse, ExplainCandidateError, ThrowOnError>({
        ...options,
        url: '/candidates/{userId}/explain'
    });
};

/**
 * Рейтинг внутри категории (для отладки и питча)
 */
export const categoryRanking = <ThrowOnError extends boolean = false>(options: Options<CategoryRankingData, ThrowOnError>) => {
    return (options?.client ?? client).get<CategoryRankingResponse, CategoryRankingError, ThrowOnError>({
        ...options,
        url: '/categories/{categoryId}/ranking'
    });
};