// This file is auto-generated by @hey-api/openapi-ts

export type ExplainResponse = {
    userId?: string;
    finalScore?: number;
    factors?: Array<{
        name?: string;
        weight?: number;
        contribution?: number;
        detail?: string;
    }>;
};

export type SearchHit = {
    userId: string;
    displayName?: string;
    categoryId: string;
    gradeId: string;
    specializationId: string;
    testScore?: number;
    fspAchievementsCount?: number;
    fspBestPlace?: (number) | null;
    fspWeightSum?: number;
    yearsExperience?: (number) | null;
    score: number;
    reasons: Array<(string)>;
};

export type SearchPage = {
    items: Array<SearchHit>;
    total: number;
    limit: number;
    offset: number;
};

export type HealthzResponse = (unknown);

export type HealthzError = unknown;

export type SearchCandidatesData = {
    query?: {
        categoryId?: string;
        gradeId?: string;
        hasFsp?: boolean;
        limit?: number;
        location?: string;
        minYearsExperience?: number;
        offset?: number;
        sort?: 'relevance' | 'testScore' | 'fspWeight';
        specializationId?: string;
        /**
         * Повторяющийся параметр — ID технологий
         */
        stack?: Array<(string)>;
    };
};

export type SearchCandidatesResponse = (SearchPage);

export type SearchCandidatesError = unknown;

export type ExplainCandidateData = {
    path: {
        userId: string;
    };
};

export type ExplainCandidateResponse = (ExplainResponse);

export type ExplainCandidateError = unknown;

export type CategoryRankingData = {
    path: {
        categoryId: string;
    };
    query?: {
        limit?: number;
    };
};

export type CategoryRankingResponse = (Array<SearchHit>);

export type CategoryRankingError = unknown;