worker_processes 1;
events { worker_connections 1024; }

http {
  include /etc/nginx/mime.types;

  upstream auth        { server auth:8080; }
  upstream dict        { server dict:8080; }
  upstream candidate   { server candidate:8080; }
  upstream employer    { server employer:8080; }
  upstream testing     { server testing:8080; }
  upstream interaction { server interaction:8080; }
  upstream search      { server search:8080; }
  upstream frontend    { server frontend:80; }

  server {
    listen 80;

    location /api/auth/        { proxy_pass http://auth/; }
    location /api/dict/        { proxy_pass http://dict/; }
    location /api/candidate/   { proxy_pass http://candidate/; }
    location /api/employer/    { proxy_pass http://employer/; }
    location /api/testing/     { proxy_pass http://testing/; }
    location /api/interaction/ { proxy_pass http://interaction/; }
    location /api/search/      { proxy_pass http://search/; }
    location /specs/           { root /usr/share/nginx/html; }
    location /                 { proxy_pass http://frontend/; }

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}