// Package apiauth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apiauth

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UserRole.
const (
	Admin     UserRole = "admin"
	Candidate UserRole = "candidate"
	Employer  UserRole = "employer"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Candidate:
		return true
	case Employer:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	Active  UserStatus = "active"
	Blocked UserStatus = "blocked"
	Deleted UserStatus = "deleted"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Blocked:
		return true
	case Deleted:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ExternalCallbackRequest defines model for ExternalCallbackRequest.
type ExternalCallbackRequest struct {
	Code        string  `json:"code"`
	RedirectUri *string `json:"redirectUri,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	Role     UserRole            `json:"role"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	NewPassword string `json:"newPassword"`
	Token       string `json:"token"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessExpiresAt  time.Time `json:"accessExpiresAt"`
	AccessToken      string    `json:"accessToken"`
	RefreshExpiresAt time.Time `json:"refreshExpiresAt"`
	RefreshToken     string    `json:"refreshToken"`
	User             User      `json:"user"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Token string `json:"token"`
}

// User defines model for User.
type User struct {
	CreatedAt       time.Time           `json:"createdAt"`
	Email           openapi_types.Email `json:"email"`
	EmailVerifiedAt *time.Time          `json:"emailVerifiedAt,omitempty"`
	Id              openapi_types.UUID  `json:"id"`
	Role            UserRole            `json:"role"`
	Status          UserStatus          `json:"status"`
}

// UserRole defines model for UserRole.
type UserRole string

// UserStatus defines model for UserStatus.
type UserStatus string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ForgotPasswordJSONBody defines parameters for ForgotPassword.
type ForgotPasswordJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// DeleteMeJSONBody defines parameters for DeleteMe.
type DeleteMeJSONBody struct {
	Password string  `json:"password"`
	Reason   *string `json:"reason,omitempty"`
}

// ResendConfirmationJSONBody defines parameters for ResendConfirmation.
type ResendConfirmationJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// ConfirmEmailJSONRequestBody defines body for ConfirmEmail for application/json ContentType.
type ConfirmEmailJSONRequestBody = TokenRequest

// ExternalCallbackJSONRequestBody defines body for ExternalCallback for application/json ContentType.
type ExternalCallbackJSONRequestBody = ExternalCallbackRequest

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody ForgotPasswordJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// DeleteMeJSONRequestBody defines body for DeleteMe for application/json ContentType.
type DeleteMeJSONRequestBody DeleteMeJSONBody

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ResendConfirmationJSONRequestBody defines body for ResendConfirmation for application/json ContentType.
type ResendConfirmationJSONRequestBody ResendConfirmationJSONBody

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ConfirmEmail Подтверждение email по токену из письма
	// (POST /auth/confirm-email)
	ConfirmEmail(c *gin.Context)
	// ExternalCallback Callback внешнего identity-провайдера (задел под Keycloak/OIDC)
	// (POST /auth/external/{provider}/callback)
	ExternalCallback(c *gin.Context, provider string)
	// ForgotPassword Запрос на сброс пароля
	// (POST /auth/forgot-password)
	ForgotPassword(c *gin.Context)
	// Login Логин по email/паролю
	// (POST /auth/login)
	Login(c *gin.Context)
	// Logout Отзыв refresh-токена
	// (POST /auth/logout)
	Logout(c *gin.Context)
	// DeleteMe Удаление аккаунта (soft delete + анонимизация по 152-ФЗ)
	// (DELETE /auth/me)
	DeleteMe(c *gin.Context)
	// Me Текущий пользователь
	// (GET /auth/me)
	Me(c *gin.Context)
	// Refresh Обновление access-токена
	// (POST /auth/refresh)
	Refresh(c *gin.Context)
	// Register Регистрация пользователя
	// (POST /auth/register)
	Register(c *gin.Context)
	// ResendConfirmation Повторная отправка письма с подтверждением
	// (POST /auth/resend-confirmation)
	ResendConfirmation(c *gin.Context)
	// ResetPassword Установка нового пароля по токену
	// (POST /auth/reset-password)
	ResetPassword(c *gin.Context)
	// Healthz Liveness probe
	// (GET /healthz)
	Healthz(c *gin.Context)
	// InternalGetUser Внутренний эндпоинт — получить пользователя по ID (для других сервисов)
	// (GET /internal/users/{userId})
	InternalGetUser(c *gin.Context, userId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ConfirmEmail operation middleware
func (siw *ServerInterfaceWrapper) ConfirmEmail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ConfirmEmail(c)
}

// ExternalCallback operation middleware
func (siw *ServerInterfaceWrapper) ExternalCallback(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", c.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter provider: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExternalCallback(c, provider)
}

// ForgotPassword operation middleware
func (siw *ServerInterfaceWrapper) ForgotPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ForgotPassword(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// DeleteMe operation middleware
func (siw *ServerInterfaceWrapper) DeleteMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteMe(c)
}

// Me operation middleware
func (siw *ServerInterfaceWrapper) Me(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Me(c)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Refresh(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// ResendConfirmation operation middleware
func (siw *ServerInterfaceWrapper) ResendConfirmation(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResendConfirmation(c)
}

// ResetPassword operation middleware
func (siw *ServerInterfaceWrapper) ResetPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResetPassword(c)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// InternalGetUser operation middleware
func (siw *ServerInterfaceWrapper) InternalGetUser(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.InternalGetUser(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.POST(options.BaseURL+"/auth/confirm-email", wrapper.ConfirmEmail)
	router.POST(options.BaseURL+"/auth/resend-confirmation", wrapper.ResendConfirmation)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.Refresh)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.POST(options.BaseURL+"/auth/forgot-password", wrapper.ForgotPassword)
	router.POST(options.BaseURL+"/auth/reset-password", wrapper.ResetPassword)
	router.DELETE(options.BaseURL+"/auth/me", wrapper.DeleteMe)
	router.GET(options.BaseURL+"/auth/me", wrapper.Me)
	router.POST(options.BaseURL+"/auth/external/:provider/callback", wrapper.ExternalCallback)
	router.GET(options.BaseURL+"/internal/users/:userId", wrapper.InternalGetUser)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FndbhvH9X+Vxfz/Fza6EiXFBVzeObLUqlYSQbLbC0MoVrsjaaLlzmZ2qFgRCEhUksawW7dFgAAtErd1",
	"H4BhxZiRTPoVzrxCn6Q4M7PkktolaX0QRa4k7s6cOXN+5+N3zh4Sn1diHtFIJqR8SARNYh4lVP943wvW",
	"6SdVmkj85fNI0kj/68VxyHxPMh6VPk54hM8Sf5dWPPzv/wXdJmXyf6W+6JJ5m5SWhOCC1Go1lwQ08QWL",
	"UQgpE/gWWtCEljqCjnoGPzrwGhrwVh1BVx2TmksWebQdMn8aqvwVutBRn8M5tOFM1Z1b0LG6tOENqug6",
	"tOKx0FEn8AO0jKod9ULVb6Omy1xssSCg0RRU/RrNo+rqBN72LdZST9WfoYO6fMjlMq9GwXQAdLShfoRT",
	"aEEHuqjAo8iryl0u2Gd0ako0oKnq0NV4vYYuNBEegqutAJRvZJQPSSx4TIVkxud9HlD8S594lTikpEyW",
	"Pri3svq7h/ceLH1IXCIPYnyYSMGiHbxghSaJtzO0x7iHFwrqBQeOoDsskVTQ4KKAmksE/aTK8GX5sTm+",
	"L3Szt55vfUx9iQcuPZFURF646IXhlufvZUI0/yoXVBY0YIL68pFg+H6bi4onSZlUBZtMwTy1VvkOiwp1",
	"0QYZOMw8yTFo7CXJp1wEOaoP6ZKK6O3I02udbgua7BZqJsz7h3zPBOzoIwdW5x9nsL5uS1S8J6s02pG7",
	"pDy/cNclFRalv+/mbBU8pOOi6FFCxTquG2tXKy//vgmVa3Zh4aUj+una5S8jJ8PGLHMHDstTWYO35rGc",
	"6Pd8nybJ0pOYCZrckwMwBZ6kM5JVaB5UZmORE7mp31xC8hj/dEk1oWISqC/YK6vz0DnuBUvkXMEeXWji",
	"Qm94JzzzxD+yVx7Kd4J6kgbvYtx3CEb94jdUsG02wRmP050uiaphSDZrLmHBYLatsoBcOXRdkkhPVpNJ",
	"dmyYlcN21mqk99an94S6GaMWAbFu9aVRtaIrhBcFDC2ipcYhP6ACHSqosCya/QtnVMuI8XzJ9lHGVsj9",
	"PV06AxpSSYMcIWgG6lcFkwcbeGHjEFvUE1Tcq2JeSX8tp+b/9W8fEksIUJJ528djV8rYMAwWbXPcP8Q0",
	"/g4t+De0Nfs6gob6EtrqhevAW+jCqapbLvuD5UJtaBnO6DpwDl3cCR3XsTHlOuoYvjdcFyU08F841/Ka",
	"0IGW+srKYAGNJJMHs6gpk5psLG+sOWuhJ9GznP8cfe3gjZ0NKvaZjwbcpyIxSs/Pzs3Oocl5TCMvZqRM",
	"3pudn53TuV7uaqOVkK+VfB5tM1GZ6QVIzE0kY8BpyrYSkLIm5UxUllLnMRH/Pg8Oro3rDaSS2qDvSlGl",
	"+kGmaVmYu3MRLa1gDjYpTb4zN1ekR094KdMOaYerViqeOEBfeDkac32wg5QUzvCNOnGQmeJj9J/n8AYa",
	"iKe3k2jPR4fdxCMMFtQSvtJhLPg+C6iolXxL/oqhGaaJGmPhVaikAo85JAwtg7hjkvJ0FKQHkGEruxm0",
	"+jR3jx74Iff2cljj5s14QxH5ncgx5q7XKTWFyGtCXqljeGuC1rSyTfUFeojxtPnxnjbQNA36WnrxbGLA",
	"RNTtpYYZ0zXrrke3YpienFu6O0THPLdx4Dyw6JU+Wrm/eHuEA25zscPlTJaO5vvcsl64lqGNl3SBS1Lm",
	"XB57sW5N4isLOSn/pe4odaMPXeeWje2mOtYInEIDQenCa2jqivAUGtBSdWdhbsGBU0znukVXT6Gt6uqZ",
	"A11Vd7DcWRPeHk4r3/QnILqzLqoSI6ALsSsrBkw3bTeUuAcawp9yfOKm98Zv6o+FhmD+W8oHTJ3QblXK",
	"4PvH0fjyqhwJML6/GYSHWuvLFmf4B7TUsTpGAmWGWLqOqq90FW1cIWtaSqirXZYMPt7E+pSB4DtVh9fq",
	"GTRTRjbTr9Yja3OFmvsgMb1o/fv6+Qf02jLhiNkIHuHZ7UU9yFB+HDE3yYmaYpLT91VowRtNQfuJDrMi",
	"JrrFjfVlB9qYw87Vifq9rk4d7fpdR51g+tT7O+gG5HKO9Cc4gzNoqBPoqHpPKJI81+bpHHxtJjaJWw9y",
	"n101EUx7VN7PFc/f0fFfZe1uZqcZEyJvSPi2dIyDOz/D94hZR0/C2xrlL03cYuqa//nCDPwLvskhEy7Z",
	"oTn5ycbGDZUBO/bI8WVdRT+HNprM8KFz9TwdFqs60iT1YhqZ55/QgjN1grFikMzT5PmIDGQdurgE2Cz9",
	"P1QDplXnv7VGfJFGSCPThOG76yDk8B18b6RlwshMzyYtIun3gVEY2hU3BeLg0HoiFOenEKb50YA1BLM1",
	"pq6Om22ju46hxgWVCt6YVI+kutEDrHupCQBu+cX4Lb3PlkNekzs+Ks5Eo5wnoVEwYwc2njFdsR/h4sXs",
	"2p90k2ZgujMept530pzJTvoxsWNSSdaBzpDdZKY449xvDI6T9NgDH1xuLB/kfNS5NL1/2WcnDnT72fKa",
	"hm+vMIYsL7GImH8Ntcw2yhcHcfmA7FIvlLufoVa5rOVX9v0VK9tgAPXn+P0BG98bGz922yQU/qMHQ7Zb",
	"Zfs0oknixIJv0YwtjAGsNVhk54/VhIqkdIh/VoJaoXVW7PpfUqkz+ySDRyNz5NhxzIcTM3GcOpEs4GtX",
	"zTt/QefUpQFzR0eTQ/UH6MCpTi9t3eDoRstUDGyo2qo+gswa31+579xKZ1Gn6kid6CL0BVZUTFZNTGW4",
	"L28cqHmt2E9RHLTEKve90AnoPnFJVYT2C0q5VArxxS5PZPnu3N15gjBZwYcp+PqAmtv7bb2vtln7bwAA",
	"AP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
