// Package apiauth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apiauth

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ConsentType.
const (
	ConsentTypePdnProcessing      ConsentType = "pdn_processing"
	ConsentTypeProfilePublication ConsentType = "profile_publication"
)

// Valid indicates whether the value is a known member of the ConsentType enum.
func (e ConsentType) Valid() bool {
	switch e {
	case ConsentTypePdnProcessing:
		return true
	case ConsentTypeProfilePublication:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Admin     UserRole = "admin"
	Candidate UserRole = "candidate"
	Employer  UserRole = "employer"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Candidate:
		return true
	case Employer:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	Active  UserStatus = "active"
	Blocked UserStatus = "blocked"
	Deleted UserStatus = "deleted"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Blocked:
		return true
	case Deleted:
		return true
	default:
		return false
	}
}

// Defines values for GrantConsentParamsType.
const (
	GrantConsentParamsTypePdnProcessing      GrantConsentParamsType = "pdn_processing"
	GrantConsentParamsTypeProfilePublication GrantConsentParamsType = "profile_publication"
)

// Valid indicates whether the value is a known member of the GrantConsentParamsType enum.
func (e GrantConsentParamsType) Valid() bool {
	switch e {
	case GrantConsentParamsTypePdnProcessing:
		return true
	case GrantConsentParamsTypeProfilePublication:
		return true
	default:
		return false
	}
}

// Defines values for RevokeConsentParamsType.
const (
	RevokeConsentParamsTypePdnProcessing      RevokeConsentParamsType = "pdn_processing"
	RevokeConsentParamsTypeProfilePublication RevokeConsentParamsType = "profile_publication"
)

// Valid indicates whether the value is a known member of the RevokeConsentParamsType enum.
func (e RevokeConsentParamsType) Valid() bool {
	switch e {
	case RevokeConsentParamsTypePdnProcessing:
		return true
	case RevokeConsentParamsTypeProfilePublication:
		return true
	default:
		return false
	}
}

// Consent defines model for Consent.
type Consent struct {
	GrantedAt time.Time          `json:"grantedAt"`
	Id        openapi_types.UUID `json:"id"`
	RevokedAt *time.Time         `json:"revokedAt,omitempty"`
	Type      ConsentType        `json:"type"`
	Version   string             `json:"version"`
}

// ConsentType defines model for Consent.Type.
type ConsentType string

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ExternalCallbackRequest defines model for ExternalCallbackRequest.
type ExternalCallbackRequest struct {
	Code        string  `json:"code"`
	RedirectUri *string `json:"redirectUri,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	ConsentPdn                bool                `json:"consentPdn"`
	ConsentProfilePublication bool                `json:"consentProfilePublication"`
	Email                     openapi_types.Email `json:"email"`
	Password                  string              `json:"password"`
	Role                      UserRole            `json:"role"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	NewPassword string `json:"newPassword"`
	Token       string `json:"token"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessExpiresAt  time.Time `json:"accessExpiresAt"`
	AccessToken      string    `json:"accessToken"`
	RefreshExpiresAt time.Time `json:"refreshExpiresAt"`
	RefreshToken     string    `json:"refreshToken"`
	User             User      `json:"user"`
}

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Token string `json:"token"`
}

// User defines model for User.
type User struct {
	CreatedAt       time.Time           `json:"createdAt"`
	Email           openapi_types.Email `json:"email"`
	EmailVerifiedAt *time.Time          `json:"emailVerifiedAt,omitempty"`
	Id              openapi_types.UUID  `json:"id"`
	Role            UserRole            `json:"role"`
	Status          UserStatus          `json:"status"`
}

// UserRole defines model for UserRole.
type UserRole string

// UserStatus defines model for UserStatus.
type UserStatus string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GrantConsentParamsType defines parameters for GrantConsent.
type GrantConsentParamsType string

// RevokeConsentParamsType defines parameters for RevokeConsent.
type RevokeConsentParamsType string

// ForgotPasswordJSONBody defines parameters for ForgotPassword.
type ForgotPasswordJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// DeleteMeJSONBody defines parameters for DeleteMe.
type DeleteMeJSONBody struct {
	Password string  `json:"password"`
	Reason   *string `json:"reason,omitempty"`
}

// ResendConfirmationJSONBody defines parameters for ResendConfirmation.
type ResendConfirmationJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// ConfirmEmailJSONRequestBody defines body for ConfirmEmail for application/json ContentType.
type ConfirmEmailJSONRequestBody = TokenRequest

// ExternalCallbackJSONRequestBody defines body for ExternalCallback for application/json ContentType.
type ExternalCallbackJSONRequestBody = ExternalCallbackRequest

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody ForgotPasswordJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// DeleteMeJSONRequestBody defines body for DeleteMe for application/json ContentType.
type DeleteMeJSONRequestBody DeleteMeJSONBody

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ResendConfirmationJSONRequestBody defines body for ResendConfirmation for application/json ContentType.
type ResendConfirmationJSONRequestBody ResendConfirmationJSONBody

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ConfirmEmail Подтверждение email по токену из письма
	// (POST /auth/confirm-email)
	ConfirmEmail(c *gin.Context)

	// (GET /auth/consents)
	ListConsents(c *gin.Context)

	// (POST /auth/consents/{type}/grant)
	GrantConsent(c *gin.Context, pType GrantConsentParamsType)

	// (POST /auth/consents/{type}/revoke)
	RevokeConsent(c *gin.Context, pType RevokeConsentParamsType)
	// ExternalCallback Callback внешнего identity-провайдера (задел под Keycloak/OIDC)
	// (POST /auth/external/{provider}/callback)
	ExternalCallback(c *gin.Context, provider string)
	// ForgotPassword Запрос на сброс пароля
	// (POST /auth/forgot-password)
	ForgotPassword(c *gin.Context)
	// Login Логин по email/паролю
	// (POST /auth/login)
	Login(c *gin.Context)
	// Logout Отзыв refresh-токена
	// (POST /auth/logout)
	Logout(c *gin.Context)
	// DeleteMe Удаление аккаунта (soft delete + анонимизация по 152-ФЗ)
	// (DELETE /auth/me)
	DeleteMe(c *gin.Context)
	// Me Текущий пользователь
	// (GET /auth/me)
	Me(c *gin.Context)
	// Refresh Обновление access-токена
	// (POST /auth/refresh)
	Refresh(c *gin.Context)
	// Register Регистрация пользователя
	// (POST /auth/register)
	Register(c *gin.Context)
	// ResendConfirmation Повторная отправка письма с подтверждением
	// (POST /auth/resend-confirmation)
	ResendConfirmation(c *gin.Context)
	// ResetPassword Установка нового пароля по токену
	// (POST /auth/reset-password)
	ResetPassword(c *gin.Context)
	// Healthz Liveness probe
	// (GET /healthz)
	Healthz(c *gin.Context)
	// InternalGetUser Внутренний эндпоинт — получить пользователя по ID (для других сервисов)
	// (GET /internal/users/{userId})
	InternalGetUser(c *gin.Context, userId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ConfirmEmail operation middleware
func (siw *ServerInterfaceWrapper) ConfirmEmail(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ConfirmEmail(c)
}

// ListConsents operation middleware
func (siw *ServerInterfaceWrapper) ListConsents(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListConsents(c)
}

// GrantConsent operation middleware
func (siw *ServerInterfaceWrapper) GrantConsent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "type" -------------
	var pType GrantConsentParamsType

	err = runtime.BindStyledParameterWithOptions("simple", "type", c.Param("type"), &pType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter type: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GrantConsent(c, pType)
}

// RevokeConsent operation middleware
func (siw *ServerInterfaceWrapper) RevokeConsent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "type" -------------
	var pType RevokeConsentParamsType

	err = runtime.BindStyledParameterWithOptions("simple", "type", c.Param("type"), &pType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter type: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeConsent(c, pType)
}

// ExternalCallback operation middleware
func (siw *ServerInterfaceWrapper) ExternalCallback(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "provider" -------------
	var provider string

	err = runtime.BindStyledParameterWithOptions("simple", "provider", c.Param("provider"), &provider, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter provider: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExternalCallback(c, provider)
}

// ForgotPassword operation middleware
func (siw *ServerInterfaceWrapper) ForgotPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ForgotPassword(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// DeleteMe operation middleware
func (siw *ServerInterfaceWrapper) DeleteMe(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteMe(c)
}

// Me operation middleware
func (siw *ServerInterfaceWrapper) Me(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Me(c)
}

// Refresh operation middleware
func (siw *ServerInterfaceWrapper) Refresh(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Refresh(c)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Register(c)
}

// ResendConfirmation operation middleware
func (siw *ServerInterfaceWrapper) ResendConfirmation(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResendConfirmation(c)
}

// ResetPassword operation middleware
func (siw *ServerInterfaceWrapper) ResetPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ResetPassword(c)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// InternalGetUser operation middleware
func (siw *ServerInterfaceWrapper) InternalGetUser(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.InternalGetUser(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register)
	router.POST(options.BaseURL+"/auth/confirm-email", wrapper.ConfirmEmail)
	router.POST(options.BaseURL+"/auth/resend-confirmation", wrapper.ResendConfirmation)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.Refresh)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.POST(options.BaseURL+"/auth/forgot-password", wrapper.ForgotPassword)
	router.POST(options.BaseURL+"/auth/reset-password", wrapper.ResetPassword)
	router.DELETE(options.BaseURL+"/auth/me", wrapper.DeleteMe)
	router.GET(options.BaseURL+"/auth/me", wrapper.Me)
	router.POST(options.BaseURL+"/auth/external/:provider/callback", wrapper.ExternalCallback)
	router.GET(options.BaseURL+"/internal/users/:userId", wrapper.InternalGetUser)
	router.GET(options.BaseURL+"/auth/consents", wrapper.ListConsents)
	router.POST(options.BaseURL+"/auth/consents/:type/grant", wrapper.GrantConsent)
	router.POST(options.BaseURL+"/auth/consents/:type/revoke", wrapper.RevokeConsent)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FrdbhvHFX6VxbQXNroyKcUFXN45spWqVhJBttsLQzBWuyNqouXOZnaoWBEIWFSSxrBbt0WAAC0St3Uf",
	"gFHFmJFM+hXOvEKfpDgzu+SSmiUpWlKbXInkzJw9833nf7VHfF6LeUQjmZDKHhE0iXmUUP3lXS9Yox/X",
	"aSLxm88jSSP90YvjkPmeZDwqfZTwCH9L/C1a8/DTzwXdJBXys9JAdMmsJqXbQnBBGo2GSwKa+ILFKIRU",
	"CHwDbTiEtnoMXfUUfnDgFbTgjXoMPbVPGi5Z5NFmyPzLUOWv0IOu+gxOoAPHqulcgW6qSwdeo4quQ2se",
	"Cx11AN9D26jaVc9V8ypqusTFBgsCGl2Cql8hPKqpDuDNALG2eqL+DF3U5QMul3g9Ci6HQEcD9QMcQRu6",
	"0EMF7kdeXW5xwT6ll6ZECw5VE3qar1fQg0Okh+DuVADKX0QzN4rEgsdUSGasviq8SNLgpl7a5KLmSVIh",
	"gSfpnGQ1Slwid2NKKiSRgkVVvCQLhvbW6yywbRN0h29PIflBdsYlUT0MyXojW9kjNKrXcEccRA9jwX2a",
	"JGZnLPgmC+nDuL6RoUrWLUrsUJEwA/bImtbw4zoTyNQDMrjD4JCbQ2cgnG98RH2Jwg0xpyD1eWCUf+TV",
	"4hCP3H7/5vLKw3s379z+wIZUjSaJVx05Y3zOCwX1gl1H0CpLJEVl3Qk30Y8fCLUq/khSEXnhoheGG56/",
	"nYt79qtYyA2YoL68L9iwMQg2nYI2tVZ4lUWFumhAhh5mfrEAGntJ8gkXwWTaMxH9Eza91uimoMlWoWbC",
	"rN/j23QKSxvabX+c4XoMK9qZV4P80zY4D6kXoYBs3fjIas5FrNvPB1iXCB7SSbHsfkLFGu6bSEQqz83f",
	"dtzV7EgmVK6mEgvhjOgnq7l71bxHKzSqyi1SmV+44ZIai7LvNyyQyOlYN9vcoYfZVNZmseoxS1zxfIx/",
	"tx/FTNDkLAHbHCwyTzezyBkkT7B8l9QTKqaxiVN45XUeeY57CgnLFdJHF0JcaA1n4tMm/n565RGfFdQ7",
	"Y549g1/qhd9SwTbZjBl32qR+Jh93SSI9WU+mOXHX7LTm5ezeaURIhbo5UIuIWEv1zQoJ34sChohoqXHI",
	"d6lAgwpqzF5A5FTLifF8yXZQxkbI/W2dlAMaUkkDixCEgfp1weTuXbywMYgN6gkqbtYxrmTfljL4f/O7",
	"eySt33Sw1qsDPrakjE1ByKJNjudHCsO/Qxv+DR1dLD+GlvoCOuq568Ab6MGRaqatx/dp6dqBtinxXQdO",
	"oIcnoes6qU+5jtqH70xrghJa+BFOtLxD6EJbfZnKYAGNJJO711BTJnUZs3R31VkNPYmW5fzn8VcO3ti5",
	"S8UO8/O1VoXMXytfKyPkPKaRFzNSIe9cm79W1klBbmnQSlhel3webTJRm+s7SMyNJ6PD6WywHJCK7qGY",
	"qN3OjMd4/Ls82D230nwolDSGbVeKOtU/5HrMhfL102xpBS3cZF3N9XK5SI++8FKue9UGV6/VPLGLtvBi",
	"POf6wQ52EHCMK+rAwUYCf0b7eQavoYV8etVEWz4a7Do+os9FkrXTVWphYYUlcjHbdAqO8pmoYJLWJgaT",
	"rNXptxHEE8LbtTVQH94x+M5Pxneos8u7NKk8GHbmB+sNCz6lPVSmUdIdRbHNvofL2Q3Q8IVXo5KKRD+G",
	"odLoDBi5PR0a0pZl2OzcHGZv2UI11qcx4QzIGQx1NhhNc1mM45pe/3ECOT0qNO3jSnux4DssoKJR8tOe",
	"rhib0e5vKniyB4yHqN+9btNdP+TeNinA4fxDcVFPO1VULp9vRtD1u21g81LtwxuTMc3Y71B9juH5LcJQ",
	"P9BnF89nZawCev28PGcmjHpCpMdWWBs4V/QkDbPCSZqEnDspe6UPl28tXh0T/Te5qHI5l28L7Ta3pDeu",
	"5pq7GU1gxpmAtds8XTROYysLlnrrhZ6+6aEo9JwraWI9VPuagSNoISk9eAWHuhx7Ai1oq6azUF5w4Ahr",
	"KT3OVE+go5rqqQM91XQw3qQQXh3N6V8PpsV6CllUoo2hLuRVFhUTpmcxF1Q1Dc15fsr+iYfemXxoMEIf",
	"oflvWTFuijRtVqUcv38czy+vy7EE4/rFMDwyMZu1MoZ/QFvtq33sXszAXxex6ktdwrYuqHgbouBb1YRX",
	"6ikcZu3Q3KBUHlsY16i5D3aFp9G/pX9/n55bJBw/maNekp/+nR4AjMTHMeNQi9cUdxgDW4U2vNb93yDQ",
	"YVTEQLd4d23JgQ7GsBN1oH6vs1NXm37PUQcYPvX5LpoBmc2Q/gTHcAwtdQBd1ewLxQ7LTeO0hd80EpvA",
	"rV96PX3bQHDZrxUHseLZGQ3/ZR53854pByHWDQnflI4xcOcXuI6cdfVbw45m+Qvjtxi65n+5MAf/gq8t",
	"xYRr7xtT37igNJDOHC22rLPoZ9BByEw9dKKeZS/WVBPLJPX8MiLPP6ENx+oAfcUwadPk2ZgIlBr0uCbJ",
	"bPj/yQGXlee/SUF8nnlIKzcBwbXzKMjhW/jOSMu5kRldT5tEstd+4zhMd1wUicPvoqZicf4S3NTuDZhD",
	"MFpj6Oq6+RlWzzGlcUGmgtcm1GNR3eoT1ptpqoFHfjX5SP9fPEasxjq7LY5E44wnoVEwl05L+y8Ai+wI",
	"Ny/m9/6kmzRD0/XJNPX/p8QyVs3+8aJrQknegI6xusmNUCeZ3wQep+mxh952Xlg8sLxRnbm8fzGoThzo",
	"DaLlOU2+X6IPpXVJyoj5aErLfKN8egpuJ2SLeqHc+rRw2v3rdP0tM9uwAw1eog0GbHx7ov+kx6Yp4bOx",
	"Yx+7FbZDI5okTiz4Bs1hYQBI0WBROn+sJ1QkpT38sxw0CtFZTve/R6WO7NMMHo3MsWPHCW8tLZPX8v8s",
	"Q7113PkLGqdODRg7uro4VH+ALhzp8NLRDY5utEzGwIaqo5pjillj+8u3nCvZLOpIPVYHOgl9jhkVg9Uh",
	"hjI8ZxsH6rpW7GQsDiOxwn0vdAK6Q1xSF2H6+rJSKoW4sMUTWblRvjFPkKZU8F5Gvn5Aw+1/T62vsd74",
	"bwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
