// This file is auto-generated by @hey-api/openapi-ts

export const StartSessionRequestSchema = {
    type: 'object',
    properties: {
        targetCategoryId: {
            type: 'string',
            format: 'uuid'
        }
    },
    required: ['targetCategoryId']
} as const;

export const SessionSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        targetCategoryId: {
            type: 'string',
            format: 'uuid'
        },
        status: {
            type: 'string',
            enum: ['in_progress', 'submitted', 'evaluated', 'expired', 'cancelled']
        },
        startedAt: {
            type: 'string',
            format: 'date-time'
        },
        finishedAt: {
            type: ['string', 'null'],
            format: 'date-time'
        }
    },
    required: ['id', 'targetCategoryId', 'status', 'startedAt']
} as const;

export const SessionWithItemsSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/Session'
        },
        {
            type: 'object',
            properties: {
                items: {
                    type: 'array',
                    items: {
                        '$ref': '#/components/schemas/SessionItem'
                    }
                }
            }
        }
    ]
} as const;

export const SessionItemSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        position: {
            type: 'integer'
        },
        type: {
            type: 'string',
            enum: ['single_choice', 'multi_choice', 'code', 'text', 'sql', 'regex']
        },
        topic: {
            type: 'string'
        },
        body: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: ['pending', 'answered', 'skipped']
        }
    },
    required: ['id', 'position', 'type', 'topic', 'body', 'status']
} as const;

export const AnswerInputSchema = {
    type: 'object',
    properties: {
        itemId: {
            type: 'string',
            format: 'uuid'
        },
        answer: {
            description: 'Произвольный JSON-ответ'
        },
        skipped: {
            type: 'boolean',
            default: false
        }
    },
    required: ['itemId']
} as const;

export const SessionResultSchema = {
    type: 'object',
    properties: {
        sessionId: {
            type: 'string',
            format: 'uuid'
        },
        score: {
            type: 'number'
        },
        abilityEstimate: {
            type: 'number'
        },
        resultingGradeId: {
            type: 'string',
            format: 'uuid'
        },
        resultingCategoryId: {
            type: 'string',
            format: 'uuid'
        },
        decision: {
            type: 'string',
            enum: ['confirmed', 'downgrade_offered', 'upgrade_offered']
        },
        explanation: {
            type: 'string'
        }
    },
    required: ['sessionId', 'score', 'resultingGradeId', 'resultingCategoryId', 'decision']
} as const;

export const QuestionnaireInputSchema = {
    type: 'object',
    properties: {
        specializationId: {
            type: 'string',
            format: 'uuid'
        },
        claimedGradeId: {
            type: 'string',
            format: 'uuid'
        },
        yearsExperience: {
            type: 'number'
        },
        technologies: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['specializationId', 'claimedGradeId']
} as const;

export const QuestionnaireResultSchema = {
    type: 'object',
    properties: {
        targetCategoryId: {
            type: 'string',
            format: 'uuid'
        },
        recommendedGradeId: {
            type: 'string',
            format: 'uuid'
        },
        canStartTest: {
            type: 'boolean'
        },
        cooldownRemainingDays: {
            type: 'integer'
        },
        canChangeAt: {
            type: ['string', 'null'],
            format: 'date-time'
        },
        message: {
            type: 'string'
        }
    },
    required: ['targetCategoryId', 'canStartTest', 'message']
} as const;

export const QuestionnaireStateSchema = {
    type: 'object',
    properties: {
        state: {
            type: 'object'
        },
        canChangeAt: {
            type: ['string', 'null'],
            format: 'date-time'
        },
        canStartTest: {
            type: 'boolean'
        }
    },
    required: ['canStartTest']
} as const;

export const GradeChangeSchema = {
    type: 'object',
    properties: {
        fromGradeId: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        toGradeId: {
            type: 'string',
            format: 'uuid'
        },
        reason: {
            type: 'string'
        },
        changedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const PeriodicTaskInputSchema = {
    type: 'object',
    properties: {
        categoryId: {
            type: 'string',
            format: 'uuid'
        },
        title: {
            type: 'string'
        },
        body: {
            type: 'string'
        }
    },
    required: ['categoryId', 'title', 'body']
} as const;

export const PeriodicTaskSchema = {
    allOf: [
        {
            '$ref': '#/components/schemas/PeriodicTaskInput'
        },
        {
            type: 'object',
            properties: {
                id: {
                    type: 'string',
                    format: 'uuid'
                },
                createdAt: {
                    type: 'string',
                    format: 'date-time'
                }
            }
        }
    ]
} as const;

export const CandidateFSPProfileSchema = {
    type: 'object',
    properties: {
        userId: {
            type: 'string',
            format: 'uuid'
        },
        hasFsp: {
            type: 'boolean'
        },
        fspMemberId: {
            type: ['string', 'null']
        },
        fullName: {
            type: ['string', 'null']
        },
        sportsRank: {
            type: ['string', 'null']
        },
        fspRating: {
            type: 'integer'
        },
        region: {
            type: ['string', 'null']
        },
        discipline: {
            type: ['string', 'null']
        },
        fspScore: {
            type: 'number'
        },
        fspWeightSum: {
            type: 'integer'
        },
        achievementsCount: {
            type: 'integer'
        },
        bestPlace: {
            type: ['integer', 'null']
        },
        verificationSource: {
            type: 'string'
        },
        linkedAt: {
            type: ['string', 'null'],
            format: 'date-time'
        },
        explanation: {
            type: 'string'
        },
        achievements: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/FSPAchievement'
            }
        }
    },
    required: ['userId', 'hasFsp', 'fspRating', 'fspScore', 'fspWeightSum', 'achievementsCount', 'verificationSource', 'explanation', 'achievements']
} as const;

export const LinkFSPRequestSchema = {
    type: 'object',
    properties: {
        fspMemberId: {
            type: 'string'
        }
    },
    required: ['fspMemberId']
} as const;

export const FSPAchievementSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        externalId: {
            type: ['string', 'null']
        },
        eventName: {
            type: 'string'
        },
        eventDate: {
            type: ['string', 'null']
        },
        place: {
            type: ['integer', 'null']
        },
        category: {
            type: 'string'
        },
        score: {
            type: ['number', 'null']
        },
        weight: {
            type: 'integer'
        },
        badge: {
            type: ['string', 'null']
        },
        description: {
            type: ['string', 'null']
        }
    },
    required: ['eventName', 'category', 'weight']
} as const;

export const FSPRegistryMemberSchema = {
    type: 'object',
    properties: {
        fspId: {
            type: 'string'
        },
        fullName: {
            type: 'string'
        },
        sportsRank: {
            type: 'string'
        },
        rating: {
            type: 'integer'
        },
        region: {
            type: 'string'
        },
        discipline: {
            type: 'string'
        },
        status: {
            type: 'string'
        },
        verified: {
            type: 'boolean'
        },
        achievements: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/FSPAchievement'
            }
        }
    },
    required: ['fspId', 'fullName', 'sportsRank', 'rating', 'region', 'verified']
} as const;

export const FSPVerificationRequestSchema = {
    type: 'object',
    properties: {
        fspId: {
            type: 'string'
        },
        fullName: {
            type: 'string'
        },
        certificate: {
            type: 'string'
        }
    },
    required: ['fspId']
} as const;

export const FSPVerificationResultSchema = {
    type: 'object',
    properties: {
        isValid: {
            type: 'boolean'
        },
        message: {
            type: 'string'
        },
        verifiedAt: {
            type: 'string',
            format: 'date-time'
        },
        member: {
            '$ref': '#/components/schemas/FSPRegistryMember'
        }
    },
    required: ['isValid', 'message', 'verifiedAt']
} as const;