// This file is auto-generated by @hey-api/openapi-ts

export type AnswerInput = {
    itemId: string;
    /**
     * Произвольный JSON-ответ
     */
    answer?: unknown;
    skipped?: boolean;
};

export type CandidateFSPProfile = {
    userId: string;
    hasFsp: boolean;
    fspMemberId?: (string) | null;
    fullName?: (string) | null;
    sportsRank?: (string) | null;
    fspRating: number;
    region?: (string) | null;
    discipline?: (string) | null;
    fspScore: number;
    fspWeightSum: number;
    achievementsCount: number;
    bestPlace?: (number) | null;
    verificationSource: string;
    linkedAt?: (string) | null;
    explanation: string;
    achievements: Array<FSPAchievement>;
};

export type FSPAchievement = {
    id?: string;
    externalId?: (string) | null;
    eventName: string;
    eventDate?: (string) | null;
    place?: (number) | null;
    category: string;
    score?: (number) | null;
    weight: number;
    badge?: (string) | null;
    description?: (string) | null;
};

export type FSPRegistryMember = {
    fspId: string;
    fullName: string;
    sportsRank: string;
    rating: number;
    region: string;
    discipline?: string;
    status?: string;
    verified: boolean;
    achievements?: Array<FSPAchievement>;
};

export type FSPVerificationRequest = {
    fspId: string;
    fullName?: string;
    certificate?: string;
};

export type FSPVerificationResult = {
    isValid: boolean;
    message: string;
    verifiedAt: string;
    member?: FSPRegistryMember;
};

export type GradeChange = {
    fromGradeId?: (string) | null;
    toGradeId?: string;
    reason?: string;
    changedAt?: string;
};

export type LinkFSPRequest = {
    fspMemberId: string;
};

export type PeriodicTask = PeriodicTaskInput & {
    id?: string;
    createdAt?: string;
};

export type PeriodicTaskInput = {
    categoryId: string;
    title: string;
    body: string;
};

export type QuestionnaireInput = {
    specializationId: string;
    claimedGradeId: string;
    yearsExperience?: number;
    technologies?: Array<(string)>;
};

export type QuestionnaireResult = {
    targetCategoryId: string;
    recommendedGradeId?: string;
    canStartTest: boolean;
    cooldownRemainingDays?: number;
    canChangeAt?: (string) | null;
    message: string;
};

export type QuestionnaireState = {
    state?: {
        [key: string]: unknown;
    };
    canChangeAt?: (string) | null;
    canStartTest: boolean;
};

export type Session = {
    id: string;
    targetCategoryId: string;
    status: 'in_progress' | 'submitted' | 'evaluated' | 'expired' | 'cancelled';
    startedAt: string;
    finishedAt?: (string) | null;
};

export type status = 'in_progress' | 'submitted' | 'evaluated' | 'expired' | 'cancelled';

export type SessionItem = {
    id: string;
    position: number;
    type: 'single_choice' | 'multi_choice' | 'code' | 'text' | 'sql' | 'regex';
    topic: string;
    body: string;
    status: 'pending' | 'answered' | 'skipped';
};

export type type = 'single_choice' | 'multi_choice' | 'code' | 'text' | 'sql' | 'regex';

export type status2 = 'pending' | 'answered' | 'skipped';

export type SessionResult = {
    sessionId: string;
    score: number;
    abilityEstimate?: number;
    resultingGradeId: string;
    resultingCategoryId: string;
    decision: 'confirmed' | 'downgrade_offered' | 'upgrade_offered';
    explanation?: string;
};

export type decision = 'confirmed' | 'downgrade_offered' | 'upgrade_offered';

export type SessionWithItems = Session & {
    items?: Array<SessionItem>;
};

export type StartSessionRequest = {
    targetCategoryId: string;
};

export type HealthzResponse = (unknown);

export type HealthzError = unknown;

export type StartSessionData = {
    body: StartSessionRequest;
};

export type StartSessionResponse = (Session);

export type StartSessionError = unknown;

export type ListMySessionsResponse = (Array<Session>);

export type ListMySessionsError = unknown;

export type GetSessionData = {
    path: {
        id: string;
    };
};

export type GetSessionResponse = (SessionWithItems);

export type GetSessionError = unknown;

export type AnswerItemData = {
    body: AnswerInput;
    path: {
        id: string;
    };
};

export type AnswerItemResponse = (unknown);

export type AnswerItemError = (unknown);

export type SubmitSessionData = {
    path: {
        id: string;
    };
};

export type SubmitSessionResponse = (SessionResult);

export type SubmitSessionError = unknown;

export type ListGradeChangesResponse = ({
    canChangeAt?: (string) | null;
    changes?: Array<GradeChange>;
});

export type ListGradeChangesError = unknown;

export type SubmitQuestionnaireData = {
    body: QuestionnaireInput;
};

export type SubmitQuestionnaireResponse = (QuestionnaireResult);

export type SubmitQuestionnaireError = unknown;

export type GetQuestionnaireStateResponse = (QuestionnaireState);

export type GetQuestionnaireStateError = unknown;

export type ListPeriodicTasksResponse = (Array<PeriodicTask>);

export type ListPeriodicTasksError = unknown;

export type SubmitPeriodicTaskData = {
    body: {
        answer: string;
    };
    path: {
        id: string;
    };
};

export type SubmitPeriodicTaskResponse = (unknown);

export type SubmitPeriodicTaskError = unknown;

export type CreatePeriodicTaskData = {
    body: PeriodicTaskInput;
};

export type CreatePeriodicTaskResponse = (PeriodicTask);

export type CreatePeriodicTaskError = unknown;

export type InternalGetCategoryData = {
    path: {
        userId: string;
    };
};

export type InternalGetCategoryResponse = ({
    categoryId?: string;
    gradeId?: string;
    testScore?: number;
});

export type InternalGetCategoryError = unknown;

export type GetMyFspResponse = (CandidateFSPProfile);

export type GetMyFspError = unknown;

export type LinkFspData = {
    body: LinkFSPRequest;
};

export type LinkFspResponse = (CandidateFSPProfile);

export type LinkFspError = (unknown);

export type UnlinkFspResponse = (CandidateFSPProfile);

export type UnlinkFspError = unknown;

export type SyncKeycloakFspResponse = (CandidateFSPProfile);

export type SyncKeycloakFspError = unknown;

export type InternalGetCandidateFspData = {
    path: {
        userId: string;
    };
};

export type InternalGetCandidateFspResponse = (CandidateFSPProfile);

export type InternalGetCandidateFspError = unknown;

export type SearchFspRegistryMembersData = {
    query?: {
        limit?: number;
        offset?: number;
        q?: string;
        rank?: string;
        region?: string;
    };
};

export type SearchFspRegistryMembersResponse = ({
    total?: number;
    members?: Array<FSPRegistryMember>;
});

export type SearchFspRegistryMembersError = unknown;

export type GetFspRegistryMemberData = {
    path: {
        fspId: string;
    };
};

export type GetFspRegistryMemberResponse = (FSPRegistryMember);

export type GetFspRegistryMemberError = (unknown);

export type VerifyFspMemberData = {
    body: FSPVerificationRequest;
};

export type VerifyFspMemberResponse = (FSPVerificationResult);

export type VerifyFspMemberError = unknown;