// Package apidict provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apidict

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Category defines model for Category.
type Category struct {
	GradeId          openapi_types.UUID `json:"gradeId"`
	Id               openapi_types.UUID `json:"id"`
	IsActive         bool               `json:"isActive"`
	Slug             string             `json:"slug"`
	SpecializationId openapi_types.UUID `json:"specializationId"`
}

// Grade defines model for Grade.
type Grade struct {
	Code string             `json:"code"`
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Rank int                `json:"rank"`
}

// Industry defines model for Industry.
type Industry struct {
	Code string             `json:"code"`
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// Snapshot defines model for Snapshot.
type Snapshot struct {
	Categories      *[]Category       `json:"categories,omitempty"`
	Grades          *[]Grade          `json:"grades,omitempty"`
	Industries      *[]Industry       `json:"industries,omitempty"`
	Specializations *[]Specialization `json:"specializations,omitempty"`
	Technologies    *[]Technology     `json:"technologies,omitempty"`
	Version         *time.Time        `json:"version,omitempty"`
}

// Specialization defines model for Specialization.
type Specialization struct {
	Code        string             `json:"code"`
	Description *string            `json:"description,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	IndustryId  openapi_types.UUID `json:"industryId"`
	IsActive    bool               `json:"isActive"`
	Name        string             `json:"name"`
}

// Technology defines model for Technology.
type Technology struct {
	Category *string            `json:"category,omitempty"`
	Code     string             `json:"code"`
	Id       openapi_types.UUID `json:"id"`
	Name     string             `json:"name"`
}

// ListCategoriesParams defines parameters for ListCategories.
type ListCategoriesParams struct {
	SpecializationId *openapi_types.UUID `form:"specializationId,omitempty" json:"specializationId,omitempty"`
	GradeId          *openapi_types.UUID `form:"gradeId,omitempty" json:"gradeId,omitempty"`
}

// ListSpecializationsParams defines parameters for ListSpecializations.
type ListSpecializationsParams struct {
	IndustryId *openapi_types.UUID `form:"industryId,omitempty" json:"industryId,omitempty"`
	ActiveOnly *bool               `form:"activeOnly,omitempty" json:"activeOnly,omitempty"`
}

// ListTechnologiesParams defines parameters for ListTechnologies.
type ListTechnologiesParams struct {
	Category *string `form:"category,omitempty" json:"category,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /categories)
	ListCategories(c *gin.Context, params ListCategoriesParams)

	// (GET /categories/{id})
	GetCategory(c *gin.Context, id openapi_types.UUID)

	// (GET /grades)
	ListGrades(c *gin.Context)

	// (GET /healthz)
	Healthz(c *gin.Context)

	// (GET /industries)
	ListIndustries(c *gin.Context)

	// (GET /internal/dictionaries/snapshot)
	Snapshot(c *gin.Context)

	// (GET /specializations)
	ListSpecializations(c *gin.Context, params ListSpecializationsParams)

	// (GET /technologies)
	ListTechnologies(c *gin.Context, params ListTechnologiesParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListCategories operation middleware
func (siw *ServerInterfaceWrapper) ListCategories(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCategoriesParams

	// ------------- Optional query parameter "specializationId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "specializationId", c.Request.URL.Query(), &params.SpecializationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter specializationId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "gradeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "gradeId", c.Request.URL.Query(), &params.GradeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gradeId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCategories(c, params)
}

// GetCategory operation middleware
func (siw *ServerInterfaceWrapper) GetCategory(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCategory(c, id)
}

// ListGrades operation middleware
func (siw *ServerInterfaceWrapper) ListGrades(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGrades(c)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// ListIndustries operation middleware
func (siw *ServerInterfaceWrapper) ListIndustries(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListIndustries(c)
}

// Snapshot operation middleware
func (siw *ServerInterfaceWrapper) Snapshot(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Snapshot(c)
}

// ListSpecializations operation middleware
func (siw *ServerInterfaceWrapper) ListSpecializations(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSpecializationsParams

	// ------------- Optional query parameter "industryId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "industryId", c.Request.URL.Query(), &params.IndustryId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter industryId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "activeOnly" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "activeOnly", c.Request.URL.Query(), &params.ActiveOnly, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter activeOnly: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListSpecializations(c, params)
}

// ListTechnologies operation middleware
func (siw *ServerInterfaceWrapper) ListTechnologies(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTechnologiesParams

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", c.Request.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter category: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTechnologies(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/industries", wrapper.ListIndustries)
	router.GET(options.BaseURL+"/specializations", wrapper.ListSpecializations)
	router.GET(options.BaseURL+"/grades", wrapper.ListGrades)
	router.GET(options.BaseURL+"/categories", wrapper.ListCategories)
	router.GET(options.BaseURL+"/categories/:id", wrapper.GetCategory)
	router.GET(options.BaseURL+"/technologies", wrapper.ListTechnologies)
	router.GET(options.BaseURL+"/internal/dictionaries/snapshot", wrapper.Snapshot)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFfdahvHF38VMf//RQuqJae5CHtXUuqaFhJQ7owpk91jaZLd2c3MrKliFmSXtIVe5KZXhVL6BsK2qGzV",
	"yiuceYU+SZnRfkkeWSvSuL1bcc78zjm/86kT4sdREnPgShLvhEh/ABG1n4+pgn4shuY7EXECQjGwkr6g",
	"AewH5vMoFhFVxCNpygLSJmqYAPGIVILxPsnahDVUk5/5ih2DUc6Fz+M4BMqNVIZp30jgWxoloRVS/yXw",
	"4JuIBUEILkSZgM9oyF5TxWLeyNusTQS8SpmAgHgHxKrcgmmX4ed+1Zw/LCHj5y/AV8aPPaN9m0M/DurB",
	"bk0Yp5H7vaD8pRFEjLMojYi3W75mXEEfhDtQ61COm6O4wtnnQSqVqyo+UESbfHU52eM0kYNYOZxcFHX+",
	"iymI7Mf/BRwRj/yvU3VDJ2+FTtkHWWmJCkHtb1sKzaEWteDAYQtWt3GrTIQDbrlom2P2lt65kBX4Ax6H",
	"cX8bV58Vj5zOHoOQxlq9RgKq4BPFInA26e18L/vdvDQDkL5gSfFqIT8oFNqEp2FIDrcYY3lS9v+JqbdF",
	"Q9TsrnbyncOplpl1rTK8m5j/TNdnlv6j2IIxZbfEF72nrachVcaL1l+jn1ufM9/kmophqwfimPlAagVI",
	"dne6O13jVZwApwkjHvl0Z3enS9okoWpgaeksj5A+2CljiCsXDfmaSfW4UjOvBY1AgZDEOzghzBh7lYIY",
	"FvF4rkWz6J9Gi8uNWdtUjaEODfMyiblcBPig2120EFfAbaw0SULmWzc7L+Sicyr895yp2WpXEvwd3+FU",
	"n+Icr1t4jWN9hhO8wLke4RSvzJOsXU9L54QF2drc7IEqrbsTY1JdcWhJqmpRiRTuk85mLDpY+2WZKP3W",
	"cP2w+9CArqj+ipMW3uAYr/ASJ3iD84LUar+trfO9hcp9VM2a9bmpZC70CCc2tjmeF5ENgIZq8HptaF/m",
	"cndcy+aefFWgLu/xtZztV2r3wdv6U2ETdXN9pkc41qc4MxRWYSoQnIadoJinpu1k7erKQ1/B/g3nOMMb",
	"/RNetfQp3uAU/7SG9Cm+M4bwHOf6Byu4NtlqfYSXONNvTd9P9I84buGlHunv8AKn+o15NtEjPM8dPv+Y",
	"tFfYLi/BD9iGpQ03nWWUBXuO62xtpfRWdButkqVr4L2XCLXnwxMeDpfQAjiiaaiKibh6vtzPHtl0sG6o",
	"b1N2ONHf4xTHOMMp/oFj+6us9NV7d22intUVG2XJr7ZQFXX1DzekvJ/SPvxbK/quo30TrWc40W/MHsEZ",
	"zvGiJDRrEwniuGAlFSHxyECpxOt0wtin4SCWynvUffSAZIfZ3wMA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
