// Package apisearch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apisearch

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SearchCandidatesParamsSort.
const (
	FspWeight SearchCandidatesParamsSort = "fspWeight"
	Relevance SearchCandidatesParamsSort = "relevance"
	TestScore SearchCandidatesParamsSort = "testScore"
)

// Valid indicates whether the value is a known member of the SearchCandidatesParamsSort enum.
func (e SearchCandidatesParamsSort) Valid() bool {
	switch e {
	case FspWeight:
		return true
	case Relevance:
		return true
	case TestScore:
		return true
	default:
		return false
	}
}

// ExplainResponse defines model for ExplainResponse.
type ExplainResponse struct {
	Factors *[]struct {
		Contribution *float32 `json:"contribution,omitempty"`
		Detail       *string  `json:"detail,omitempty"`
		Name         *string  `json:"name,omitempty"`
		Weight       *float32 `json:"weight,omitempty"`
	} `json:"factors,omitempty"`
	FinalScore *float32            `json:"finalScore,omitempty"`
	UserId     *openapi_types.UUID `json:"userId,omitempty"`
}

// SearchHit defines model for SearchHit.
type SearchHit struct {
	CategoryId           openapi_types.UUID `json:"categoryId"`
	DisplayName          *string            `json:"displayName,omitempty"`
	FspAchievementsCount *int               `json:"fspAchievementsCount,omitempty"`
	FspBestPlace         *int               `json:"fspBestPlace,omitempty"`
	FspWeightSum         *int               `json:"fspWeightSum,omitempty"`
	GradeId              openapi_types.UUID `json:"gradeId"`
	Reasons              []string           `json:"reasons"`
	Score                float32            `json:"score"`
	SpecializationId     openapi_types.UUID `json:"specializationId"`
	TestScore            *float32           `json:"testScore,omitempty"`
	UserId               openapi_types.UUID `json:"userId"`
	YearsExperience      *float32           `json:"yearsExperience,omitempty"`
}

// SearchPage defines model for SearchPage.
type SearchPage struct {
	Items  []SearchHit `json:"items"`
	Limit  int         `json:"limit"`
	Offset int         `json:"offset"`
	Total  int         `json:"total"`
}

// SearchCandidatesParams defines parameters for SearchCandidates.
type SearchCandidatesParams struct {
	CategoryId       *openapi_types.UUID `form:"categoryId,omitempty" json:"categoryId,omitempty"`
	SpecializationId *openapi_types.UUID `form:"specializationId,omitempty" json:"specializationId,omitempty"`
	GradeId          *openapi_types.UUID `form:"gradeId,omitempty" json:"gradeId,omitempty"`

	// Stack Повторяющийся параметр — ID технологий
	Stack              *[]openapi_types.UUID       `form:"stack,omitempty" json:"stack,omitempty"`
	HasFsp             *bool                       `form:"hasFsp,omitempty" json:"hasFsp,omitempty"`
	MinYearsExperience *float32                    `form:"minYearsExperience,omitempty" json:"minYearsExperience,omitempty"`
	Location           *string                     `form:"location,omitempty" json:"location,omitempty"`
	Limit              *int                        `form:"limit,omitempty" json:"limit,omitempty"`
	Offset             *int                        `form:"offset,omitempty" json:"offset,omitempty"`
	Sort               *SearchCandidatesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// SearchCandidatesParamsSort defines parameters for SearchCandidates.
type SearchCandidatesParamsSort string

// CategoryRankingParams defines parameters for CategoryRanking.
type CategoryRankingParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// SearchCandidates Поиск по банку кандидатов
	// (GET /candidates)
	SearchCandidates(c *gin.Context, params SearchCandidatesParams)
	// ExplainCandidate Объяснение попадания кандидата в выдачу
	// (GET /candidates/{userId}/explain)
	ExplainCandidate(c *gin.Context, userId openapi_types.UUID)
	// CategoryRanking Рейтинг внутри категории (для отладки и питча)
	// (GET /categories/{categoryId}/ranking)
	CategoryRanking(c *gin.Context, categoryId openapi_types.UUID, params CategoryRankingParams)

	// (GET /healthz)
	Healthz(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SearchCandidates operation middleware
func (siw *ServerInterfaceWrapper) SearchCandidates(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchCandidatesParams

	// ------------- Optional query parameter "categoryId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "categoryId", c.Request.URL.Query(), &params.CategoryId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "specializationId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "specializationId", c.Request.URL.Query(), &params.SpecializationId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter specializationId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "gradeId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "gradeId", c.Request.URL.Query(), &params.GradeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter gradeId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "stack" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "stack", c.Request.URL.Query(), &params.Stack, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter stack: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "hasFsp" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "hasFsp", c.Request.URL.Query(), &params.HasFsp, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter hasFsp: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "minYearsExperience" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "minYearsExperience", c.Request.URL.Query(), &params.MinYearsExperience, runtime.BindQueryParameterOptions{Type: "number", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter minYearsExperience: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "location" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "location", c.Request.URL.Query(), &params.Location, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter location: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", c.Request.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SearchCandidates(c, params)
}

// ExplainCandidate operation middleware
func (siw *ServerInterfaceWrapper) ExplainCandidate(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExplainCandidate(c, userId)
}

// CategoryRanking operation middleware
func (siw *ServerInterfaceWrapper) CategoryRanking(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "categoryId" -------------
	var categoryId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", c.Param("categoryId"), &categoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter categoryId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CategoryRankingParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CategoryRanking(c, categoryId, params)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/candidates", wrapper.SearchCandidates)
	router.GET(options.BaseURL+"/candidates/:userId/explain", wrapper.ExplainCandidate)
	router.GET(options.BaseURL+"/categories/:categoryId/ranking", wrapper.CategoryRanking)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"tFbdbhtFFH6V1cAFSKvYLUJUe1dKoxYkiGqkCkUWmqyPvdPuX2dmQ9zIkuMAEQSRG64pvIHrxGLj1M4r",
	"nHkFngTN7Nrrn7XiELjb3Tlz5uz3fec7c0jcKIijEEIpiHNIhOtBQM3j44PYpyx8BiKOQgH6U8yjGLhk",
	"YAKa1JURN49MQiBWI9wolJztJZJFoX6X7RiIQ8Ik2ANOOjZpgKTMn1sSkrOwpZdCGpgz4YAGsZ+tUffl",
	"twGVrkfs1Q3fAWt5suSYziw42nsBriTFB8o5bev3JgupX3MjDqV1JgL404b56YgHVBKHJAlrrJZRdlYN",
	"KHe9J0yWAEQltCLe3ii3TRpMxD5tf5lDs7LeFPFD12OwD4Em9FGUhPOAsFBCK/uhpog/BSF3fOrOpdqd",
	"hdgkTHyf1LPQ5wbaWhKUJ2tx2oANf4EDFVG4KJqNKV5mTawlTMTgMuqz11Rrb8PaJAj5H2jAJm2gXDw+",
	"iIEzCBcBzvPN8DWQvEoYh4Zezg+x55VRAFzyX1MQCmTrayW4Q1slbTyjYfbwPocmcch7lcIbKrkxVAox",
	"l/Dhs4CtEVzUbApYsyYjSf2ypSVwsgKn8dPjZrlXf1wLAdyEM9mu6fqzH94DyoE/TKRXvG1PKf38+dcG",
	"Ux1NnHy14NiTMiYdnZiFzcjUzKSR7nZtx9rxqdTisP7u/mZlSFk14PvM1QTtAxfGCMm9repW1aASQ0hj",
	"Rhzy0da9rSqxSUylZ6qsuDRssAaVWdGtDDxN3EzSOa2PikC9n9MAJHBBnN1DwvRxrxLgbTK11EVpZbxu",
	"5Gzl2UoVececc3q/TaoGCJezOJs2BN/gBAeqhxPVVWfqV/UTpnipjtSZhdfYV13s4zscqp7qGr6efmap",
	"Hg7VDzjGCV7hBM/1BmITOIj9qAHEkTwBuxwFbVwL9c666WbbWXY12TaK0hvJOog8KrZFvHBinmcvinyg",
	"4Xp0AxZ+s2RQJWmK6VmexY9cw3jZ3pv4nTZusbEBTZr4kjj3qzYJ6AEL9LC5V63aJaZQnjR3gdKst0gj",
	"Ir4mCeHgwz7N8IJQF7i78K2YH3NTc86WZrDUbcLza5WRyP1qdXpdgmxi0zj2WQZw5YXIbk9FSTcbtLF6",
	"41NLTfGn1jv2cYyp+hH7luriEP9Sx3ilflE97Ot+wYGljiyc4Fv1szpTRzjGod6AQ3yXmWoSBJS3p02W",
	"qiMc6aaaWPjW5B6pYwtH5vECU7yY5jW755ytcpgNvE4FstvmWqvLb6Mzr1tjddo+Cy5n07SYIlkLb24r",
	"/ydVyzfsMr7eqC6m6gRTHKtTC1MLBzjCK+zjhTpdJuP3VcYMLdrvNAmG9bNVZvoWDiwcqFPzfqKOpzyZ",
	"QcE0T8XQ6FQ4DV9qdNZx9SiPfZbHbULVwlD693Td3nA+njec+6WGc1cN3PViVdbGeG3aboKjVTonOLAt",
	"dYzX2ejDC5yoEyOIsTrFy6xT1RGmeGUEoro4Ud/rV3W2LKk/cIiXqqf1h+dafGN1bCwkNefqiYnn+hxM",
	"MbU+wAudxMKJ6mUixZGOTC1Tb0+dYP/DTFweUF96r9eK6Em+Xo79IhxffbFw1yPObr2z9GHx2rdb16QK",
	"4PtTSSbcz693TqWiZ5vvRUI6D6oPPiGdeuefAQA=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
