// Package apitesting provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apitesting

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SessionStatus.
const (
	SessionStatusCancelled  SessionStatus = "cancelled"
	SessionStatusEvaluated  SessionStatus = "evaluated"
	SessionStatusExpired    SessionStatus = "expired"
	SessionStatusInProgress SessionStatus = "in_progress"
	SessionStatusSubmitted  SessionStatus = "submitted"
)

// Valid indicates whether the value is a known member of the SessionStatus enum.
func (e SessionStatus) Valid() bool {
	switch e {
	case SessionStatusCancelled:
		return true
	case SessionStatusEvaluated:
		return true
	case SessionStatusExpired:
		return true
	case SessionStatusInProgress:
		return true
	case SessionStatusSubmitted:
		return true
	default:
		return false
	}
}

// Defines values for SessionItemStatus.
const (
	Answered SessionItemStatus = "answered"
	Pending  SessionItemStatus = "pending"
	Skipped  SessionItemStatus = "skipped"
)

// Valid indicates whether the value is a known member of the SessionItemStatus enum.
func (e SessionItemStatus) Valid() bool {
	switch e {
	case Answered:
		return true
	case Pending:
		return true
	case Skipped:
		return true
	default:
		return false
	}
}

// Defines values for SessionItemType.
const (
	Code         SessionItemType = "code"
	MultiChoice  SessionItemType = "multi_choice"
	Regex        SessionItemType = "regex"
	SingleChoice SessionItemType = "single_choice"
	Sql          SessionItemType = "sql"
	Text         SessionItemType = "text"
)

// Valid indicates whether the value is a known member of the SessionItemType enum.
func (e SessionItemType) Valid() bool {
	switch e {
	case Code:
		return true
	case MultiChoice:
		return true
	case Regex:
		return true
	case SingleChoice:
		return true
	case Sql:
		return true
	case Text:
		return true
	default:
		return false
	}
}

// Defines values for SessionResultDecision.
const (
	Confirmed        SessionResultDecision = "confirmed"
	DowngradeOffered SessionResultDecision = "downgrade_offered"
	UpgradeOffered   SessionResultDecision = "upgrade_offered"
)

// Valid indicates whether the value is a known member of the SessionResultDecision enum.
func (e SessionResultDecision) Valid() bool {
	switch e {
	case Confirmed:
		return true
	case DowngradeOffered:
		return true
	case UpgradeOffered:
		return true
	default:
		return false
	}
}

// Defines values for SessionWithItemsStatus.
const (
	SessionWithItemsStatusCancelled  SessionWithItemsStatus = "cancelled"
	SessionWithItemsStatusEvaluated  SessionWithItemsStatus = "evaluated"
	SessionWithItemsStatusExpired    SessionWithItemsStatus = "expired"
	SessionWithItemsStatusInProgress SessionWithItemsStatus = "in_progress"
	SessionWithItemsStatusSubmitted  SessionWithItemsStatus = "submitted"
)

// Valid indicates whether the value is a known member of the SessionWithItemsStatus enum.
func (e SessionWithItemsStatus) Valid() bool {
	switch e {
	case SessionWithItemsStatusCancelled:
		return true
	case SessionWithItemsStatusEvaluated:
		return true
	case SessionWithItemsStatusExpired:
		return true
	case SessionWithItemsStatusInProgress:
		return true
	case SessionWithItemsStatusSubmitted:
		return true
	default:
		return false
	}
}

// AnswerInput defines model for AnswerInput.
type AnswerInput struct {
	// Answer Произвольный JSON-ответ
	Answer  interface{}        `json:"answer,omitempty"`
	ItemId  openapi_types.UUID `json:"itemId"`
	Skipped *bool              `json:"skipped,omitempty"`
}

// GradeChange defines model for GradeChange.
type GradeChange struct {
	ChangedAt   *time.Time          `json:"changedAt,omitempty"`
	FromGradeId *openapi_types.UUID `json:"fromGradeId,omitempty"`
	Reason      *string             `json:"reason,omitempty"`
	ToGradeId   *openapi_types.UUID `json:"toGradeId,omitempty"`
}

// PeriodicTask defines model for PeriodicTask.
type PeriodicTask struct {
	Body       string              `json:"body"`
	CategoryId openapi_types.UUID  `json:"categoryId"`
	CreatedAt  *time.Time          `json:"createdAt,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Title      string              `json:"title"`
}

// PeriodicTaskInput defines model for PeriodicTaskInput.
type PeriodicTaskInput struct {
	Body       string             `json:"body"`
	CategoryId openapi_types.UUID `json:"categoryId"`
	Title      string             `json:"title"`
}

// Session defines model for Session.
type Session struct {
	FinishedAt       *time.Time         `json:"finishedAt,omitempty"`
	Id               openapi_types.UUID `json:"id"`
	StartedAt        time.Time          `json:"startedAt"`
	Status           SessionStatus      `json:"status"`
	TargetCategoryId openapi_types.UUID `json:"targetCategoryId"`
}

// SessionStatus defines model for Session.Status.
type SessionStatus string

// SessionItem defines model for SessionItem.
type SessionItem struct {
	Body     string             `json:"body"`
	Id       openapi_types.UUID `json:"id"`
	Position int                `json:"position"`
	Status   SessionItemStatus  `json:"status"`
	Topic    string             `json:"topic"`
	Type     SessionItemType    `json:"type"`
}

// SessionItemStatus defines model for SessionItem.Status.
type SessionItemStatus string

// SessionItemType defines model for SessionItem.Type.
type SessionItemType string

// SessionResult defines model for SessionResult.
type SessionResult struct {
	AbilityEstimate     *float32              `json:"abilityEstimate,omitempty"`
	Decision            SessionResultDecision `json:"decision"`
	ResultingCategoryId openapi_types.UUID    `json:"resultingCategoryId"`
	ResultingGradeId    openapi_types.UUID    `json:"resultingGradeId"`
	Score               float32               `json:"score"`
	SessionId           openapi_types.UUID    `json:"sessionId"`
}

// SessionResultDecision defines model for SessionResult.Decision.
type SessionResultDecision string

// SessionWithItems defines model for SessionWithItems.
type SessionWithItems struct {
	FinishedAt       *time.Time             `json:"finishedAt,omitempty"`
	Id               openapi_types.UUID     `json:"id"`
	Items            *[]SessionItem         `json:"items,omitempty"`
	StartedAt        time.Time              `json:"startedAt"`
	Status           SessionWithItemsStatus `json:"status"`
	TargetCategoryId openapi_types.UUID     `json:"targetCategoryId"`
}

// SessionWithItemsStatus defines model for SessionWithItems.Status.
type SessionWithItemsStatus string

// StartSessionRequest defines model for StartSessionRequest.
type StartSessionRequest struct {
	TargetCategoryId openapi_types.UUID `json:"targetCategoryId"`
}

// SubmitPeriodicTaskJSONBody defines parameters for SubmitPeriodicTask.
type SubmitPeriodicTaskJSONBody struct {
	Answer string `json:"answer"`
}

// SubmitPeriodicTaskJSONRequestBody defines body for SubmitPeriodicTask for application/json ContentType.
type SubmitPeriodicTaskJSONRequestBody SubmitPeriodicTaskJSONBody

// StartSessionJSONRequestBody defines body for StartSession for application/json ContentType.
type StartSessionJSONRequestBody = StartSessionRequest

// AnswerItemJSONRequestBody defines body for AnswerItem for application/json ContentType.
type AnswerItemJSONRequestBody = AnswerInput

// CreatePeriodicTaskJSONRequestBody defines body for CreatePeriodicTask for application/json ContentType.
type CreatePeriodicTaskJSONRequestBody = PeriodicTaskInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /healthz)
	Healthz(c *gin.Context)
	// InternalGetCategory Внутренний эндпоинт — текущая категория кандидата
	// (GET /internal/users/{userId}/category)
	InternalGetCategory(c *gin.Context, userId openapi_types.UUID)
	// ListGradeChanges История смены грейда и остаток кулдауна
	// (GET /me/category-changes)
	ListGradeChanges(c *gin.Context)

	// (GET /me/periodic-tasks)
	ListPeriodicTasks(c *gin.Context)

	// (POST /me/periodic-tasks/{id}/submit)
	SubmitPeriodicTask(c *gin.Context, id openapi_types.UUID)

	// (GET /me/sessions)
	ListMySessions(c *gin.Context)
	// StartSession Старт тест-сессии на выбранную категорию
	// (POST /me/sessions)
	StartSession(c *gin.Context)

	// (GET /me/sessions/{id})
	GetSession(c *gin.Context, id openapi_types.UUID)

	// (POST /me/sessions/{id}/answers)
	AnswerItem(c *gin.Context, id openapi_types.UUID)

	// (POST /me/sessions/{id}/submit)
	SubmitSession(c *gin.Context, id openapi_types.UUID)

	// (POST /periodic-tasks)
	CreatePeriodicTask(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// InternalGetCategory operation middleware
func (siw *ServerInterfaceWrapper) InternalGetCategory(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.InternalGetCategory(c, userId)
}

// ListGradeChanges operation middleware
func (siw *ServerInterfaceWrapper) ListGradeChanges(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListGradeChanges(c)
}

// ListPeriodicTasks operation middleware
func (siw *ServerInterfaceWrapper) ListPeriodicTasks(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPeriodicTasks(c)
}

// SubmitPeriodicTask operation middleware
func (siw *ServerInterfaceWrapper) SubmitPeriodicTask(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubmitPeriodicTask(c, id)
}

// ListMySessions operation middleware
func (siw *ServerInterfaceWrapper) ListMySessions(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMySessions(c)
}

// StartSession operation middleware
func (siw *ServerInterfaceWrapper) StartSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartSession(c)
}

// GetSession operation middleware
func (siw *ServerInterfaceWrapper) GetSession(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSession(c, id)
}

// AnswerItem operation middleware
func (siw *ServerInterfaceWrapper) AnswerItem(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AnswerItem(c, id)
}

// SubmitSession operation middleware
func (siw *ServerInterfaceWrapper) SubmitSession(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SubmitSession(c, id)
}

// CreatePeriodicTask operation middleware
func (siw *ServerInterfaceWrapper) CreatePeriodicTask(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreatePeriodicTask(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/me/sessions", wrapper.ListMySessions)
	router.POST(options.BaseURL+"/me/sessions", wrapper.StartSession)
	router.GET(options.BaseURL+"/me/sessions/:id", wrapper.GetSession)
	router.POST(options.BaseURL+"/me/sessions/:id/answers", wrapper.AnswerItem)
	router.POST(options.BaseURL+"/me/sessions/:id/submit", wrapper.SubmitSession)
	router.GET(options.BaseURL+"/me/category-changes", wrapper.ListGradeChanges)
	router.GET(options.BaseURL+"/me/periodic-tasks", wrapper.ListPeriodicTasks)
	router.POST(options.BaseURL+"/me/periodic-tasks/:id/submit", wrapper.SubmitPeriodicTask)
	router.POST(options.BaseURL+"/periodic-tasks", wrapper.CreatePeriodicTask)
	router.GET(options.BaseURL+"/internal/users/:userId/category", wrapper.InternalGetCategory)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FjdbtvGEn4VYs+5OAeQLeecFkh1lxpN6vQnQRUgF4YQrMmVtAnJZXaXTlxDgGxfpIXTGCgKtOhF27yB",
	"48S17MTKK8y+Qp+k2CEpUhKlUE4aFL0yLS5nZ75v5pvZ3SauCCIRslAr0tgmyu2ygOLjlVA9YHItjGJt",
	"/42kiJjUnOFLii/tk8eUK3mkuQhJg8Cvpg9DGMAJHMEQXprHcG724dS53rzx5RIMzS4cwbHZJb0a4ZoF",
	"a5610RYyoJo0SBxzj9SI3ooYaRClJQ87dqm6x6OIecl+bRr7mjTa1FdstHZDCJ/RkPR6NSLZ/ZhLu3w9",
	"26Q1Wig27jJXW6PXJPXYapeGHTYdoIu/e1f0mH8e1WxJ84CVOdmWIkCb84Jazz6okTD2fdJCf6my6G1P",
	"29TijRZHq3slMd5kkguPu7eouoe8+f6NNmmsb5N/S9YmDfKvep4A9ZT9evGrJAF6tSmAJKN6MYD4xaJo",
	"TcQxIyU3hLdViqFLNesIuVUx1zTXPisxNJFYBavZN7XEh7JcazKleMLxuNdtHnLVrYBjWeLwitWjqVyQ",
	"KqWpjtFBFsYBFlJ4J5KiI5lSpEZUvBFwrZndj21SP6bp88MIAbKohy7zfVasvQLIVHaYXl2EmcnCxiWT",
	"ZkaeF6OeQ8iaZsECqVQR8EgorvlYSfNQsw6T5dhGLPQSahNdRQAzzSuFT0TcLRcM/CE3rXjY8dkdtyu4",
	"a5kOYl/z/F9XeMg/e6jtlvd9YlHusIcl25YRMIo0XZ25lpbCKNg5FHzFFOr5VIvZ4D7XW58ozQOqixUZ",
	"xsFGAqXHXJ7VVRaxK8I2lwFi6IkHYccK6B3Rbqe4xtH4L2X4SvSJh53VxbRj9F111a4R5QpZHp5Kk/QC",
	"5ZF/mm1Q4l15oAVY59B2m+uurR5Vva1kIjjdTHhmaPRQwQ7Wbt4uqJR0a1b/aFoxGCXc/Zipkox7e1Ga",
	"sjANINLqxpLrraaNJ1UcRiWTV2Ldzf+7mm19/fYtZNGutqMOvs196WodkZ41zMO2wECSFkauNm86N32q",
	"bRDOH/0fnFtMWbKdJpObiQBsMpkUELm0vLK8YvEUEQtpxEmD/H/50vKKrXKqu+hmvcuor7tf2+cOQwgt",
	"gFSnWUo+Td9jZkUiVEl4/1tZmZ4Vb3w2hgZprLfs/3UrlTKkfj1WTKr6tv2z5vXqWcedufla+uG1nAJ0",
	"XtKAaSYVJii3W9uAbCOlCGiyASlSqWXMUshplTRolQfsilCzEF2lUeRzF52t303Hvdz+xGy1mOp0FhAb",
	"zZRuzhCc6dLpocaODfg/w6HZhWN4DkPTh4E5SEiMg4Baagh8D+dmz+yaPhzDOZzDAE4d8x2cwwt4jUeD",
	"c7OLyYhmzsye+RYOzYEDZ5OW8Sf8cAAv8OUhblYP2CgZlpJBXc1Mis+50oVJX5F3zFSY2L3Q/FbwvZLw",
	"FU8sFYSvhL2n8BoGZgeGcDbJ209mx+yOoDc78MoSaPYdeI5cnloOHBg4MMSVlo8hnDmWQniJBO3BeYGi",
	"KJ3ZlzRV9+YTVBzv35qhSlCOHYymsZxG7jebmTZSc2D6eKg9duAEDjHwRxaWF/Zdec6WQ1Lf5l6vnozS",
	"mFpCleDTxPdj/lYRNf4OBA375MfpMHzBCslvCua3znRdqzSLx+PoVekueBNhxebA5mmBg3Qymp+QX2w1",
	"s2XvIxvzyejNifgUjs2O2YEBDJL3M9KmMPGQi5M51+uSoaoSXZfenQsZcPOASuRsCCe2IkcSVZC+pyhn",
	"fbOLPcmq25LZyWF27DcOHJl9eGb6aMK2uCfTLesJmcwyrPGZqXaNFSh6PzX9FqlcgYj8VPBmRkbyaYcE",
	"cwCvYOD8B57BMZw4tuOYb3CCGMDpf0vKNxHPRDXUbPVMbzHtUeHvrZrzwC1exV5YD3/J7l4deJ1Lo5Wc",
	"D1Y+Kln/Y04OHDtmD363HS+7wX2E3AwdGMBLGDh5udgWaHk9M32zP9H+xrmr1vj+WfWRXnbMGjBOcMB4",
	"nExXOGsNcMp6DkM4mjElZ/hOj1vlsK7ixe3EPPFXZG3JLfL7bQ7jM16pHuVNIRkRxs+j4+fy9ZbNEMXk",
	"ZpaCsfTT83ejXveFS/2uULpxeeXyh6TX6v0ZAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
