// This file is auto-generated by @hey-api/openapi-ts

export const CreateInvitationRequestSchema = {
    type: 'object',
    properties: {
        candidateUserId: {
            type: 'string',
            format: 'uuid'
        },
        vacancyId: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        needId: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        message: {
            type: 'string'
        },
        salaryMin: {
            type: 'integer',
            minimum: 0
        },
        salaryMax: {
            type: 'integer',
            minimum: 0
        },
        currency: {
            type: 'string',
            default: 'RUB'
        },
        contactChannel: {
            type: 'string',
            enum: ['email', 'telegram', 'phone', 'platform']
        }
    },
    required: ['candidateUserId', 'message', 'salaryMin', 'salaryMax', 'contactChannel']
} as const;

export const CreateApplicationRequestSchema = {
    type: 'object',
    properties: {
        vacancyId: {
            type: 'string',
            format: 'uuid'
        },
        coverLetter: {
            type: 'string'
        }
    },
    required: ['vacancyId']
} as const;

export const InvitationSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        employerUserId: {
            type: 'string',
            format: 'uuid'
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        },
        candidateUserId: {
            type: 'string',
            format: 'uuid'
        },
        vacancyId: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        needId: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        message: {
            type: 'string'
        },
        salaryMin: {
            type: 'integer'
        },
        salaryMax: {
            type: 'integer'
        },
        currency: {
            type: 'string'
        },
        contactChannel: {
            type: 'string'
        },
        status: {
            type: 'string',
            enum: ['sent', 'viewed', 'accepted', 'rejected', 'withdrawn', 'expired']
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        statusUpdatedAt: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'employerUserId', 'companyId', 'candidateUserId', 'message', 'salaryMin', 'salaryMax', 'currency', 'contactChannel', 'status', 'createdAt']
} as const;

export const ApplicationSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        candidateUserId: {
            type: 'string',
            format: 'uuid'
        },
        vacancyId: {
            type: 'string',
            format: 'uuid'
        },
        companyId: {
            type: 'string',
            format: 'uuid'
        },
        coverLetter: {
            type: ['string', 'null']
        },
        status: {
            type: 'string',
            enum: ['sent', 'viewed', 'accepted', 'rejected', 'withdrawn']
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        },
        statusUpdatedAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const RevealRecordInputSchema = {
    type: 'object',
    properties: {
        candidateUserId: {
            type: 'string',
            format: 'uuid'
        },
        employerUserId: {
            type: 'string',
            format: 'uuid'
        },
        entityType: {
            type: 'string',
            enum: ['invitation', 'application']
        },
        entityId: {
            type: 'string',
            format: 'uuid'
        },
        reason: {
            type: 'string',
            enum: ['invitation_accepted', 'application_sent']
        }
    },
    required: ['candidateUserId', 'employerUserId', 'entityType', 'entityId', 'reason']
} as const;