// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { HealthzError, HealthzResponse, CreateInvitationData, CreateInvitationError, CreateInvitationResponse, ListMyInvitationsAsEmployerError, ListMyInvitationsAsEmployerResponse, WithdrawInvitationData, WithdrawInvitationError, WithdrawInvitationResponse, ListIncomingInvitationsError, ListIncomingInvitationsResponse, AcceptInvitationData, AcceptInvitationError, AcceptInvitationResponse, RejectInvitationData, RejectInvitationError, RejectInvitationResponse, CreateApplicationData, CreateApplicationError, CreateApplicationResponse, ListMyApplicationsAsCandidateError, ListMyApplicationsAsCandidateResponse, ListApplicationsForVacancyData, ListApplicationsForVacancyError, ListApplicationsForVacancyResponse, AcceptApplicationData, AcceptApplicationError, AcceptApplicationResponse, RejectApplicationData, RejectApplicationError, RejectApplicationResponse, InternalRecordRevealData, InternalRecordRevealError, InternalRecordRevealResponse } from './types.gen';

export const client = createClient(createConfig());

export const healthz = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthzResponse, HealthzError, ThrowOnError>({
        ...options,
        url: '/healthz'
    });
};

/**
 * Отправить приглашение кандидату
 */
export const createInvitation = <ThrowOnError extends boolean = false>(options: Options<CreateInvitationData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateInvitationResponse, CreateInvitationError, ThrowOnError>({
        ...options,
        url: '/me/invitations'
    });
};

export const listMyInvitationsAsEmployer = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ListMyInvitationsAsEmployerResponse, ListMyInvitationsAsEmployerError, ThrowOnError>({
        ...options,
        url: '/me/invitations'
    });
};

export const withdrawInvitation = <ThrowOnError extends boolean = false>(options: Options<WithdrawInvitationData, ThrowOnError>) => {
    return (options?.client ?? client).post<WithdrawInvitationResponse, WithdrawInvitationError, ThrowOnError>({
        ...options,
        url: '/me/invitations/{id}/withdraw'
    });
};

export const listIncomingInvitations = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ListIncomingInvitationsResponse, ListIncomingInvitationsError, ThrowOnError>({
        ...options,
        url: '/me/invitations/incoming'
    });
};

/**
 * Принятие раскрывает контакты работодателю
 */
export const acceptInvitation = <ThrowOnError extends boolean = false>(options: Options<AcceptInvitationData, ThrowOnError>) => {
    return (options?.client ?? client).post<AcceptInvitationResponse, AcceptInvitationError, ThrowOnError>({
        ...options,
        url: '/me/invitations/{id}/accept'
    });
};

export const rejectInvitation = <ThrowOnError extends boolean = false>(options: Options<RejectInvitationData, ThrowOnError>) => {
    return (options?.client ?? client).post<RejectInvitationResponse, RejectInvitationError, ThrowOnError>({
        ...options,
        url: '/me/invitations/{id}/reject'
    });
};

/**
 * Отклик кандидата на вакансию
 */
export const createApplication = <ThrowOnError extends boolean = false>(options: Options<CreateApplicationData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateApplicationResponse, CreateApplicationError, ThrowOnError>({
        ...options,
        url: '/me/applications'
    });
};

export const listMyApplicationsAsCandidate = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ListMyApplicationsAsCandidateResponse, ListMyApplicationsAsCandidateError, ThrowOnError>({
        ...options,
        url: '/me/applications'
    });
};

export const listApplicationsForVacancy = <ThrowOnError extends boolean = false>(options: Options<ListApplicationsForVacancyData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListApplicationsForVacancyResponse, ListApplicationsForVacancyError, ThrowOnError>({
        ...options,
        url: '/me/vacancies/{vacancyId}/applications'
    });
};

export const acceptApplication = <ThrowOnError extends boolean = false>(options: Options<AcceptApplicationData, ThrowOnError>) => {
    return (options?.client ?? client).post<AcceptApplicationResponse, AcceptApplicationError, ThrowOnError>({
        ...options,
        url: '/me/applications/{id}/accept'
    });
};

export const rejectApplication = <ThrowOnError extends boolean = false>(options: Options<RejectApplicationData, ThrowOnError>) => {
    return (options?.client ?? client).post<RejectApplicationResponse, RejectApplicationError, ThrowOnError>({
        ...options,
        url: '/me/applications/{id}/reject'
    });
};

export const internalRecordReveal = <ThrowOnError extends boolean = false>(options: Options<InternalRecordRevealData, ThrowOnError>) => {
    return (options?.client ?? client).post<InternalRecordRevealResponse, InternalRecordRevealError, ThrowOnError>({
        ...options,
        url: '/internal/reveals'
    });
};