// This file is auto-generated by @hey-api/openapi-ts

export type Application = {
    id?: string;
    candidateUserId?: string;
    vacancyId?: string;
    companyId?: string;
    coverLetter?: (string) | null;
    status?: 'sent' | 'viewed' | 'accepted' | 'rejected' | 'withdrawn';
    createdAt?: string;
    statusUpdatedAt?: string;
};

export type status = 'sent' | 'viewed' | 'accepted' | 'rejected' | 'withdrawn';

export type CreateApplicationRequest = {
    vacancyId: string;
    coverLetter?: string;
};

export type CreateInvitationRequest = {
    candidateUserId: string;
    vacancyId?: (string) | null;
    needId?: (string) | null;
    message: string;
    salaryMin: number;
    salaryMax: number;
    currency?: string;
    contactChannel: 'email' | 'telegram' | 'phone' | 'platform';
};

export type contactChannel = 'email' | 'telegram' | 'phone' | 'platform';

export type Invitation = {
    id: string;
    employerUserId: string;
    companyId: string;
    candidateUserId: string;
    vacancyId?: (string) | null;
    needId?: (string) | null;
    message: string;
    salaryMin: number;
    salaryMax: number;
    currency: string;
    contactChannel: string;
    status: 'sent' | 'viewed' | 'accepted' | 'rejected' | 'withdrawn' | 'expired';
    createdAt: string;
    statusUpdatedAt?: string;
};

export type status2 = 'sent' | 'viewed' | 'accepted' | 'rejected' | 'withdrawn' | 'expired';

export type RevealRecordInput = {
    candidateUserId: string;
    employerUserId: string;
    entityType: 'invitation' | 'application';
    entityId: string;
    reason: 'invitation_accepted' | 'application_sent';
};

export type entityType = 'invitation' | 'application';

export type reason = 'invitation_accepted' | 'application_sent';

export type HealthzResponse = (unknown);

export type HealthzError = unknown;

export type CreateInvitationData = {
    body: CreateInvitationRequest;
};

export type CreateInvitationResponse = (Invitation);

export type CreateInvitationError = unknown;

export type ListMyInvitationsAsEmployerResponse = (Array<Invitation>);

export type ListMyInvitationsAsEmployerError = unknown;

export type WithdrawInvitationData = {
    path: {
        id: string;
    };
};

export type WithdrawInvitationResponse = (Invitation);

export type WithdrawInvitationError = unknown;

export type ListIncomingInvitationsResponse = (Array<Invitation>);

export type ListIncomingInvitationsError = unknown;

export type AcceptInvitationData = {
    path: {
        id: string;
    };
};

export type AcceptInvitationResponse = (Invitation);

export type AcceptInvitationError = unknown;

export type RejectInvitationData = {
    path: {
        id: string;
    };
};

export type RejectInvitationResponse = (Invitation);

export type RejectInvitationError = unknown;

export type CreateApplicationData = {
    body: CreateApplicationRequest;
};

export type CreateApplicationResponse = (Application);

export type CreateApplicationError = unknown;

export type ListMyApplicationsAsCandidateResponse = (Array<Application>);

export type ListMyApplicationsAsCandidateError = unknown;

export type ListApplicationsForVacancyData = {
    path: {
        vacancyId: string;
    };
};

export type ListApplicationsForVacancyResponse = (Array<Application>);

export type ListApplicationsForVacancyError = unknown;

export type AcceptApplicationData = {
    path: {
        id: string;
    };
};

export type AcceptApplicationResponse = (unknown);

export type AcceptApplicationError = unknown;

export type RejectApplicationData = {
    path: {
        id: string;
    };
};

export type RejectApplicationResponse = (unknown);

export type RejectApplicationError = unknown;

export type InternalRecordRevealData = {
    body: RevealRecordInput;
};

export type InternalRecordRevealResponse = (unknown);

export type InternalRecordRevealError = unknown;