// This file is auto-generated by @hey-api/openapi-ts

export const IndustrySchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        code: {
            type: 'string'
        },
        name: {
            type: 'string'
        }
    },
    required: ['id', 'code', 'name']
} as const;

export const SpecializationSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        industryId: {
            type: 'string',
            format: 'uuid'
        },
        code: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        description: {
            type: ['string', 'null']
        },
        isActive: {
            type: 'boolean'
        }
    },
    required: ['id', 'industryId', 'code', 'name', 'isActive']
} as const;

export const GradeSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        code: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        rank: {
            type: 'integer',
            minimum: 1
        }
    },
    required: ['id', 'code', 'name', 'rank']
} as const;

export const CategorySchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        specializationId: {
            type: 'string',
            format: 'uuid'
        },
        gradeId: {
            type: 'string',
            format: 'uuid'
        },
        slug: {
            type: 'string',
            example: 'backend_middle'
        },
        isActive: {
            type: 'boolean'
        }
    },
    required: ['id', 'specializationId', 'gradeId', 'slug', 'isActive']
} as const;

export const TechnologySchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        code: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        category: {
            type: ['string', 'null']
        }
    },
    required: ['id', 'code', 'name']
} as const;

export const SnapshotSchema = {
    type: 'object',
    properties: {
        industries: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Industry'
            }
        },
        specializations: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Specialization'
            }
        },
        grades: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Grade'
            }
        },
        categories: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Category'
            }
        },
        technologies: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Technology'
            }
        },
        version: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;