// This file is auto-generated by @hey-api/openapi-ts

export type Category = {
    id: string;
    specializationId: string;
    gradeId: string;
    slug: string;
    isActive: boolean;
};

export type Grade = {
    id: string;
    code: string;
    name: string;
    rank: number;
};

export type Industry = {
    id: string;
    code: string;
    name: string;
};

export type Snapshot = {
    industries?: Array<Industry>;
    specializations?: Array<Specialization>;
    grades?: Array<Grade>;
    categories?: Array<Category>;
    technologies?: Array<Technology>;
    version?: string;
};

export type Specialization = {
    id: string;
    industryId: string;
    code: string;
    name: string;
    description?: (string) | null;
    isActive: boolean;
};

export type Technology = {
    id: string;
    code: string;
    name: string;
    category?: (string) | null;
};

export type HealthzResponse = (unknown);

export type HealthzError = unknown;

export type ListIndustriesResponse = (Array<Industry>);

export type ListIndustriesError = unknown;

export type ListSpecializationsData = {
    query?: {
        activeOnly?: boolean;
        industryId?: string;
    };
};

export type ListSpecializationsResponse = (Array<Specialization>);

export type ListSpecializationsError = unknown;

export type ListGradesResponse = (Array<Grade>);

export type ListGradesError = unknown;

export type ListCategoriesData = {
    query?: {
        gradeId?: string;
        specializationId?: string;
    };
};

export type ListCategoriesResponse = (Array<Category>);

export type ListCategoriesError = unknown;

export type GetCategoryData = {
    path: {
        id: string;
    };
};

export type GetCategoryResponse = (Category);

export type GetCategoryError = (unknown);

export type ListTechnologiesData = {
    query?: {
        category?: string;
    };
};

export type ListTechnologiesResponse = (Array<Technology>);

export type ListTechnologiesError = unknown;

export type SnapshotResponse = (Snapshot);

export type SnapshotError = unknown;