// Package apiinteraction provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apiinteraction

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApplicationStatus.
const (
	ApplicationStatusAccepted  ApplicationStatus = "accepted"
	ApplicationStatusRejected  ApplicationStatus = "rejected"
	ApplicationStatusSent      ApplicationStatus = "sent"
	ApplicationStatusViewed    ApplicationStatus = "viewed"
	ApplicationStatusWithdrawn ApplicationStatus = "withdrawn"
)

// Valid indicates whether the value is a known member of the ApplicationStatus enum.
func (e ApplicationStatus) Valid() bool {
	switch e {
	case ApplicationStatusAccepted:
		return true
	case ApplicationStatusRejected:
		return true
	case ApplicationStatusSent:
		return true
	case ApplicationStatusViewed:
		return true
	case ApplicationStatusWithdrawn:
		return true
	default:
		return false
	}
}

// Defines values for CreateInvitationRequestContactChannel.
const (
	Email    CreateInvitationRequestContactChannel = "email"
	Phone    CreateInvitationRequestContactChannel = "phone"
	Platform CreateInvitationRequestContactChannel = "platform"
	Telegram CreateInvitationRequestContactChannel = "telegram"
)

// Valid indicates whether the value is a known member of the CreateInvitationRequestContactChannel enum.
func (e CreateInvitationRequestContactChannel) Valid() bool {
	switch e {
	case Email:
		return true
	case Phone:
		return true
	case Platform:
		return true
	case Telegram:
		return true
	default:
		return false
	}
}

// Defines values for InvitationStatus.
const (
	InvitationStatusAccepted  InvitationStatus = "accepted"
	InvitationStatusExpired   InvitationStatus = "expired"
	InvitationStatusRejected  InvitationStatus = "rejected"
	InvitationStatusSent      InvitationStatus = "sent"
	InvitationStatusViewed    InvitationStatus = "viewed"
	InvitationStatusWithdrawn InvitationStatus = "withdrawn"
)

// Valid indicates whether the value is a known member of the InvitationStatus enum.
func (e InvitationStatus) Valid() bool {
	switch e {
	case InvitationStatusAccepted:
		return true
	case InvitationStatusExpired:
		return true
	case InvitationStatusRejected:
		return true
	case InvitationStatusSent:
		return true
	case InvitationStatusViewed:
		return true
	case InvitationStatusWithdrawn:
		return true
	default:
		return false
	}
}

// Defines values for RevealRecordInputEntityType.
const (
	RevealRecordInputEntityTypeApplication RevealRecordInputEntityType = "application"
	RevealRecordInputEntityTypeInvitation  RevealRecordInputEntityType = "invitation"
)

// Valid indicates whether the value is a known member of the RevealRecordInputEntityType enum.
func (e RevealRecordInputEntityType) Valid() bool {
	switch e {
	case RevealRecordInputEntityTypeApplication:
		return true
	case RevealRecordInputEntityTypeInvitation:
		return true
	default:
		return false
	}
}

// Defines values for RevealRecordInputReason.
const (
	ApplicationSent    RevealRecordInputReason = "application_sent"
	InvitationAccepted RevealRecordInputReason = "invitation_accepted"
)

// Valid indicates whether the value is a known member of the RevealRecordInputReason enum.
func (e RevealRecordInputReason) Valid() bool {
	switch e {
	case ApplicationSent:
		return true
	case InvitationAccepted:
		return true
	default:
		return false
	}
}

// Application defines model for Application.
type Application struct {
	CandidateUserId *openapi_types.UUID `json:"candidateUserId,omitempty"`
	CompanyId       *openapi_types.UUID `json:"companyId,omitempty"`
	CoverLetter     *string             `json:"coverLetter,omitempty"`
	CreatedAt       *time.Time          `json:"createdAt,omitempty"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	Status          *ApplicationStatus  `json:"status,omitempty"`
	StatusUpdatedAt *time.Time          `json:"statusUpdatedAt,omitempty"`
	VacancyId       *openapi_types.UUID `json:"vacancyId,omitempty"`
}

// ApplicationStatus defines model for Application.Status.
type ApplicationStatus string

// CreateApplicationRequest defines model for CreateApplicationRequest.
type CreateApplicationRequest struct {
	CoverLetter *string            `json:"coverLetter,omitempty"`
	VacancyId   openapi_types.UUID `json:"vacancyId"`
}

// CreateInvitationRequest defines model for CreateInvitationRequest.
type CreateInvitationRequest struct {
	CandidateUserId openapi_types.UUID                    `json:"candidateUserId"`
	ContactChannel  CreateInvitationRequestContactChannel `json:"contactChannel"`
	Currency        *string                               `json:"currency,omitempty"`
	Message         string                                `json:"message"`
	NeedId          *openapi_types.UUID                   `json:"needId,omitempty"`
	SalaryMax       int                                   `json:"salaryMax"`
	SalaryMin       int                                   `json:"salaryMin"`
	VacancyId       *openapi_types.UUID                   `json:"vacancyId,omitempty"`
}

// CreateInvitationRequestContactChannel defines model for CreateInvitationRequest.ContactChannel.
type CreateInvitationRequestContactChannel string

// Invitation defines model for Invitation.
type Invitation struct {
	CandidateUserId openapi_types.UUID  `json:"candidateUserId"`
	CompanyId       openapi_types.UUID  `json:"companyId"`
	ContactChannel  string              `json:"contactChannel"`
	CreatedAt       time.Time           `json:"createdAt"`
	Currency        string              `json:"currency"`
	EmployerUserId  openapi_types.UUID  `json:"employerUserId"`
	Id              openapi_types.UUID  `json:"id"`
	Message         string              `json:"message"`
	NeedId          *openapi_types.UUID `json:"needId,omitempty"`
	SalaryMax       int                 `json:"salaryMax"`
	SalaryMin       int                 `json:"salaryMin"`
	Status          InvitationStatus    `json:"status"`
	StatusUpdatedAt *time.Time          `json:"statusUpdatedAt,omitempty"`
	VacancyId       *openapi_types.UUID `json:"vacancyId,omitempty"`
}

// InvitationStatus defines model for Invitation.Status.
type InvitationStatus string

// RevealRecordInput defines model for RevealRecordInput.
type RevealRecordInput struct {
	CandidateUserId openapi_types.UUID          `json:"candidateUserId"`
	EmployerUserId  openapi_types.UUID          `json:"employerUserId"`
	EntityId        openapi_types.UUID          `json:"entityId"`
	EntityType      RevealRecordInputEntityType `json:"entityType"`
	Reason          RevealRecordInputReason     `json:"reason"`
}

// RevealRecordInputEntityType defines model for RevealRecordInput.EntityType.
type RevealRecordInputEntityType string

// RevealRecordInputReason defines model for RevealRecordInput.Reason.
type RevealRecordInputReason string

// InternalRecordRevealJSONRequestBody defines body for InternalRecordReveal for application/json ContentType.
type InternalRecordRevealJSONRequestBody = RevealRecordInput

// CreateApplicationJSONRequestBody defines body for CreateApplication for application/json ContentType.
type CreateApplicationJSONRequestBody = CreateApplicationRequest

// CreateInvitationJSONRequestBody defines body for CreateInvitation for application/json ContentType.
type CreateInvitationJSONRequestBody = CreateInvitationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /healthz)
	Healthz(c *gin.Context)

	// (POST /internal/reveals)
	InternalRecordReveal(c *gin.Context)

	// (GET /me/applications)
	ListMyApplicationsAsCandidate(c *gin.Context)
	// CreateApplication Отклик кандидата на вакансию
	// (POST /me/applications)
	CreateApplication(c *gin.Context)

	// (POST /me/applications/{id}/accept)
	AcceptApplication(c *gin.Context, id openapi_types.UUID)

	// (POST /me/applications/{id}/reject)
	RejectApplication(c *gin.Context, id openapi_types.UUID)

	// (GET /me/invitations)
	ListMyInvitationsAsEmployer(c *gin.Context)
	// CreateInvitation Отправить приглашение кандидату
	// (POST /me/invitations)
	CreateInvitation(c *gin.Context)

	// (GET /me/invitations/incoming)
	ListIncomingInvitations(c *gin.Context)

	// (POST /me/invitations/{id}/accept)
	AcceptInvitation(c *gin.Context, id openapi_types.UUID)

	// (POST /me/invitations/{id}/reject)
	RejectInvitation(c *gin.Context, id openapi_types.UUID)

	// (POST /me/invitations/{id}/withdraw)
	WithdrawInvitation(c *gin.Context, id openapi_types.UUID)

	// (GET /me/vacancies/{vacancyId}/applications)
	ListApplicationsForVacancy(c *gin.Context, vacancyId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// InternalRecordReveal operation middleware
func (siw *ServerInterfaceWrapper) InternalRecordReveal(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.InternalRecordReveal(c)
}

// ListMyApplicationsAsCandidate operation middleware
func (siw *ServerInterfaceWrapper) ListMyApplicationsAsCandidate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMyApplicationsAsCandidate(c)
}

// CreateApplication operation middleware
func (siw *ServerInterfaceWrapper) CreateApplication(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateApplication(c)
}

// AcceptApplication operation middleware
func (siw *ServerInterfaceWrapper) AcceptApplication(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AcceptApplication(c, id)
}

// RejectApplication operation middleware
func (siw *ServerInterfaceWrapper) RejectApplication(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RejectApplication(c, id)
}

// ListMyInvitationsAsEmployer operation middleware
func (siw *ServerInterfaceWrapper) ListMyInvitationsAsEmployer(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMyInvitationsAsEmployer(c)
}

// CreateInvitation operation middleware
func (siw *ServerInterfaceWrapper) CreateInvitation(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateInvitation(c)
}

// ListIncomingInvitations operation middleware
func (siw *ServerInterfaceWrapper) ListIncomingInvitations(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListIncomingInvitations(c)
}

// AcceptInvitation operation middleware
func (siw *ServerInterfaceWrapper) AcceptInvitation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AcceptInvitation(c, id)
}

// RejectInvitation operation middleware
func (siw *ServerInterfaceWrapper) RejectInvitation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RejectInvitation(c, id)
}

// WithdrawInvitation operation middleware
func (siw *ServerInterfaceWrapper) WithdrawInvitation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.WithdrawInvitation(c, id)
}

// ListApplicationsForVacancy operation middleware
func (siw *ServerInterfaceWrapper) ListApplicationsForVacancy(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "vacancyId" -------------
	var vacancyId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "vacancyId", c.Param("vacancyId"), &vacancyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vacancyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApplicationsForVacancy(c, vacancyId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/me/invitations", wrapper.ListMyInvitationsAsEmployer)
	router.POST(options.BaseURL+"/me/invitations", wrapper.CreateInvitation)
	router.POST(options.BaseURL+"/me/invitations/:id/withdraw", wrapper.WithdrawInvitation)
	router.GET(options.BaseURL+"/me/invitations/incoming", wrapper.ListIncomingInvitations)
	router.POST(options.BaseURL+"/me/invitations/:id/accept", wrapper.AcceptInvitation)
	router.POST(options.BaseURL+"/me/invitations/:id/reject", wrapper.RejectInvitation)
	router.GET(options.BaseURL+"/me/applications", wrapper.ListMyApplicationsAsCandidate)
	router.POST(options.BaseURL+"/me/applications", wrapper.CreateApplication)
	router.GET(options.BaseURL+"/me/vacancies/:vacancyId/applications", wrapper.ListApplicationsForVacancy)
	router.POST(options.BaseURL+"/me/applications/:id/accept", wrapper.AcceptApplication)
	router.POST(options.BaseURL+"/me/applications/:id/reject", wrapper.RejectApplication)
	router.POST(options.BaseURL+"/internal/reveals", wrapper.InternalRecordReveal)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FjRbts2F34Vg/9/qUXuBgyF79xixby1WJG260VgFKx0ErOQKJWk3HqGgdTDgA0dWmAYsJuhewWvSzAv",
	"mZ1XIF9hTzKQlC3ZkmIla5ICvTFk84jk+b7vfDz0EHlRGEcUqOCoNUTc60GIzWM7jgPiYUEiqr/GLIqB",
	"CQJm0MPUJz4W8IAD6/j6p92IhVigFkoS4iMHiUEMqIW4YITuoZFjVsJ0UDu6D+w2CAFMx9vxnUWAg2gS",
	"BKirAxlgAX5brEyr9/aRICGUzU3qbYELLBKTLtAkNKsDFchBfQLPQL+CPQ9iYR4ZPAHPPj4joucz/Iyi",
	"buWsD2L/rLvuYw9Trx5+o+Uv0WO9L/3+TQNUjtZteJoAFyXslmF//p0weJoQBr5GMHu1W7nFDu0TsWGH",
	"59IfFdgTN3uYUgjytEKISaBfgQD2GA6Rg+JeRDULcYCFnrmUSi9hDKg30HP5sIuTQK+//eBG2fIhcI73",
	"oBRQCuCflkWZ7jkOMBvcwc/1ayGhJNTJNJcrEypgDxjKQgndHFqD2uJm1jheJyfLPb+VfAYFcsrEkcni",
	"avxoXT3FkLM7UV5BhUEI4yAaADtDTjWd7UK1uEF/JcP/2WcdBM9jI7/LdtyNxWBi15jMa885X7ksdFMQ",
	"5hLOvB7Lymkb+oCDbfAi5ndonLwjlz2HaIEKIgZnCr5vfs4EQzJvcBDOdS5lemCAuTWR4uuPclLLzfPI",
	"KLK76XQrUllgPrf/XObLTRWZ0gIGL2FEDO7p7sxS8xgwA9ZORC/7dmuB3RcP72sdmGjUSkczMHtCxGik",
	"JyZ0NzI1SUSgR27du9u4m554jX/2f250qACGPQ1B4x6wPvH0tvvAuLFhdG2rudXUmEYxUBwT1EKfbF3b",
	"auqTE4ue2arbAxyI3jf6eQ+MzLTIDK6adPR5Oq5B4HFEuU3x42bTHqzcYyS2vo+++nIFEdTaMRXnajth",
	"FAcuM7I2E8QRL1mtk0Za5dsqQJZG4OJG5A9sC0SFprw1zMvAfZIKx/bJ+un/DHZRC/3PzRppN+2i3WKJ",
	"jVYVI1gCo0La14ppy1/kRJ7IqXohJ3Im53oinXYIbm57vBLi24SLO4Nc78fb/OZCrBXA14aACAj5Jizy",
	"14msO8WM4YFFZS3hX+VcThtyrsbySB7LqTySUxtYTmuhu70gTiu76PrUvpN9rOBZgt8bNZYnal9O5Ft5",
	"LA9T0TiIJ2GI2WARkmLbkEdGWAdyKg/kRI3lpCFn+uOtnNgx9UJO1StUJjt3SPyRa52zuvDaZnyVoRgz",
	"HIIAxlFrZ4h0h2CMQx+n2JgX8dE6rE4Ook23j24dU5G/qX05lTP1Wo0ra8smaduP6iS3zfh7meSC7rmc",
	"LfWwSDQ7ADd5SNaF8zb/LD3dLsVBcv1/HQOxnP4hj+VEfW8SnqrXjnWU1cKYqZfyUFfAXP4tT0wdTOWh",
	"/Guz3XTybcfFuU3xQnzJZpOH/vxeswiZqrH6sWG+rhFkaVgxIvUtKhGpS6gXhVr9p6m1kwblNPs+KvUn",
	"9Z2cywP1Wv1gITgpk255tVZZ7ykGp5fQTKgX8kjtq5fG4g/V2FbATHu/PFJj9dJEyd9NxczTY+FQHqtX",
	"yCm19pVquCrTuwy9Vx0XBV7qnRYfDG41TyCL3eJ2X43ewzTig8JvLv80BbuKnv2nggB3h8s/LUb1rwb5",
	"i8GtiH1tp6iFZvYfyVWCeiFXkDf5u0dlOzxau4+u3s13ujo3Dqy/wDBhQXoHb7luEHk46EVctK43r3+K",
	"Rt3RvwEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
