// Package apiinteraction provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apiinteraction

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApplicationStatus.
const (
	ApplicationStatusAccepted  ApplicationStatus = "accepted"
	ApplicationStatusRejected  ApplicationStatus = "rejected"
	ApplicationStatusSent      ApplicationStatus = "sent"
	ApplicationStatusViewed    ApplicationStatus = "viewed"
	ApplicationStatusWithdrawn ApplicationStatus = "withdrawn"
)

// Valid indicates whether the value is a known member of the ApplicationStatus enum.
func (e ApplicationStatus) Valid() bool {
	switch e {
	case ApplicationStatusAccepted:
		return true
	case ApplicationStatusRejected:
		return true
	case ApplicationStatusSent:
		return true
	case ApplicationStatusViewed:
		return true
	case ApplicationStatusWithdrawn:
		return true
	default:
		return false
	}
}

// Defines values for CreateInvitationRequestContactChannel.
const (
	Email    CreateInvitationRequestContactChannel = "email"
	Phone    CreateInvitationRequestContactChannel = "phone"
	Platform CreateInvitationRequestContactChannel = "platform"
	Telegram CreateInvitationRequestContactChannel = "telegram"
)

// Valid indicates whether the value is a known member of the CreateInvitationRequestContactChannel enum.
func (e CreateInvitationRequestContactChannel) Valid() bool {
	switch e {
	case Email:
		return true
	case Phone:
		return true
	case Platform:
		return true
	case Telegram:
		return true
	default:
		return false
	}
}

// Defines values for InvitationStatus.
const (
	InvitationStatusAccepted  InvitationStatus = "accepted"
	InvitationStatusExpired   InvitationStatus = "expired"
	InvitationStatusRejected  InvitationStatus = "rejected"
	InvitationStatusSent      InvitationStatus = "sent"
	InvitationStatusViewed    InvitationStatus = "viewed"
	InvitationStatusWithdrawn InvitationStatus = "withdrawn"
)

// Valid indicates whether the value is a known member of the InvitationStatus enum.
func (e InvitationStatus) Valid() bool {
	switch e {
	case InvitationStatusAccepted:
		return true
	case InvitationStatusExpired:
		return true
	case InvitationStatusRejected:
		return true
	case InvitationStatusSent:
		return true
	case InvitationStatusViewed:
		return true
	case InvitationStatusWithdrawn:
		return true
	default:
		return false
	}
}

// Defines values for RevealRecordInputEntityType.
const (
	RevealRecordInputEntityTypeApplication RevealRecordInputEntityType = "application"
	RevealRecordInputEntityTypeInvitation  RevealRecordInputEntityType = "invitation"
)

// Valid indicates whether the value is a known member of the RevealRecordInputEntityType enum.
func (e RevealRecordInputEntityType) Valid() bool {
	switch e {
	case RevealRecordInputEntityTypeApplication:
		return true
	case RevealRecordInputEntityTypeInvitation:
		return true
	default:
		return false
	}
}

// Defines values for RevealRecordInputReason.
const (
	ApplicationSent    RevealRecordInputReason = "application_sent"
	InvitationAccepted RevealRecordInputReason = "invitation_accepted"
)

// Valid indicates whether the value is a known member of the RevealRecordInputReason enum.
func (e RevealRecordInputReason) Valid() bool {
	switch e {
	case ApplicationSent:
		return true
	case InvitationAccepted:
		return true
	default:
		return false
	}
}

// Application defines model for Application.
type Application struct {
	CandidateUserId *openapi_types.UUID `json:"candidateUserId,omitempty"`
	CompanyId       *openapi_types.UUID `json:"companyId,omitempty"`
	CoverLetter     *string             `json:"coverLetter,omitempty"`
	CreatedAt       *time.Time          `json:"createdAt,omitempty"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	Status          *ApplicationStatus  `json:"status,omitempty"`
	StatusUpdatedAt *time.Time          `json:"statusUpdatedAt,omitempty"`
	VacancyId       *openapi_types.UUID `json:"vacancyId,omitempty"`
}

// ApplicationStatus defines model for Application.Status.
type ApplicationStatus string

// CreateApplicationRequest defines model for CreateApplicationRequest.
type CreateApplicationRequest struct {
	CoverLetter *string            `json:"coverLetter,omitempty"`
	VacancyId   openapi_types.UUID `json:"vacancyId"`
}

// CreateInvitationRequest defines model for CreateInvitationRequest.
type CreateInvitationRequest struct {
	CandidateUserId openapi_types.UUID                    `json:"candidateUserId"`
	ContactChannel  CreateInvitationRequestContactChannel `json:"contactChannel"`
	Currency        *string                               `json:"currency,omitempty"`
	Message         string                                `json:"message"`
	NeedId          *openapi_types.UUID                   `json:"needId,omitempty"`
	SalaryMax       int                                   `json:"salaryMax"`
	SalaryMin       int                                   `json:"salaryMin"`
	VacancyId       *openapi_types.UUID                   `json:"vacancyId,omitempty"`
}

// CreateInvitationRequestContactChannel defines model for CreateInvitationRequest.ContactChannel.
type CreateInvitationRequestContactChannel string

// Invitation defines model for Invitation.
type Invitation struct {
	CandidateUserId openapi_types.UUID  `json:"candidateUserId"`
	CompanyId       openapi_types.UUID  `json:"companyId"`
	ContactChannel  string              `json:"contactChannel"`
	CreatedAt       time.Time           `json:"createdAt"`
	Currency        string              `json:"currency"`
	EmployerUserId  openapi_types.UUID  `json:"employerUserId"`
	Id              openapi_types.UUID  `json:"id"`
	Message         string              `json:"message"`
	NeedId          *openapi_types.UUID `json:"needId,omitempty"`
	SalaryMax       int                 `json:"salaryMax"`
	SalaryMin       int                 `json:"salaryMin"`
	Status          InvitationStatus    `json:"status"`
	StatusUpdatedAt *time.Time          `json:"statusUpdatedAt,omitempty"`
	VacancyId       *openapi_types.UUID `json:"vacancyId,omitempty"`
}

// InvitationStatus defines model for Invitation.Status.
type InvitationStatus string

// RevealRecordInput defines model for RevealRecordInput.
type RevealRecordInput struct {
	CandidateUserId openapi_types.UUID          `json:"candidateUserId"`
	EmployerUserId  openapi_types.UUID          `json:"employerUserId"`
	EntityId        openapi_types.UUID          `json:"entityId"`
	EntityType      RevealRecordInputEntityType `json:"entityType"`
	Reason          RevealRecordInputReason     `json:"reason"`
}

// RevealRecordInputEntityType defines model for RevealRecordInput.EntityType.
type RevealRecordInputEntityType string

// RevealRecordInputReason defines model for RevealRecordInput.Reason.
type RevealRecordInputReason string

// InternalRecordRevealJSONRequestBody defines body for InternalRecordReveal for application/json ContentType.
type InternalRecordRevealJSONRequestBody = RevealRecordInput

// CreateApplicationJSONRequestBody defines body for CreateApplication for application/json ContentType.
type CreateApplicationJSONRequestBody = CreateApplicationRequest

// CreateInvitationJSONRequestBody defines body for CreateInvitation for application/json ContentType.
type CreateInvitationJSONRequestBody = CreateInvitationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /healthz)
	Healthz(c *gin.Context)

	// (POST /internal/reveals)
	InternalRecordReveal(c *gin.Context)

	// (GET /me/applications)
	ListMyApplicationsAsCandidate(c *gin.Context)
	// CreateApplication Отклик кандидата на вакансию
	// (POST /me/applications)
	CreateApplication(c *gin.Context)

	// (POST /me/applications/{id}/accept)
	AcceptApplication(c *gin.Context, id openapi_types.UUID)

	// (POST /me/applications/{id}/reject)
	RejectApplication(c *gin.Context, id openapi_types.UUID)

	// (GET /me/invitations)
	ListMyInvitationsAsEmployer(c *gin.Context)
	// CreateInvitation Отправить приглашение кандидату
	// (POST /me/invitations)
	CreateInvitation(c *gin.Context)

	// (GET /me/invitations/incoming)
	ListIncomingInvitations(c *gin.Context)

	// (POST /me/invitations/{id}/accept)
	AcceptInvitation(c *gin.Context, id openapi_types.UUID)

	// (POST /me/invitations/{id}/reject)
	RejectInvitation(c *gin.Context, id openapi_types.UUID)

	// (POST /me/invitations/{id}/withdraw)
	WithdrawInvitation(c *gin.Context, id openapi_types.UUID)

	// (GET /me/vacancies/{vacancyId}/applications)
	ListApplicationsForVacancy(c *gin.Context, vacancyId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// InternalRecordReveal operation middleware
func (siw *ServerInterfaceWrapper) InternalRecordReveal(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.InternalRecordReveal(c)
}

// ListMyApplicationsAsCandidate operation middleware
func (siw *ServerInterfaceWrapper) ListMyApplicationsAsCandidate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMyApplicationsAsCandidate(c)
}

// CreateApplication operation middleware
func (siw *ServerInterfaceWrapper) CreateApplication(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateApplication(c)
}

// AcceptApplication operation middleware
func (siw *ServerInterfaceWrapper) AcceptApplication(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AcceptApplication(c, id)
}

// RejectApplication operation middleware
func (siw *ServerInterfaceWrapper) RejectApplication(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RejectApplication(c, id)
}

// ListMyInvitationsAsEmployer operation middleware
func (siw *ServerInterfaceWrapper) ListMyInvitationsAsEmployer(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListMyInvitationsAsEmployer(c)
}

// CreateInvitation operation middleware
func (siw *ServerInterfaceWrapper) CreateInvitation(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateInvitation(c)
}

// ListIncomingInvitations operation middleware
func (siw *ServerInterfaceWrapper) ListIncomingInvitations(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListIncomingInvitations(c)
}

// AcceptInvitation operation middleware
func (siw *ServerInterfaceWrapper) AcceptInvitation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AcceptInvitation(c, id)
}

// RejectInvitation operation middleware
func (siw *ServerInterfaceWrapper) RejectInvitation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RejectInvitation(c, id)
}

// WithdrawInvitation operation middleware
func (siw *ServerInterfaceWrapper) WithdrawInvitation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.WithdrawInvitation(c, id)
}

// ListApplicationsForVacancy operation middleware
func (siw *ServerInterfaceWrapper) ListApplicationsForVacancy(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "vacancyId" -------------
	var vacancyId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "vacancyId", c.Param("vacancyId"), &vacancyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter vacancyId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListApplicationsForVacancy(c, vacancyId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/me/invitations", wrapper.ListMyInvitationsAsEmployer)
	router.POST(options.BaseURL+"/me/invitations", wrapper.CreateInvitation)
	router.POST(options.BaseURL+"/me/invitations/:id/withdraw", wrapper.WithdrawInvitation)
	router.GET(options.BaseURL+"/me/invitations/incoming", wrapper.ListIncomingInvitations)
	router.POST(options.BaseURL+"/me/invitations/:id/accept", wrapper.AcceptInvitation)
	router.POST(options.BaseURL+"/me/invitations/:id/reject", wrapper.RejectInvitation)
	router.GET(options.BaseURL+"/me/applications", wrapper.ListMyApplicationsAsCandidate)
	router.POST(options.BaseURL+"/me/applications", wrapper.CreateApplication)
	router.GET(options.BaseURL+"/me/vacancies/:vacancyId/applications", wrapper.ListApplicationsForVacancy)
	router.POST(options.BaseURL+"/me/applications/:id/accept", wrapper.AcceptApplication)
	router.POST(options.BaseURL+"/me/applications/:id/reject", wrapper.RejectApplication)
	router.POST(options.BaseURL+"/internal/reveals", wrapper.InternalRecordReveal)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FjRbts2F34Vg/9/qUXuBgyF79xixby1WJG260VgFKx0ErOQKJWk3HqGgdTDgA0dWmAYsJuhewWvSzAv",
	"mZ1XIF9hTzKQlC3ZkmIla5ICvQkU8Yg85/u+85H0EHlRGEcUqOCoNUTc60GIzWM7jgPiYUEiqv+NWRQD",
	"EwTMoIepT3ws4AEH1vH1q92IhVigFkoS4iMHiUEMqIW4YITuoZFjVsJ0UDu6D+w2CAFMx9vxnUWAg2gS",
	"BKirAxlgAX5brEyrc/tIkBDK5ib1UuACi8SUCzQJzepABXJQn8Az0J9gz4NYmEcGT8Czj8+I6PkMP6Oo",
	"Wznrg9g/a9Z97GHq1cNvtHwTPdZ56e9vGqBytG7D0wS4KGG3DPvzZ8LgaUIY+BrB7NNuZYod2idiQ4bn",
	"0h8V2BM3e5hSCPK0QohJoD+BAPYYDpGD4l5ENQtxgIWeuZRKL2EMqDfQc/mwi5NAr7/94EbZ8iFwjveg",
	"FFAK4J9WRZnuOQ4wG9zBz/VnIaEk1MU0lysTKmAPGMpCCd0cWoPaYjJrHK+Tk9WeTyVfQYGcMnFksrga",
	"P1pXTzHk7E6UV1BhEMI4iAbAzlBTTWe7UC1u0F/J8H/2WQfB89jI77Idd2MzmNg1JvPac87XLgvdFIS5",
	"hDOvx7J22oY+4GAbvIj5HRon78hlzyFaoIKIwZmC75vXmWBI5g0OwrmTS5keGGAe0fLPH+WklpvnkVFk",
	"d9PuVqSywHwu/1zly6SKTGkBg5cwIgb39OnMUvMYMAPWTkQv++/WArsvHt7XOjDRqJWOZmD2hIjRSE9M",
	"6G5kepKIQI/cune3cTfd8Rr/7P/c6FABDHsagsY9YH3i6bT7wLixYXRtq7nV1JhGMVAcE9RCn2xd22oi",
	"B8VY9Eyqbg9wIHrf6Oc9MDLTIjO4atLR5+m4BoHHEeW2xI+bTbuxco+R2Po++urLFURQa8d0nEt0ohQH",
	"LjOyNhPEES9ZrZNGWuXbLkCWRuDiRuQP7BGICk15a5iXgfskFY49J+un/zPYRS30Pzc7SLt2lLvFFhut",
	"KkawBEaFsq8Vy5a/yIk8kVP1Qk7kTM71RLrsENxcerwS4tuEizuD3NmPt/nNhVgrgK8NAREQ8k1Y5NZG",
	"2ekUM4YHFpW1gn+VczltyLkayyN5LKfySE5tYDmthdPtBXFaeYquT+07yWMFzxL83qixPFH7ciLfymN5",
	"mIrGQTwJQ8wGi5AU24Y8MsI6kFN5ICdqLCcNOdN/3sqJHVMv5FS9QmWyc4fEH7nWOasbr23GVxmKMcMh",
	"CGActXaGiOjUtXEgB1FszIv4aB1WJwfRpttHt46pyN/UvpzKmXqtxpW9ZYu0x4/qIrfN+HtZ5ILuuZwt",
	"9bAoNNsAN3lIdgrnbf5ZurtdioNkK9cyEMvpH/JYTtT3puCpeu1YR1ltjJl6KQ91B8zl3/LE9MFUHsq/",
	"NttNJ3/suDi3KV6IL9ls8tCf32sWIVM1Vj825EmRIEvDihGpb1GJSF1CvSjU6j9NrZ00KKfZ91GpP6nv",
	"5FweqNfqBwvBSZl0y7u1ynpPMTi9hGZCvZBHal+9NBZ/qMa2A2ba++WRGquXJkr+bjpmnm4Lh/JYvUJO",
	"qbWvdMNVmd5l6L1quyjwUm+3+GBwq7kDWewWt/tq9B6mER8UfnP5p2nYVfTsLxUEuDtc/mgxqn81yF8M",
	"bkXsaztFLTSXy10pqBdyBXmTv3tUHodHa/fR1bv5TlfXxoH1FxgmLEjv4C3XDSIPB72Ii9b15vVP0ag7",
	"+ncA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
