// This file is auto-generated by @hey-api/openapi-ts

export const CandidateProfileSchema = {
    type: 'object',
    properties: {
        userId: {
            type: 'string',
            format: 'uuid'
        },
        firstName: {
            type: ['string', 'null']
        },
        lastName: {
            type: ['string', 'null']
        },
        headline: {
            type: ['string', 'null']
        },
        about: {
            type: ['string', 'null']
        },
        location: {
            type: ['string', 'null']
        },
        yearsExperience: {
            type: ['number', 'null'],
            format: 'float'
        },
        categoryId: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        gradeId: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        specializationId: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        fspMemberId: {
            type: ['string', 'null']
        },
        updatedAt: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['userId', 'updatedAt']
} as const;

export const UpdateProfileRequestSchema = {
    type: 'object',
    properties: {
        firstName: {
            type: 'string'
        },
        lastName: {
            type: 'string'
        },
        headline: {
            type: 'string'
        },
        about: {
            type: 'string'
        },
        location: {
            type: 'string'
        },
        yearsExperience: {
            type: 'number'
        }
    }
} as const;

export const CandidateContactsSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email'
        },
        phone: {
            type: ['string', 'null']
        },
        telegram: {
            type: ['string', 'null']
        },
        github: {
            type: ['string', 'null']
        },
        linkedin: {
            type: ['string', 'null']
        },
        website: {
            type: ['string', 'null'],
            format: 'uri'
        }
    }
} as const;

export const VisibilitySchema = {
    type: 'object',
    properties: {
        contacts: {
            type: 'boolean'
        },
        fsp: {
            type: 'boolean'
        },
        experience: {
            type: 'boolean'
        },
        resume: {
            type: 'boolean'
        }
    }
} as const;

export const ResumeSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        title: {
            type: 'string'
        },
        source: {
            type: 'string',
            enum: ['manual', 'pdf_upload', 'generated']
        },
        isPrimary: {
            type: 'boolean'
        },
        parsed: {
            type: ['object', 'null'],
            additionalProperties: true
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const ResumeInputSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        content: {
            type: 'string'
        },
        isPrimary: {
            type: 'boolean',
            default: false
        }
    },
    required: ['title', 'content']
} as const;

export const ExperienceSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        company: {
            type: 'string'
        },
        position: {
            type: 'string'
        },
        startedAt: {
            type: 'string',
            format: 'date'
        },
        endedAt: {
            type: ['string', 'null'],
            format: 'date'
        },
        description: {
            type: ['string', 'null']
        }
    },
    required: ['id', 'company', 'position', 'startedAt']
} as const;

export const ExperienceInputSchema = {
    type: 'object',
    properties: {
        company: {
            type: 'string'
        },
        position: {
            type: 'string'
        },
        startedAt: {
            type: 'string',
            format: 'date'
        },
        endedAt: {
            type: ['string', 'null'],
            format: 'date'
        },
        description: {
            type: 'string'
        }
    },
    required: ['company', 'position', 'startedAt']
} as const;

export const CandidateTechnologySchema = {
    type: 'object',
    properties: {
        technologyId: {
            type: 'string',
            format: 'uuid'
        },
        level: {
            type: 'integer',
            minimum: 1,
            maximum: 5
        }
    },
    required: ['technologyId']
} as const;

export const CategoryStateSchema = {
    type: 'object',
    properties: {
        categoryId: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        gradeId: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        specializationId: {
            type: ['string', 'null'],
            format: 'uuid'
        },
        history: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    categoryId: {
                        type: 'string',
                        format: 'uuid'
                    },
                    gradeId: {
                        type: 'string',
                        format: 'uuid'
                    },
                    reason: {
                        type: 'string',
                        enum: ['initial_test', 'retake', 'manual']
                    },
                    effectiveFrom: {
                        type: 'string',
                        format: 'date-time'
                    },
                    effectiveTo: {
                        type: ['string', 'null'],
                        format: 'date-time'
                    }
                }
            }
        }
    }
} as const;

export const FSPStateSchema = {
    type: 'object',
    properties: {
        fspMemberId: {
            type: ['string', 'null']
        },
        linkedAt: {
            type: ['string', 'null'],
            format: 'date-time'
        },
        achievements: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/FSPAchievement'
            }
        }
    }
} as const;

export const FSPAchievementSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        externalId: {
            type: ['string', 'null']
        },
        eventName: {
            type: 'string'
        },
        eventDate: {
            type: ['string', 'null'],
            format: 'date'
        },
        place: {
            type: ['integer', 'null']
        },
        category: {
            type: ['string', 'null']
        },
        score: {
            type: ['number', 'null']
        },
        weight: {
            type: 'integer'
        }
    }
} as const;

export const CandidateCardSchema = {
    type: 'object',
    properties: {
        userId: {
            type: 'string',
            format: 'uuid'
        },
        displayName: {
            type: 'string'
        },
        headline: {
            type: ['string', 'null']
        },
        categoryId: {
            type: 'string',
            format: 'uuid'
        },
        gradeId: {
            type: 'string',
            format: 'uuid'
        },
        specializationId: {
            type: 'string',
            format: 'uuid'
        },
        yearsExperience: {
            type: ['number', 'null']
        },
        technologies: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CandidateTechnology'
            }
        },
        fsp: {
            type: 'object',
            properties: {
                hasFSP: {
                    type: 'boolean'
                },
                achievementsCount: {
                    type: 'integer'
                },
                bestPlace: {
                    type: ['integer', 'null']
                }
            }
        },
        contacts: {
            description: 'null, если контакты не раскрыты',
            oneOf: [
                {
                    '$ref': '#/components/schemas/CandidateContacts'
                },
                {
                    type: 'null'
                }
            ]
        }
    }
} as const;