// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options, formDataBodySerializer } from '@hey-api/client-fetch';
import type { HealthzError, HealthzResponse, GetMyProfileError, GetMyProfileResponse, UpdateMyProfileData, UpdateMyProfileError, UpdateMyProfileResponse, GetMyContactsError, GetMyContactsResponse, ReplaceMyContactsData, ReplaceMyContactsError, ReplaceMyContactsResponse, GetMyVisibilityError, GetMyVisibilityResponse, UpdateMyVisibilityData, UpdateMyVisibilityError, UpdateMyVisibilityResponse, ListResumesError, ListResumesResponse, CreateResumeData, CreateResumeError, CreateResumeResponse, UploadResumePdfData, UploadResumePdfError, UploadResumePdfResponse, ListExperiencesError, ListExperiencesResponse, AddExperienceData, AddExperienceError, AddExperienceResponse, ReplaceTechnologiesData, ReplaceTechnologiesError, ReplaceTechnologiesResponse, GetMyCategoryError, GetMyCategoryResponse, GetMyFspError, GetMyFspResponse, LinkFspData, LinkFspError, LinkFspResponse, GetCandidateForEmployerData, GetCandidateForEmployerError, GetCandidateForEmployerResponse } from './types.gen';

export const client = createClient(createConfig());

export const healthz = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthzResponse, HealthzError, ThrowOnError>({
        ...options,
        url: '/healthz'
    });
};

export const getMyProfile = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMyProfileResponse, GetMyProfileError, ThrowOnError>({
        ...options,
        url: '/me/profile'
    });
};

export const updateMyProfile = <ThrowOnError extends boolean = false>(options: Options<UpdateMyProfileData, ThrowOnError>) => {
    return (options?.client ?? client).patch<UpdateMyProfileResponse, UpdateMyProfileError, ThrowOnError>({
        ...options,
        url: '/me/profile'
    });
};

export const getMyContacts = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMyContactsResponse, GetMyContactsError, ThrowOnError>({
        ...options,
        url: '/me/contacts'
    });
};

export const replaceMyContacts = <ThrowOnError extends boolean = false>(options: Options<ReplaceMyContactsData, ThrowOnError>) => {
    return (options?.client ?? client).put<ReplaceMyContactsResponse, ReplaceMyContactsError, ThrowOnError>({
        ...options,
        url: '/me/contacts'
    });
};

export const getMyVisibility = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMyVisibilityResponse, GetMyVisibilityError, ThrowOnError>({
        ...options,
        url: '/me/visibility'
    });
};

export const updateMyVisibility = <ThrowOnError extends boolean = false>(options: Options<UpdateMyVisibilityData, ThrowOnError>) => {
    return (options?.client ?? client).put<UpdateMyVisibilityResponse, UpdateMyVisibilityError, ThrowOnError>({
        ...options,
        url: '/me/visibility'
    });
};

export const listResumes = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ListResumesResponse, ListResumesError, ThrowOnError>({
        ...options,
        url: '/me/resumes'
    });
};

export const createResume = <ThrowOnError extends boolean = false>(options: Options<CreateResumeData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateResumeResponse, CreateResumeError, ThrowOnError>({
        ...options,
        url: '/me/resumes'
    });
};

/**
 * Загрузка PDF с автораспознаванием
 */
export const uploadResumePdf = <ThrowOnError extends boolean = false>(options: Options<UploadResumePdfData, ThrowOnError>) => {
    return (options?.client ?? client).post<UploadResumePdfResponse, UploadResumePdfError, ThrowOnError>({
        ...options,
        ...formDataBodySerializer,
        headers: {
            'Content-Type': null,
            ...options?.headers
        },
        url: '/me/resumes/upload'
    });
};

export const listExperiences = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ListExperiencesResponse, ListExperiencesError, ThrowOnError>({
        ...options,
        url: '/me/experiences'
    });
};

export const addExperience = <ThrowOnError extends boolean = false>(options: Options<AddExperienceData, ThrowOnError>) => {
    return (options?.client ?? client).post<AddExperienceResponse, AddExperienceError, ThrowOnError>({
        ...options,
        url: '/me/experiences'
    });
};

export const replaceTechnologies = <ThrowOnError extends boolean = false>(options: Options<ReplaceTechnologiesData, ThrowOnError>) => {
    return (options?.client ?? client).put<ReplaceTechnologiesResponse, ReplaceTechnologiesError, ThrowOnError>({
        ...options,
        url: '/me/technologies'
    });
};

export const getMyCategory = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMyCategoryResponse, GetMyCategoryError, ThrowOnError>({
        ...options,
        url: '/me/category'
    });
};

export const getMyFsp = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMyFspResponse, GetMyFspError, ThrowOnError>({
        ...options,
        url: '/me/fsp'
    });
};

export const linkFsp = <ThrowOnError extends boolean = false>(options: Options<LinkFspData, ThrowOnError>) => {
    return (options?.client ?? client).put<LinkFspResponse, LinkFspError, ThrowOnError>({
        ...options,
        url: '/me/fsp'
    });
};

/**
 * Возвращает карточку без контактов. Контакты появятся только после accepted.
 */
export const getCandidateForEmployer = <ThrowOnError extends boolean = false>(options: Options<GetCandidateForEmployerData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCandidateForEmployerResponse, GetCandidateForEmployerError, ThrowOnError>({
        ...options,
        url: '/candidates/{userId}'
    });
};