// This file is auto-generated by @hey-api/openapi-ts

export type CandidateCard = {
    userId?: string;
    displayName?: string;
    headline?: (string) | null;
    categoryId?: string;
    gradeId?: string;
    specializationId?: string;
    yearsExperience?: (number) | null;
    technologies?: Array<CandidateTechnology>;
    fsp?: {
        hasFSP?: boolean;
        achievementsCount?: number;
        bestPlace?: (number) | null;
    };
    /**
     * null, если контакты не раскрыты
     */
    contacts?: (CandidateContacts | null);
};

export type CandidateContacts = {
    email?: string;
    phone?: (string) | null;
    telegram?: (string) | null;
    github?: (string) | null;
    linkedin?: (string) | null;
    website?: (string) | null;
};

export type CandidateProfile = {
    userId: string;
    firstName?: (string) | null;
    lastName?: (string) | null;
    headline?: (string) | null;
    about?: (string) | null;
    location?: (string) | null;
    yearsExperience?: (number) | null;
    categoryId?: (string) | null;
    gradeId?: (string) | null;
    specializationId?: (string) | null;
    fspMemberId?: (string) | null;
    updatedAt: string;
};

export type CandidateTechnology = {
    technologyId: string;
    level?: number;
};

export type CategoryState = {
    categoryId?: (string) | null;
    gradeId?: (string) | null;
    specializationId?: (string) | null;
    history?: Array<{
        categoryId?: string;
        gradeId?: string;
        reason?: 'initial_test' | 'retake' | 'manual';
        effectiveFrom?: string;
        effectiveTo?: (string) | null;
    }>;
};

export type Experience = {
    id: string;
    company: string;
    position: string;
    startedAt: string;
    endedAt?: (string) | null;
    description?: (string) | null;
};

export type ExperienceInput = {
    company: string;
    position: string;
    startedAt: string;
    endedAt?: (string) | null;
    description?: string;
};

export type FSPAchievement = {
    id?: string;
    externalId?: (string) | null;
    eventName?: string;
    eventDate?: (string) | null;
    place?: (number) | null;
    category?: (string) | null;
    score?: (number) | null;
    weight?: number;
};

export type FSPState = {
    fspMemberId?: (string) | null;
    linkedAt?: (string) | null;
    achievements?: Array<FSPAchievement>;
};

export type Resume = {
    id?: string;
    title?: string;
    source?: 'manual' | 'pdf_upload' | 'generated';
    isPrimary?: boolean;
    parsed?: {
        [key: string]: unknown;
    } | null;
    createdAt?: string;
};

export type source = 'manual' | 'pdf_upload' | 'generated';

export type ResumeInput = {
    title: string;
    content: string;
    isPrimary?: boolean;
};

export type UpdateProfileRequest = {
    firstName?: string;
    lastName?: string;
    headline?: string;
    about?: string;
    location?: string;
    yearsExperience?: number;
};

export type Visibility = {
    contacts?: boolean;
    fsp?: boolean;
    experience?: boolean;
    resume?: boolean;
};

export type HealthzResponse = (unknown);

export type HealthzError = unknown;

export type GetMyProfileResponse = (CandidateProfile);

export type GetMyProfileError = unknown;

export type UpdateMyProfileData = {
    body: UpdateProfileRequest;
};

export type UpdateMyProfileResponse = (CandidateProfile);

export type UpdateMyProfileError = unknown;

export type GetMyContactsResponse = (CandidateContacts);

export type GetMyContactsError = unknown;

export type ReplaceMyContactsData = {
    body: CandidateContacts;
};

export type ReplaceMyContactsResponse = (CandidateContacts);

export type ReplaceMyContactsError = unknown;

export type GetMyVisibilityResponse = (Visibility);

export type GetMyVisibilityError = unknown;

export type UpdateMyVisibilityData = {
    body: Visibility;
};

export type UpdateMyVisibilityResponse = (unknown);

export type UpdateMyVisibilityError = unknown;

export type ListResumesResponse = (Array<Resume>);

export type ListResumesError = unknown;

export type CreateResumeData = {
    body: ResumeInput;
};

export type CreateResumeResponse = (Resume);

export type CreateResumeError = unknown;

export type UploadResumePdfData = {
    body: {
        file: (Blob | File);
    };
};

export type UploadResumePdfResponse = (Resume);

export type UploadResumePdfError = unknown;

export type ListExperiencesResponse = (Array<Experience>);

export type ListExperiencesError = unknown;

export type AddExperienceData = {
    body: ExperienceInput;
};

export type AddExperienceResponse = (Experience);

export type AddExperienceError = unknown;

export type ReplaceTechnologiesData = {
    body: Array<CandidateTechnology>;
};

export type ReplaceTechnologiesResponse = (unknown);

export type ReplaceTechnologiesError = unknown;

export type GetMyCategoryResponse = (CategoryState);

export type GetMyCategoryError = unknown;

export type GetMyFspResponse = (FSPState);

export type GetMyFspError = unknown;

export type LinkFspData = {
    body: {
        fspMemberId: string;
    };
};

export type LinkFspResponse = (unknown);

export type LinkFspError = unknown;

export type GetCandidateForEmployerData = {
    path: {
        userId: string;
    };
    query?: {
        /**
         * Показывать ли контакты (только при accepted-приглашении/отклике)
         */
        revealContacts?: boolean;
    };
};

export type GetCandidateForEmployerResponse = (CandidateCard);

export type GetCandidateForEmployerError = (unknown);