// Package apicandidate provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apicandidate

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CategoryStateHistoryReason.
const (
	CategoryStateHistoryReasonInitialTest CategoryStateHistoryReason = "initial_test"
	CategoryStateHistoryReasonManual      CategoryStateHistoryReason = "manual"
	CategoryStateHistoryReasonRetake      CategoryStateHistoryReason = "retake"
)

// Valid indicates whether the value is a known member of the CategoryStateHistoryReason enum.
func (e CategoryStateHistoryReason) Valid() bool {
	switch e {
	case CategoryStateHistoryReasonInitialTest:
		return true
	case CategoryStateHistoryReasonManual:
		return true
	case CategoryStateHistoryReasonRetake:
		return true
	default:
		return false
	}
}

// Defines values for ResumeSource.
const (
	ResumeSourceGenerated ResumeSource = "generated"
	ResumeSourceManual    ResumeSource = "manual"
	ResumeSourcePdfUpload ResumeSource = "pdf_upload"
)

// Valid indicates whether the value is a known member of the ResumeSource enum.
func (e ResumeSource) Valid() bool {
	switch e {
	case ResumeSourceGenerated:
		return true
	case ResumeSourceManual:
		return true
	case ResumeSourcePdfUpload:
		return true
	default:
		return false
	}
}

// Defines values for InternalRecordRevealJSONBodyEntityType.
const (
	Application InternalRecordRevealJSONBodyEntityType = "application"
	Invitation  InternalRecordRevealJSONBodyEntityType = "invitation"
)

// Valid indicates whether the value is a known member of the InternalRecordRevealJSONBodyEntityType enum.
func (e InternalRecordRevealJSONBodyEntityType) Valid() bool {
	switch e {
	case Application:
		return true
	case Invitation:
		return true
	default:
		return false
	}
}

// Defines values for InternalRecordRevealJSONBodyReason.
const (
	ApplicationSent    InternalRecordRevealJSONBodyReason = "application_sent"
	InvitationAccepted InternalRecordRevealJSONBodyReason = "invitation_accepted"
)

// Valid indicates whether the value is a known member of the InternalRecordRevealJSONBodyReason enum.
func (e InternalRecordRevealJSONBodyReason) Valid() bool {
	switch e {
	case ApplicationSent:
		return true
	case InvitationAccepted:
		return true
	default:
		return false
	}
}

// CandidateCard defines model for CandidateCard.
type CandidateCard struct {
	CategoryId       *openapi_types.UUID    `json:"categoryId,omitempty"`
	Contacts         *CandidateContacts     `json:"contacts,omitempty"`
	DisplayName      *string                `json:"displayName,omitempty"`
	Fsp              *CandidateCardFsp      `json:"fsp,omitempty"`
	GradeId          *openapi_types.UUID    `json:"gradeId,omitempty"`
	Headline         *string                `json:"headline,omitempty"`
	Location         *string                `json:"location,omitempty"`
	Salary           *CandidateCardSalary   `json:"salary,omitempty"`
	SoftSkills       *[]string              `json:"softSkills,omitempty"`
	SpecializationId *openapi_types.UUID    `json:"specializationId,omitempty"`
	Technologies     *[]CandidateTechnology `json:"technologies,omitempty"`
	UserId           *openapi_types.UUID    `json:"userId,omitempty"`
	YearsExperience  *float32               `json:"yearsExperience,omitempty"`
}

// CandidateCardFsp defines model for CandidateCardFsp.
type CandidateCardFsp struct {
	AchievementsCount *int  `json:"achievementsCount,omitempty"`
	BestPlace         *int  `json:"bestPlace,omitempty"`
	HasFSP            *bool `json:"hasFSP,omitempty"`
}

// CandidateCardSalary defines model for CandidateCardSalary.
type CandidateCardSalary struct {
	Currency *string `json:"currency,omitempty"`
	Masked   *bool   `json:"masked,omitempty"`
	Max      *int    `json:"max,omitempty"`
	Min      *int    `json:"min,omitempty"`
}

// CandidateContacts defines model for CandidateContacts.
type CandidateContacts struct {
	Email        *openapi_types.Email `json:"email,omitempty"`
	Github       *string              `json:"github,omitempty"`
	Linkedin     *string              `json:"linkedin,omitempty"`
	Masked       *bool                `json:"masked,omitempty"`
	MaskedFields *[]string            `json:"maskedFields,omitempty"`
	Phone        *string              `json:"phone,omitempty"`
	Telegram     *string              `json:"telegram,omitempty"`
	Website      *string              `json:"website,omitempty"`
}

// CandidateProfile defines model for CandidateProfile.
type CandidateProfile struct {
	About            *string             `json:"about,omitempty"`
	CategoryId       *openapi_types.UUID `json:"categoryId,omitempty"`
	FirstName        *string             `json:"firstName,omitempty"`
	FspMemberId      *string             `json:"fspMemberId,omitempty"`
	GradeId          *openapi_types.UUID `json:"gradeId,omitempty"`
	Headline         *string             `json:"headline,omitempty"`
	LastName         *string             `json:"lastName,omitempty"`
	Location         *string             `json:"location,omitempty"`
	MiddleName       *string             `json:"middleName,omitempty"`
	SalaryCurrency   *string             `json:"salaryCurrency,omitempty"`
	SalaryMax        *int                `json:"salaryMax,omitempty"`
	SalaryMin        *int                `json:"salaryMin,omitempty"`
	SoftSkills       *[]string           `json:"softSkills,omitempty"`
	SpecializationId *openapi_types.UUID `json:"specializationId,omitempty"`
	UpdatedAt        time.Time           `json:"updatedAt"`
	UserId           openapi_types.UUID  `json:"userId"`
	YearsExperience  *float32            `json:"yearsExperience,omitempty"`
}

// CandidateTechnology defines model for CandidateTechnology.
type CandidateTechnology struct {
	Level        *int               `json:"level,omitempty"`
	TechnologyId openapi_types.UUID `json:"technologyId"`
}

// CategoryState defines model for CategoryState.
type CategoryState struct {
	CategoryId *openapi_types.UUID `json:"categoryId,omitempty"`
	GradeId    *openapi_types.UUID `json:"gradeId,omitempty"`
	History    *[]struct {
		CategoryId    *openapi_types.UUID         `json:"categoryId,omitempty"`
		EffectiveFrom *time.Time                  `json:"effectiveFrom,omitempty"`
		EffectiveTo   *time.Time                  `json:"effectiveTo,omitempty"`
		GradeId       *openapi_types.UUID         `json:"gradeId,omitempty"`
		Reason        *CategoryStateHistoryReason `json:"reason,omitempty"`
	} `json:"history,omitempty"`
	SpecializationId *openapi_types.UUID `json:"specializationId,omitempty"`
}

// CategoryStateHistoryReason defines model for CategoryState.History.Reason.
type CategoryStateHistoryReason string

// Experience defines model for Experience.
type Experience struct {
	Company     string              `json:"company"`
	Description *string             `json:"description,omitempty"`
	EndedAt     *openapi_types.Date `json:"endedAt,omitempty"`
	Id          openapi_types.UUID  `json:"id"`
	Position    string              `json:"position"`
	StartedAt   openapi_types.Date  `json:"startedAt"`
}

// ExperienceInput defines model for ExperienceInput.
type ExperienceInput struct {
	Company     string              `json:"company"`
	Description *string             `json:"description,omitempty"`
	EndedAt     *openapi_types.Date `json:"endedAt,omitempty"`
	Position    string              `json:"position"`
	StartedAt   openapi_types.Date  `json:"startedAt"`
}

// FSPAchievement defines model for FSPAchievement.
type FSPAchievement struct {
	Category   *string             `json:"category,omitempty"`
	EventDate  *openapi_types.Date `json:"eventDate,omitempty"`
	EventName  *string             `json:"eventName,omitempty"`
	ExternalId *string             `json:"externalId,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Place      *int                `json:"place,omitempty"`
	Score      *float32            `json:"score,omitempty"`
	Weight     *int                `json:"weight,omitempty"`
}

// FSPState defines model for FSPState.
type FSPState struct {
	Achievements *[]FSPAchievement `json:"achievements,omitempty"`
	FspMemberId  *string           `json:"fspMemberId,omitempty"`
	LinkedAt     *time.Time        `json:"linkedAt,omitempty"`
}

// Resume defines model for Resume.
type Resume struct {
	CreatedAt *time.Time              `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID     `json:"id,omitempty"`
	IsPrimary *bool                   `json:"isPrimary,omitempty"`
	Parsed    *map[string]interface{} `json:"parsed,omitempty"`
	Source    *ResumeSource           `json:"source,omitempty"`
	Title     *string                 `json:"title,omitempty"`
}

// ResumeSource defines model for Resume.Source.
type ResumeSource string

// ResumeInput defines model for ResumeInput.
type ResumeInput struct {
	Content   string `json:"content"`
	IsPrimary *bool  `json:"isPrimary,omitempty"`
	Title     string `json:"title"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	About           *string   `json:"about,omitempty"`
	FirstName       *string   `json:"firstName,omitempty"`
	Headline        *string   `json:"headline,omitempty"`
	LastName        *string   `json:"lastName,omitempty"`
	Location        *string   `json:"location,omitempty"`
	MiddleName      *string   `json:"middleName,omitempty"`
	SalaryCurrency  *string   `json:"salaryCurrency,omitempty"`
	SalaryMax       *int      `json:"salaryMax,omitempty"`
	SalaryMin       *int      `json:"salaryMin,omitempty"`
	SoftSkills      *[]string `json:"softSkills,omitempty"`
	YearsExperience *float32  `json:"yearsExperience,omitempty"`
}

// Visibility defines model for Visibility.
type Visibility struct {
	Contacts   *bool `json:"contacts,omitempty"`
	Experience *bool `json:"experience,omitempty"`
	Fsp        *bool `json:"fsp,omitempty"`
	Links      *bool `json:"links,omitempty"`
	Resume     *bool `json:"resume,omitempty"`
	Salary     *bool `json:"salary,omitempty"`
	SoftSkills *bool `json:"softSkills,omitempty"`
}

// InternalRecordRevealJSONBody defines parameters for InternalRecordReveal.
type InternalRecordRevealJSONBody struct {
	CandidateUserId openapi_types.UUID                     `json:"candidateUserId"`
	EmployerUserId  openapi_types.UUID                     `json:"employerUserId"`
	EntityId        openapi_types.UUID                     `json:"entityId"`
	EntityType      InternalRecordRevealJSONBodyEntityType `json:"entityType"`
	Reason          InternalRecordRevealJSONBodyReason     `json:"reason"`
}

// InternalRecordRevealParams defines parameters for InternalRecordReveal.
type InternalRecordRevealParams struct {
	XInternalToken string `json:"X-Internal-Token"`
}

// InternalRecordRevealJSONBodyEntityType defines parameters for InternalRecordReveal.
type InternalRecordRevealJSONBodyEntityType string

// InternalRecordRevealJSONBodyReason defines parameters for InternalRecordReveal.
type InternalRecordRevealJSONBodyReason string

// LinkFSPJSONBody defines parameters for LinkFSP.
type LinkFSPJSONBody struct {
	FspMemberId string `json:"fspMemberId"`
}

// UploadResumePDFMultipartBody defines parameters for UploadResumePDF.
type UploadResumePDFMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// ReplaceTechnologiesJSONBody defines parameters for ReplaceTechnologies.
type ReplaceTechnologiesJSONBody = []CandidateTechnology

// InternalRecordRevealJSONRequestBody defines body for InternalRecordReveal for application/json ContentType.
type InternalRecordRevealJSONRequestBody InternalRecordRevealJSONBody

// ReplaceMyContactsJSONRequestBody defines body for ReplaceMyContacts for application/json ContentType.
type ReplaceMyContactsJSONRequestBody = CandidateContacts

// AddExperienceJSONRequestBody defines body for AddExperience for application/json ContentType.
type AddExperienceJSONRequestBody = ExperienceInput

// LinkFSPJSONRequestBody defines body for LinkFSP for application/json ContentType.
type LinkFSPJSONRequestBody LinkFSPJSONBody

// UpdateMyProfileJSONRequestBody defines body for UpdateMyProfile for application/json ContentType.
type UpdateMyProfileJSONRequestBody = UpdateProfileRequest

// CreateResumeJSONRequestBody defines body for CreateResume for application/json ContentType.
type CreateResumeJSONRequestBody = ResumeInput

// UploadResumePDFMultipartRequestBody defines body for UploadResumePDF for multipart/form-data ContentType.
type UploadResumePDFMultipartRequestBody UploadResumePDFMultipartBody

// ReplaceTechnologiesJSONRequestBody defines body for ReplaceTechnologies for application/json ContentType.
type ReplaceTechnologiesJSONRequestBody = ReplaceTechnologiesJSONBody

// UpdateMyVisibilityJSONRequestBody defines body for UpdateMyVisibility for application/json ContentType.
type UpdateMyVisibilityJSONRequestBody = Visibility

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /candidates/{userId})
	GetCandidateForEmployer(c *gin.Context, userId openapi_types.UUID)

	// (GET /healthz)
	Healthz(c *gin.Context)

	// (POST /internal/reveals)
	InternalRecordReveal(c *gin.Context, params InternalRecordRevealParams)

	// (GET /me/category)
	GetMyCategory(c *gin.Context)

	// (GET /me/contacts)
	GetMyContacts(c *gin.Context)

	// (PUT /me/contacts)
	ReplaceMyContacts(c *gin.Context)

	// (GET /me/experiences)
	ListExperiences(c *gin.Context)

	// (POST /me/experiences)
	AddExperience(c *gin.Context)

	// (GET /me/fsp)
	GetMyFSP(c *gin.Context)

	// (PUT /me/fsp)
	LinkFSP(c *gin.Context)

	// (GET /me/profile)
	GetMyProfile(c *gin.Context)

	// (PATCH /me/profile)
	UpdateMyProfile(c *gin.Context)

	// (GET /me/resumes)
	ListResumes(c *gin.Context)

	// (POST /me/resumes)
	CreateResume(c *gin.Context)

	// (POST /me/resumes/upload)
	UploadResumePDF(c *gin.Context)

	// (PUT /me/technologies)
	ReplaceTechnologies(c *gin.Context)

	// (GET /me/visibility)
	GetMyVisibility(c *gin.Context)

	// (PUT /me/visibility)
	UpdateMyVisibility(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetCandidateForEmployer operation middleware
func (siw *ServerInterfaceWrapper) GetCandidateForEmployer(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCandidateForEmployer(c, userId)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// InternalRecordReveal operation middleware
func (siw *ServerInterfaceWrapper) InternalRecordReveal(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params InternalRecordRevealParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Internal-Token" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Internal-Token")]; found {
		var XInternalToken string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Internal-Token, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Internal-Token", valueList[0], &XInternalToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Internal-Token: %w", err), http.StatusBadRequest)
			return
		}

		params.XInternalToken = XInternalToken

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Internal-Token is required, but not found"), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.InternalRecordReveal(c, params)
}

// GetMyCategory operation middleware
func (siw *ServerInterfaceWrapper) GetMyCategory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyCategory(c)
}

// GetMyContacts operation middleware
func (siw *ServerInterfaceWrapper) GetMyContacts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyContacts(c)
}

// ReplaceMyContacts operation middleware
func (siw *ServerInterfaceWrapper) ReplaceMyContacts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReplaceMyContacts(c)
}

// ListExperiences operation middleware
func (siw *ServerInterfaceWrapper) ListExperiences(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListExperiences(c)
}

// AddExperience operation middleware
func (siw *ServerInterfaceWrapper) AddExperience(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddExperience(c)
}

// GetMyFSP operation middleware
func (siw *ServerInterfaceWrapper) GetMyFSP(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyFSP(c)
}

// LinkFSP operation middleware
func (siw *ServerInterfaceWrapper) LinkFSP(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LinkFSP(c)
}

// GetMyProfile operation middleware
func (siw *ServerInterfaceWrapper) GetMyProfile(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyProfile(c)
}

// UpdateMyProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdateMyProfile(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMyProfile(c)
}

// ListResumes operation middleware
func (siw *ServerInterfaceWrapper) ListResumes(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListResumes(c)
}

// CreateResume operation middleware
func (siw *ServerInterfaceWrapper) CreateResume(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateResume(c)
}

// UploadResumePDF operation middleware
func (siw *ServerInterfaceWrapper) UploadResumePDF(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UploadResumePDF(c)
}

// ReplaceTechnologies operation middleware
func (siw *ServerInterfaceWrapper) ReplaceTechnologies(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReplaceTechnologies(c)
}

// GetMyVisibility operation middleware
func (siw *ServerInterfaceWrapper) GetMyVisibility(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyVisibility(c)
}

// UpdateMyVisibility operation middleware
func (siw *ServerInterfaceWrapper) UpdateMyVisibility(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMyVisibility(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/me/profile", wrapper.GetMyProfile)
	router.PATCH(options.BaseURL+"/me/profile", wrapper.UpdateMyProfile)
	router.GET(options.BaseURL+"/me/contacts", wrapper.GetMyContacts)
	router.PUT(options.BaseURL+"/me/contacts", wrapper.ReplaceMyContacts)
	router.GET(options.BaseURL+"/me/visibility", wrapper.GetMyVisibility)
	router.PUT(options.BaseURL+"/me/visibility", wrapper.UpdateMyVisibility)
	router.GET(options.BaseURL+"/me/resumes", wrapper.ListResumes)
	router.POST(options.BaseURL+"/me/resumes", wrapper.CreateResume)
	router.POST(options.BaseURL+"/me/resumes/upload", wrapper.UploadResumePDF)
	router.GET(options.BaseURL+"/me/experiences", wrapper.ListExperiences)
	router.POST(options.BaseURL+"/me/experiences", wrapper.AddExperience)
	router.PUT(options.BaseURL+"/me/technologies", wrapper.ReplaceTechnologies)
	router.GET(options.BaseURL+"/me/category", wrapper.GetMyCategory)
	router.GET(options.BaseURL+"/me/fsp", wrapper.GetMyFSP)
	router.PUT(options.BaseURL+"/me/fsp", wrapper.LinkFSP)
	router.GET(options.BaseURL+"/candidates/:userId", wrapper.GetCandidateForEmployer)
	router.POST(options.BaseURL+"/internal/reveals", wrapper.InternalRecordReveal)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFrrbhvHFX6VxbY/WoAS5dgFAvWXY1up2rgVJLktYAvGaHcoTrQ3z86qZgwBuhRIC7kRWgQoEMB1EvQB",
	"aFm0aVmiX+HMK/RJijOzXM6SwyUlS8ofQ+TczuU737nQz1wvDpM4opFI3flnbuo1aUjUn3dI5DOfCHqH",
	"cB+/SHicUC4YVcseEXQj5q1FtdaIeUiEO+9mGfPdmitaCXXnH7qp4CzacGtulAWBu7Zdc704EsTTr/2c",
	"04Y77/6sPhCinktQHzzfP7Bdc32WJgFp/Z6EFM/rV/qPbNfcRppMfy/h/kKa4LENTnx6XkWalPgBiwxB",
	"bLuC2COCxVH1rpQEhLfOJfqKPoKH44ZY2WRBoGzKBA1Tq3HyLwjnRJ9LqMdIwL5SAp5XfUG9ZhQH8UaO",
	"h+LdqTRY7Z9u2STLUsqr5DGUalHC03tPE8oZjbySM6IsXKd8IPPgoXj9S+oJPD6ChhGcE6/J6BYNUY87",
	"cRYJw7YsEnSDcrxonaZiKSBlCfrrJmpIurCyZNyxHscBJZE7WbyVAiRDkZhxTiOvVQ2xkKSb1Lc9jGtP",
	"J4gdsqhyR7XwRsiXRachYUHJz/qbKuBtMNHM1idEHYs2qc+ijzEJri0wGvjnDKukGU8iBUEDusFJWL3r",
	"L3Q9ZYKWw4CzCuNUemGJxw0WUAvC1+NMVItyUbJvMJ6KMltbt6XJfYrBuuhXb7xKoibTSDodnYfM9wM6",
	"+TZN+3eM+PVpg2QBqrX84LNKrfTZ+zpyQxaxMAvd+blaVRTnZ3RcTHtmyuwSkqeLevGTucvONVmCAPZv",
	"i9Ix/G5GsJDa8sLHpZDiTCOIiTBks+QUTp9kjCOPPOy/akq8VhWTRhocCcuAblHFjSF5qh31q9rAaTdq",
	"liRU5OTWVKoPCV86bRdbs8CKIIJeXkV4saBmqYh1NiwweX5xDBTQRoN6gm3RBR6H0+OsOLYaTzh0IdWN",
	"lzglqSYeGiECMFqZYCR4LGiKGOVUkE18LyRRRgLDhYbDR5x6mZFqu78cWEMuisOERC0rn/g09ThLJpMt",
	"jXwrNVQank1n8yROWVkCYzEVhIvqp8eFmnqtr73xjHnpWqUxF6NEJ+2PtKgJ5YsY8qosdAHjLKws3R4U",
	"6+MJYQKctmgk7pKhumuiHdSxsX0pfSooj0gwqb6ZFpZTNBqpF/PKdggLTLbRtPYz23bzjiF+s0WauhUc",
	"8paFiaauCnW1P7E6mI6vlmmahTau4vS8NciU3mTpEmchMYFpdiIJ4anuUojvq0ggwZIhmuAZHaiYK1Iq",
	"4DKu0dLPG3l+qLmJ33icJUFMUK4NGlGOKloSR80VTAQ2bI834ViGigQtddFjLFGUwg0SpIWGpmUqZCrV",
	"NWpbrXjZxh0PEqNFWqZPMkypkzolc/A02ugYq6MdiLE42niYiyP9hllyW9oMk31HuosxW8Y2EWZtOaF3",
	"KG29lJbBUpZbns1ZzYrDP7KUrbOAiZYdhv2ZxCiyqGWgZK7nc8bRBaSiMXfyglhG1wbzP8tayZqTp0Z4",
	"hHoZZ6K1glyr9V2nhFN+OxPNwaeFPjP99k+rmF3VbrxcrQ6oqilE4m7jxSxqqDI3jzzMCc5SQARynPO/",
	"nW+dorNxVijfYh7G3RblqYKwe2N2bnYOdYoTGpGEufPuzdkbs3NIRUQ0laB1r39FWn+m+6lt/H6DCs0K",
	"RhHjwr+gB2/hSO5AW/4d2tCRew6cQFvuyD3oya/hRO6rL+AMjqELx9CWe9CedeA76MEZ/g0nck8eOHAK",
	"bbkLJ9CVO3JffiP35K48rDnQkbvwHroOnOHtjyLieTQR1J+BD3IHuvAa3kNb/g06cAZdeehAV2/vyT04",
	"wT/xeby+A2/gWO478h9yD7pw6qDU8Ept7OWSdeA9dODUwQuGpe7B6eyjCL7XcsodeaDu6TjQU6J04BjP",
	"y0OUE4V35C505A4cqX97eO0H6Dk59B9zukVJkP7aeZJR3pqBD2g2aKOkck8dOHLgGC/UIvfgNfRyM8w+",
	"wnoMA6poE9zPqSjcvxDze2ESxC2Fo4RwElJBeerOP3zmIocoh2OaUuw1aJwHxK3zmi4Xpmlm11SIJXGU",
	"asR/Mjc3lG9IkgRM82n9y7yXGtw/9eRdh8IQEL8zMYf+HsEc4v7W3E0LiH+EHryXz+EEzZsbfBw03ulr",
	"blmueYFQOIM2vFNAOINeiQyU6U0aeLi2rUqgepOSQDS/MqKs7Njf5Ot2A5el+MPvhh/Vb2B6wAq4nqNO",
	"MXKcWmNaHsBbeQBHOp4VktVx4uGWmQLVXbmboxoD0akMTAwoFZiPIrmrQN6Tu8pfh9q28jlaDG8zA7dj",
	"J4+XeBr9YUaG3WfyuSP3UVi8QrNTiXhskbSYG2uZejH3l5XFxoQRlha6qteB9OeZ/uGZ1XiTRpUhZQ0h",
	"Vft8Fvutc0XPcKuVx8uD6cdwNOeL8xyJBBOtc21eVV+bM5QtJkjeXxoqWotg2wimf/xxH37lex6n5ZJz",
	"XLs7ZLARc5TkNzQvhBqtastvoO+3RyL4lj2CxzHVC+jk2eRMHsA7px/VMwrzJxhq+C4GfEjrZsNtJZbP",
	"qbjf6k8V3Svlb3NyaePvH6GDtQIWEZjDT/LwfQ095BJ5WIfXKsW+g2OVnLs5e6hFU2ejrqzQub/rWnJW",
	"8QO6NW+V2EjvyRu3suDLVI0dhoS/GFtcQO5JSL5uw/0HXqmEcaTSsk62fRAM2ofxOPiCpeKese8jFZpq",
	"5mJ0UyPzFquKH7DGNBJbAZA8c5dVuu37xgtXg47hCehU2LhxBc9bLfYt9OAVtK2gyHvG8aSwsLJ0lXxQ",
	"zO9sgr9UFdORPIS3efnqwH/hB3jpLN5VfHec10tdeFN0Or/AKgo/Y1nzCqEin2Mxto875QGc/rKCTr5g",
	"0WZf48soOazTwnHp1tx8scRpKX1LRmwPeT8Z/Po+HgH9n+ivg9z6b41DQ0/+FQtm9KillVFuJcJrjmqi",
	"R2llZS6fB6wDu58qUVTZ0sgT8p9wlhdOqkUpTGzgRE+JqtPGcr7nOlJGPg6fJl18Dx14K7+BU+hUZYk7",
	"apCe33s14DAH0NecIPr2stjnBzWrOh6hhtzl9XwSP74x/je0sQqV+zlJL91dcOSug/kmr0Xbchc+qGfO",
	"VBZqq9a3A6cjLeYD9ZiWdunuQqUjwiwQLCFc1LHJmvGJIJVMnPNc0ZGts4io+n4CKeO5i7HxtfjPwLej",
	"Jg+FM2tqsKbmAfrXGr1+rDqlN7rt78JbXRbIrwse6Dj5DeqDAYnh/1xZVZCvmnsvHk+X9/83L5o+qyrq",
	"rdIof3wGNUb+V0j8xis2oLzAOMxHqO/gBMunfP5TjJ26FZVRP4EO6XL5NDmsxuU5bdLYEZf5Vn+QlfEg",
	"/5Vhvl4PYo8EzTgV85/OfXrT3V7b/n8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
