// Package apicandidate provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apicandidate

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CategoryStateHistoryReason.
const (
	CategoryStateHistoryReasonInitialTest CategoryStateHistoryReason = "initial_test"
	CategoryStateHistoryReasonManual      CategoryStateHistoryReason = "manual"
	CategoryStateHistoryReasonRetake      CategoryStateHistoryReason = "retake"
)

// Valid indicates whether the value is a known member of the CategoryStateHistoryReason enum.
func (e CategoryStateHistoryReason) Valid() bool {
	switch e {
	case CategoryStateHistoryReasonInitialTest:
		return true
	case CategoryStateHistoryReasonManual:
		return true
	case CategoryStateHistoryReasonRetake:
		return true
	default:
		return false
	}
}

// Defines values for ResumeSource.
const (
	ResumeSourceGenerated ResumeSource = "generated"
	ResumeSourceManual    ResumeSource = "manual"
	ResumeSourcePdfUpload ResumeSource = "pdf_upload"
)

// Valid indicates whether the value is a known member of the ResumeSource enum.
func (e ResumeSource) Valid() bool {
	switch e {
	case ResumeSourceGenerated:
		return true
	case ResumeSourceManual:
		return true
	case ResumeSourcePdfUpload:
		return true
	default:
		return false
	}
}

// CandidateCard defines model for CandidateCard.
type CandidateCard struct {
	CategoryId *openapi_types.UUID `json:"categoryId,omitempty"`

	// Contacts null, если контакты не раскрыты
	Contacts    *CandidateContacts `json:"contacts,omitempty"`
	DisplayName *string            `json:"displayName,omitempty"`
	Fsp         *struct {
		AchievementsCount *int  `json:"achievementsCount,omitempty"`
		BestPlace         *int  `json:"bestPlace,omitempty"`
		HasFSP            *bool `json:"hasFSP,omitempty"`
	} `json:"fsp,omitempty"`
	GradeId          *openapi_types.UUID    `json:"gradeId,omitempty"`
	Headline         *string                `json:"headline,omitempty"`
	SpecializationId *openapi_types.UUID    `json:"specializationId,omitempty"`
	Technologies     *[]CandidateTechnology `json:"technologies,omitempty"`
	UserId           *openapi_types.UUID    `json:"userId,omitempty"`
	YearsExperience  *float32               `json:"yearsExperience,omitempty"`
}

// CandidateContacts defines model for CandidateContacts.
type CandidateContacts struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	Github   *string              `json:"github,omitempty"`
	Linkedin *string              `json:"linkedin,omitempty"`
	Phone    *string              `json:"phone,omitempty"`
	Telegram *string              `json:"telegram,omitempty"`
	Website  *string              `json:"website,omitempty"`
}

// CandidateProfile defines model for CandidateProfile.
type CandidateProfile struct {
	About            *string             `json:"about,omitempty"`
	CategoryId       *openapi_types.UUID `json:"categoryId,omitempty"`
	FirstName        *string             `json:"firstName,omitempty"`
	FspMemberId      *string             `json:"fspMemberId,omitempty"`
	GradeId          *openapi_types.UUID `json:"gradeId,omitempty"`
	Headline         *string             `json:"headline,omitempty"`
	LastName         *string             `json:"lastName,omitempty"`
	Location         *string             `json:"location,omitempty"`
	SpecializationId *openapi_types.UUID `json:"specializationId,omitempty"`
	UpdatedAt        time.Time           `json:"updatedAt"`
	UserId           openapi_types.UUID  `json:"userId"`
	YearsExperience  *float32            `json:"yearsExperience,omitempty"`
}

// CandidateTechnology defines model for CandidateTechnology.
type CandidateTechnology struct {
	Level        *int               `json:"level,omitempty"`
	TechnologyId openapi_types.UUID `json:"technologyId"`
}

// CategoryState defines model for CategoryState.
type CategoryState struct {
	CategoryId *openapi_types.UUID `json:"categoryId,omitempty"`
	GradeId    *openapi_types.UUID `json:"gradeId,omitempty"`
	History    *[]struct {
		CategoryId    *openapi_types.UUID         `json:"categoryId,omitempty"`
		EffectiveFrom *time.Time                  `json:"effectiveFrom,omitempty"`
		EffectiveTo   *time.Time                  `json:"effectiveTo,omitempty"`
		GradeId       *openapi_types.UUID         `json:"gradeId,omitempty"`
		Reason        *CategoryStateHistoryReason `json:"reason,omitempty"`
	} `json:"history,omitempty"`
	SpecializationId *openapi_types.UUID `json:"specializationId,omitempty"`
}

// CategoryStateHistoryReason defines model for CategoryState.History.Reason.
type CategoryStateHistoryReason string

// Experience defines model for Experience.
type Experience struct {
	Company     string              `json:"company"`
	Description *string             `json:"description,omitempty"`
	EndedAt     *openapi_types.Date `json:"endedAt,omitempty"`
	Id          openapi_types.UUID  `json:"id"`
	Position    string              `json:"position"`
	StartedAt   openapi_types.Date  `json:"startedAt"`
}

// ExperienceInput defines model for ExperienceInput.
type ExperienceInput struct {
	Company     string              `json:"company"`
	Description *string             `json:"description,omitempty"`
	EndedAt     *openapi_types.Date `json:"endedAt,omitempty"`
	Position    string              `json:"position"`
	StartedAt   openapi_types.Date  `json:"startedAt"`
}

// FSPAchievement defines model for FSPAchievement.
type FSPAchievement struct {
	Category   *string             `json:"category,omitempty"`
	EventDate  *openapi_types.Date `json:"eventDate,omitempty"`
	EventName  *string             `json:"eventName,omitempty"`
	ExternalId *string             `json:"externalId,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Place      *int                `json:"place,omitempty"`
	Score      *float32            `json:"score,omitempty"`
	Weight     *int                `json:"weight,omitempty"`
}

// FSPState defines model for FSPState.
type FSPState struct {
	Achievements *[]FSPAchievement `json:"achievements,omitempty"`
	FspMemberId  *string           `json:"fspMemberId,omitempty"`
	LinkedAt     *time.Time        `json:"linkedAt,omitempty"`
}

// Resume defines model for Resume.
type Resume struct {
	CreatedAt *time.Time              `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID     `json:"id,omitempty"`
	IsPrimary *bool                   `json:"isPrimary,omitempty"`
	Parsed    *map[string]interface{} `json:"parsed,omitempty"`
	Source    *ResumeSource           `json:"source,omitempty"`
	Title     *string                 `json:"title,omitempty"`
}

// ResumeSource defines model for Resume.Source.
type ResumeSource string

// ResumeInput defines model for ResumeInput.
type ResumeInput struct {
	Content   string `json:"content"`
	IsPrimary *bool  `json:"isPrimary,omitempty"`
	Title     string `json:"title"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	About           *string  `json:"about,omitempty"`
	FirstName       *string  `json:"firstName,omitempty"`
	Headline        *string  `json:"headline,omitempty"`
	LastName        *string  `json:"lastName,omitempty"`
	Location        *string  `json:"location,omitempty"`
	YearsExperience *float32 `json:"yearsExperience,omitempty"`
}

// Visibility defines model for Visibility.
type Visibility struct {
	Contacts   *bool `json:"contacts,omitempty"`
	Experience *bool `json:"experience,omitempty"`
	Fsp        *bool `json:"fsp,omitempty"`
	Resume     *bool `json:"resume,omitempty"`
}

// GetCandidateForEmployerParams defines parameters for GetCandidateForEmployer.
type GetCandidateForEmployerParams struct {
	// RevealContacts Показывать ли контакты (только при accepted-приглашении/отклике)
	RevealContacts *bool `form:"revealContacts,omitempty" json:"revealContacts,omitempty"`
}

// LinkFSPJSONBody defines parameters for LinkFSP.
type LinkFSPJSONBody struct {
	FspMemberId string `json:"fspMemberId"`
}

// UploadResumePDFMultipartBody defines parameters for UploadResumePDF.
type UploadResumePDFMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// ReplaceTechnologiesJSONBody defines parameters for ReplaceTechnologies.
type ReplaceTechnologiesJSONBody = []CandidateTechnology

// ReplaceMyContactsJSONRequestBody defines body for ReplaceMyContacts for application/json ContentType.
type ReplaceMyContactsJSONRequestBody = CandidateContacts

// AddExperienceJSONRequestBody defines body for AddExperience for application/json ContentType.
type AddExperienceJSONRequestBody = ExperienceInput

// LinkFSPJSONRequestBody defines body for LinkFSP for application/json ContentType.
type LinkFSPJSONRequestBody LinkFSPJSONBody

// UpdateMyProfileJSONRequestBody defines body for UpdateMyProfile for application/json ContentType.
type UpdateMyProfileJSONRequestBody = UpdateProfileRequest

// CreateResumeJSONRequestBody defines body for CreateResume for application/json ContentType.
type CreateResumeJSONRequestBody = ResumeInput

// UploadResumePDFMultipartRequestBody defines body for UploadResumePDF for multipart/form-data ContentType.
type UploadResumePDFMultipartRequestBody UploadResumePDFMultipartBody

// ReplaceTechnologiesJSONRequestBody defines body for ReplaceTechnologies for application/json ContentType.
type ReplaceTechnologiesJSONRequestBody = ReplaceTechnologiesJSONBody

// UpdateMyVisibilityJSONRequestBody defines body for UpdateMyVisibility for application/json ContentType.
type UpdateMyVisibilityJSONRequestBody = Visibility

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /candidates/{userId})
	GetCandidateForEmployer(c *gin.Context, userId openapi_types.UUID, params GetCandidateForEmployerParams)

	// (GET /healthz)
	Healthz(c *gin.Context)

	// (GET /me/category)
	GetMyCategory(c *gin.Context)

	// (GET /me/contacts)
	GetMyContacts(c *gin.Context)

	// (PUT /me/contacts)
	ReplaceMyContacts(c *gin.Context)

	// (GET /me/experiences)
	ListExperiences(c *gin.Context)

	// (POST /me/experiences)
	AddExperience(c *gin.Context)

	// (GET /me/fsp)
	GetMyFSP(c *gin.Context)

	// (PUT /me/fsp)
	LinkFSP(c *gin.Context)

	// (GET /me/profile)
	GetMyProfile(c *gin.Context)

	// (PATCH /me/profile)
	UpdateMyProfile(c *gin.Context)

	// (GET /me/resumes)
	ListResumes(c *gin.Context)

	// (POST /me/resumes)
	CreateResume(c *gin.Context)

	// (POST /me/resumes/upload)
	UploadResumePDF(c *gin.Context)

	// (PUT /me/technologies)
	ReplaceTechnologies(c *gin.Context)

	// (GET /me/visibility)
	GetMyVisibility(c *gin.Context)

	// (PUT /me/visibility)
	UpdateMyVisibility(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetCandidateForEmployer operation middleware
func (siw *ServerInterfaceWrapper) GetCandidateForEmployer(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCandidateForEmployerParams

	// ------------- Optional query parameter "revealContacts" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "revealContacts", c.Request.URL.Query(), &params.RevealContacts, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter revealContacts: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCandidateForEmployer(c, userId, params)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Healthz(c)
}

// GetMyCategory operation middleware
func (siw *ServerInterfaceWrapper) GetMyCategory(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyCategory(c)
}

// GetMyContacts operation middleware
func (siw *ServerInterfaceWrapper) GetMyContacts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyContacts(c)
}

// ReplaceMyContacts operation middleware
func (siw *ServerInterfaceWrapper) ReplaceMyContacts(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReplaceMyContacts(c)
}

// ListExperiences operation middleware
func (siw *ServerInterfaceWrapper) ListExperiences(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListExperiences(c)
}

// AddExperience operation middleware
func (siw *ServerInterfaceWrapper) AddExperience(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddExperience(c)
}

// GetMyFSP operation middleware
func (siw *ServerInterfaceWrapper) GetMyFSP(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyFSP(c)
}

// LinkFSP operation middleware
func (siw *ServerInterfaceWrapper) LinkFSP(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LinkFSP(c)
}

// GetMyProfile operation middleware
func (siw *ServerInterfaceWrapper) GetMyProfile(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyProfile(c)
}

// UpdateMyProfile operation middleware
func (siw *ServerInterfaceWrapper) UpdateMyProfile(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMyProfile(c)
}

// ListResumes operation middleware
func (siw *ServerInterfaceWrapper) ListResumes(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListResumes(c)
}

// CreateResume operation middleware
func (siw *ServerInterfaceWrapper) CreateResume(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateResume(c)
}

// UploadResumePDF operation middleware
func (siw *ServerInterfaceWrapper) UploadResumePDF(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UploadResumePDF(c)
}

// ReplaceTechnologies operation middleware
func (siw *ServerInterfaceWrapper) ReplaceTechnologies(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ReplaceTechnologies(c)
}

// GetMyVisibility operation middleware
func (siw *ServerInterfaceWrapper) GetMyVisibility(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetMyVisibility(c)
}

// UpdateMyVisibility operation middleware
func (siw *ServerInterfaceWrapper) UpdateMyVisibility(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateMyVisibility(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Healthz)
	router.GET(options.BaseURL+"/me/profile", wrapper.GetMyProfile)
	router.PATCH(options.BaseURL+"/me/profile", wrapper.UpdateMyProfile)
	router.GET(options.BaseURL+"/me/contacts", wrapper.GetMyContacts)
	router.PUT(options.BaseURL+"/me/contacts", wrapper.ReplaceMyContacts)
	router.GET(options.BaseURL+"/me/visibility", wrapper.GetMyVisibility)
	router.PUT(options.BaseURL+"/me/visibility", wrapper.UpdateMyVisibility)
	router.GET(options.BaseURL+"/me/resumes", wrapper.ListResumes)
	router.POST(options.BaseURL+"/me/resumes", wrapper.CreateResume)
	router.POST(options.BaseURL+"/me/resumes/upload", wrapper.UploadResumePDF)
	router.GET(options.BaseURL+"/me/experiences", wrapper.ListExperiences)
	router.POST(options.BaseURL+"/me/experiences", wrapper.AddExperience)
	router.PUT(options.BaseURL+"/me/technologies", wrapper.ReplaceTechnologies)
	router.GET(options.BaseURL+"/me/category", wrapper.GetMyCategory)
	router.GET(options.BaseURL+"/me/fsp", wrapper.GetMyFSP)
	router.PUT(options.BaseURL+"/me/fsp", wrapper.LinkFSP)
	router.GET(options.BaseURL+"/candidates/:userId", wrapper.GetCandidateForEmployer)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFrdbhvHFX6VxbQXCUCLcpMCAe9c20rdJo1gOe2FIQTD3UNy4v3z7KxqxiAg0QXSQkaFFgEKBEjdFH0A",
	"WhYjWraYVzjzCn2SYmaXy1lyuNzKknIncv7Oz3fO+c6hnhI3CuIohFAkpPWUJG4PAqr/vE1Dj3lUwG3K",
	"PfVFzKMYuGCgl10qoBvx/j291ol4QAVpkTRlHmkQ0Y+BtEgiOAu7ZNAgbhQK6maPeJC4nMWCRSFpkTD1",
	"/YaDY3mAb3Di4BlO8VwOcYRncigPHTzHsSP3cSQP8Ezuy0P1LWmQKITPOqT18Cn5OYcOaZGfNee6NHNF",
	"mnMtZgIMGk9n4qmnyWB30CAeS2Kf9n9HA1ASLonfSeJlE1C3x2APAvXg7SgNhXGUhQK6wNXZNiRi26eu",
	"cfPDYr2RCaFk6NFka2fbuKMdRT7QkAwGhUGj9pfgCnVrl1MPahq/B9TzWVgSIF813k9icBn12VdUeabm",
	"1QLcXhj5UTe3CRMQ6D9qOeXB7HSfzHWknFP9OU2A1xSjD5Qnd5/EwBmEZUuHadA2DW0z5jJKlpwNAWV+",
	"SZbsG4swXSZ6abva2D4LH4HHwupdcS9a5zUBPnQ5Dap3/RHaCRNQtiVnhfTLZyrNtM2jDvPBEhLtKBXV",
	"otRJHLZzHcYTUQ5Q67Yk/hSUx7P7V29cG0C2Q/Uiyad1JPUjl2Y58HKi0nY6jZW7vFuidEx9d0OwAGzo",
	"fbeoK850/IgKQzZLGHJ4nDIOnlrOXzUl3q1CoJE5lkDowx7oUA3oExakAWn9skECFmZ/32xYcnSRxurV",
	"swXhS6ftYmeY3xFUwMVq6eVBmCUi4v1Ssn6n0g6dDriC7cEWj4L6OCuOPYjWHLqQ6sZLHGiShRmECgGq",
	"+jLBqP+FgERhlIOgj9R7AQ1T6hsuNBy+5NTFcvUukWq7vxxYCy6KgpiGfStXKdGrqtQCoWdNDZWGZ/Vs",
	"HkcJK0tgLCaCclH99KpQ06/NtDeeMS/drTTmvTDOStQ7WtSE8kUMeVUWuoBxtna2b8257OqEsAZOexCK",
	"O3SBZay1gz62knjDEwE8pP66al4XljV4eOJGvJJBKjrFuj0r3R/Yzbsi8ZsdRG32vOAtSyaqzYEyFrqW",
	"HdTLV/chSQNbruLw/3KQmt5kyTZnATWBOW+aGiSmPAF9E/U8HQnU3zZEEzyFuYq5IiYQopRnaJnVjbw+",
	"NEjsdb5IYz+iSq4uhMCVipbC0SCCCd+G7dUmXJmhQgGlJnOFJTzo0NQXpNWhflJoaFqmQqYSr9HbGsXL",
	"ttzxeWw0BPfhcapK6rq+wOysl2l9ZedqLC7TbHNxiV3XaRdnsW71zu9ZwtrMZ6Jvd86scVy2N9ieMtbz",
	"8cLyAi9iav1MQCEW3JQz0d9RqSITrA2UA7+Vit7809YssH7zhweqOOjd6nK9Oo+0nhAxGaiLWdjRLC0H",
	"jkppzrZPhQpR57/73zgFMXd2gO8xV8FmD3iSzXhubmxubCp9ohhCGjPSIh9s3NzYVJFERU8L2nRnVyTN",
	"p1k7MFDfd0EsD43w7zjFUzzWc6G/4AjHcujgGY7kvhziVH6NZ/KZgy9xjKcLIyWc4vGGg98ujpl+xKk8",
	"wmN5JIfyQB45eucb+VydzlYP8A2OHeq6EAvwNohWhxdsj3wMojDDVsTvBrEf9bU9Y8ppAAJ4ogdWqu3X",
	"iqtsowE873/m8Zelpyzr1+pJloz0AqfKJngqD/EYR3Ionzv2Idt7C9rKfZwUmt7IPuMrfIMj+Wcc4zlO",
	"cNLEqRzimboQz3D8Pmlkij1OgffnmnHYA+oXgxVTo3WJarCrIyCOwiQD8y82NxcyIY1jn2WR3vwyZ/nz",
	"B+pNBin3MpQvmO9bE0440vjCczzBCZ4oa+JIQfrDzQ8t+PwOxw6e4whf44k22FQ9MWiQZg+oL3pfGdAu",
	"o+jX+bpd9fIzn/22FPak9VCX5mYATZOzWd/5GMSn/VljSq7U0GbzazP0v3Gs4lUFsjzKwniIY3yFU4U7",
	"edTEV3Ifx8qWjkLvRB5ot+jFmV2VzkYSrtB5DsVrAFcxdrYCrBSF2Z689pcFvw+auS4Ir4vtryKvf9Vy",
	"l5PS4Cc33D/xpQopPFYZ2QyuAJrzWrsaB5+wRNw19r2jQrVou0E3lii7VcUf5aEc6l8+8KVKtQVAosSi",
	"0i3PM164GnQsNtG1sHHzCp63WuwbnOJLHFlBkROs1Ulha2f7KvNB0QLaBH+hq+uxPMLTvM44+B/8Hl84",
	"9+7ofHeiyIcc4gR/yIqvPHLew7c4VZ8V8XmpfxV7rgr3M7VTHuLb9yvSyScsfDTT+GIwKbNfa8O5qqsw",
	"Ny93FLXTTYURRwvej+c/V6xGwOw3jetIbrO3VqFhKv+EE0XHrJxDu5UKt7esSdaNlZW5/Dxg7fl+qkJR",
	"ZUujTsi/4Tmey0N8ndHbwsQGTrJuq7ps3M/3XEfJyCcqdcrFv1SnI/+Kb3FcVSVu61lMfu/VgMOcYVxz",
	"gZjZy2Kf73W/eLKUGnKXN/NhjspsueEWLvgHjhQLlc/yJL19Z8uRB46qNzkXHckD1Sbiqeb9x/qpCY7x",
	"7VKj+Ll+LJN2+85WpSOC1Bcsplw0Vf93w6OCVmbiPM8VzWKbhVTz+zVJWZ27WDa+Fv8Z+HbkgenMhm7O",
	"dWueDfyy9RMcy338ASeqPk7wNKMF8usiD4yd/Ab9wYDE4r80VBHyB+bei8fT5f3XxEXLZxWj3ivNvVZX",
	"UGM+doWJ33jFBpTvVBzKocrw+BrPFH061sVzoghTRqMqmNGsgC7ocvlpclGNy3NaeSBQngA+3B3sqmW+",
	"N5tFpdzPJ32tZtOPXOr3okS0Ptr86AMy2B38LwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
