// This file is auto-generated by @hey-api/openapi-ts

export const ErrorSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'string',
            example: 'EMAIL_TAKEN'
        },
        message: {
            type: 'string',
            example: 'email already registered'
        }
    },
    required: ['code', 'message']
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['candidate', 'employer', 'admin']
} as const;

export const UserStatusSchema = {
    type: 'string',
    enum: ['active', 'blocked', 'deleted']
} as const;

export const UserSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        email: {
            type: 'string',
            format: 'email'
        },
        role: {
            '$ref': '#/components/schemas/UserRole'
        },
        status: {
            '$ref': '#/components/schemas/UserStatus'
        },
        emailVerifiedAt: {
            type: ['string', 'null'],
            format: 'date-time'
        },
        createdAt: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'email', 'role', 'status', 'createdAt']
} as const;

export const RegisterRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email'
        },
        password: {
            type: 'string',
            minLength: 8,
            maxLength: 128
        },
        role: {
            '$ref': '#/components/schemas/UserRole'
        }
    },
    required: ['email', 'password', 'role']
} as const;

export const LoginRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email'
        },
        password: {
            type: 'string'
        }
    },
    required: ['email', 'password']
} as const;

export const TokenRequestSchema = {
    type: 'object',
    properties: {
        token: {
            type: 'string'
        }
    },
    required: ['token']
} as const;

export const RefreshRequestSchema = {
    type: 'object',
    properties: {
        refreshToken: {
            type: 'string'
        }
    },
    required: ['refreshToken']
} as const;

export const ResetPasswordRequestSchema = {
    type: 'object',
    properties: {
        token: {
            type: 'string'
        },
        newPassword: {
            type: 'string',
            minLength: 8,
            maxLength: 128
        }
    },
    required: ['token', 'newPassword']
} as const;

export const ExternalCallbackRequestSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'string'
        },
        redirectUri: {
            type: 'string',
            format: 'uri'
        }
    },
    required: ['code']
} as const;

export const TokenPairSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string'
        },
        refreshToken: {
            type: 'string'
        },
        accessExpiresAt: {
            type: 'string',
            format: 'date-time'
        },
        refreshExpiresAt: {
            type: 'string',
            format: 'date-time'
        },
        user: {
            '$ref': '#/components/schemas/User'
        }
    },
    required: ['accessToken', 'refreshToken', 'accessExpiresAt', 'refreshExpiresAt', 'user']
} as const;