// This file is auto-generated by @hey-api/openapi-ts

export type Error = {
    code: string;
    message: string;
};

export type ExternalCallbackRequest = {
    code: string;
    redirectUri?: string;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type RegisterRequest = {
    email: string;
    password: string;
    role: UserRole;
};

export type ResetPasswordRequest = {
    token: string;
    newPassword: string;
};

export type TokenPair = {
    accessToken: string;
    refreshToken: string;
    accessExpiresAt: string;
    refreshExpiresAt: string;
    user: User;
};

export type TokenRequest = {
    token: string;
};

export type User = {
    id: string;
    email: string;
    role: UserRole;
    status: UserStatus;
    emailVerifiedAt?: (string) | null;
    createdAt: string;
};

export type UserRole = 'candidate' | 'employer' | 'admin';

export type UserStatus = 'active' | 'blocked' | 'deleted';

export type HealthzResponse = ({
    status: string;
});

export type HealthzError = unknown;

export type RegisterData = {
    body: RegisterRequest;
};

export type RegisterResponse = (User);

export type RegisterError = (Error);

export type ConfirmEmailData = {
    body: TokenRequest;
};

export type ConfirmEmailResponse = (void);

export type ConfirmEmailError = (Error);

export type ResendConfirmationData = {
    body: {
        email: string;
    };
};

export type ResendConfirmationResponse = (unknown);

export type ResendConfirmationError = (Error);

export type LoginData = {
    body: LoginRequest;
};

export type LoginResponse = (TokenPair);

export type LoginError = (Error);

export type RefreshData = {
    body: RefreshRequest;
};

export type RefreshResponse = (TokenPair);

export type RefreshError = (Error);

export type LogoutData = {
    body: RefreshRequest;
};

export type LogoutResponse = (void);

export type LogoutError = (Error);

export type ForgotPasswordData = {
    body: {
        email: string;
    };
};

export type ForgotPasswordResponse = (unknown);

export type ForgotPasswordError = unknown;

export type ResetPasswordData = {
    body: ResetPasswordRequest;
};

export type ResetPasswordResponse = (void);

export type ResetPasswordError = (Error);

export type MeResponse = (User);

export type MeError = (Error);

export type DeleteMeData = {
    /**
     * Подтверждение паролем — защита от CSRF и случайного удаления
     */
    body: {
        password: string;
        reason?: (string) | null;
    };
};

export type DeleteMeResponse = (void);

export type DeleteMeError = (Error);

export type ExternalCallbackData = {
    body: ExternalCallbackRequest;
    path: {
        provider: string;
    };
};

export type ExternalCallbackResponse = (TokenPair);

export type ExternalCallbackError = (Error);

export type InternalGetUserData = {
    path: {
        userId: string;
    };
};

export type InternalGetUserResponse = (User);

export type InternalGetUserError = (Error);